#!/usr/bin/env python3
"""
MoneyControl Data Fetcher Pipeline
==================================
Crawls and parses MoneyControl API endpoints and widgets using curl_cffi Chrome impersonation.
Populates intraday_ohlcv, insider_trades, bulk_deals, proprietary_scores_history, and new estimates tables.
Fills critical data gaps for daily ML model features.

Run: python src/server/moneycontrol_fetcher.py --symbols INFY RELIANCE
     python src/server/moneycontrol_fetcher.py --batch-size 150
"""

import polars as pl
from pydantic import BaseModel
from base_fetcher import BaseFetcher, governed_fetcher

class MoneycontrolFetcherSchema(BaseModel):
    symbol: str | None = None
    date: str | None = None

class MoneycontrolFetcherBaseFetcher(BaseFetcher[MoneycontrolFetcherSchema]):
    fetcher_name = 'MoneycontrolFetcher'
    domain = 'moneycontrol.com'
    schema = MoneycontrolFetcherSchema
    min_interval_sec = 0.5


import os
import re
import sys
import time
import argparse
import datetime
from urllib.parse import urlparse, parse_qs
from bs4 import BeautifulSoup
from sqlalchemy import text
from curl_cffi import requests

# Set sys.path so we can import db_compat
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from db_compat import get_engine, use_postgres
from data_integrity_repair import parse_loose_date

HEADERS = {
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "Origin": "https://www.moneycontrol.com",
    "Referer": "https://www.moneycontrol.com/",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-site",
}

def clean_float(val):
    if val is None or val == "":
        return None
    try:
        if isinstance(val, (int, float)):
            return float(val)
        return float(str(val).replace(",", "").replace("%", "").strip())
    except ValueError:
        return None

def clean_int(val):
    if val is None or val == "":
        return None
    try:
        if isinstance(val, int):
            return val
        return int(float(str(val).replace(",", "").replace("%", "").strip()))
    except ValueError:
        return None

def make_slug(name, mcsymbol):
    cleaned = name.lower()
    # Remove common corporate suffixes to approximate MoneyControl slugs
    cleaned = re.sub(r'\b(ltd|limited|corp|corporation|inc|industries|india)\b', '', cleaned)
    cleaned = re.sub(r'[^a-z0-9\s-]', '', cleaned)
    cleaned = '-'.join(cleaned.split())
    return f"{cleaned}/{mcsymbol}"

def ensure_tables_exist(engine):
    """Ensure the target tables exist in the database (handles both Postgres and SQLite)."""
    # SQLite uses INTEGER PRIMARY KEY AUTOINCREMENT
    # Postgres uses BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    is_pg = use_postgres()
    id_type = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    float_type = "DOUBLE PRECISION" if is_pg else "REAL"

    ddls = [
        # 1. mc_analyst_ratings
        f"""CREATE TABLE IF NOT EXISTS mc_analyst_ratings (
            symbol TEXT NOT NULL,
            final_rating TEXT,
            analyst_count INTEGER,
            buy_count INTEGER,
            outperform_count INTEGER,
            hold_count INTEGER,
            underperform_count INTEGER,
            sell_count INTEGER,
            fetched_at TEXT NOT NULL,
            PRIMARY KEY (symbol, fetched_at)
        )""",
        # 2. mc_price_forecast
        f"""CREATE TABLE IF NOT EXISTS mc_price_forecast (
            symbol TEXT NOT NULL,
            high {float_type},
            mean {float_type},
            low {float_type},
            fetched_at TEXT NOT NULL,
            PRIMARY KEY (symbol, fetched_at)
        )""",
        # 3. mc_earnings_forecast
        f"""CREATE TABLE IF NOT EXISTS mc_earnings_forecast (
            symbol TEXT NOT NULL,
            date TEXT NOT NULL,
            metric_type TEXT NOT NULL,
            high {float_type},
            low {float_type},
            avg {float_type},
            actual {float_type},
            PRIMARY KEY (symbol, date, metric_type)
        )""",
        # 4. mc_estimates_hits_misses
        # fetched_at added 2026-08-13 (migration 1786990000000) -- had no timestamp column at
        # all, so it was structurally unmeasurable by any freshness check. See dataQualityChecks.ts.
        f"""CREATE TABLE IF NOT EXISTS mc_estimates_hits_misses (
            symbol TEXT NOT NULL,
            quarter TEXT NOT NULL,
            actual {float_type},
            estimates {float_type},
            surprise {float_type},
            type TEXT,
            fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (symbol, quarter)
        )""",
        # 5. mc_seasonality_best_stocks (fetched_at added 2026-08-13, see note above)
        f"""CREATE TABLE IF NOT EXISTS mc_seasonality_best_stocks (
            tab_type TEXT NOT NULL,
            sc_id TEXT NOT NULL,
            sc_fullname TEXT,
            year INTEGER NOT NULL,
            month INTEGER NOT NULL,
            avg_pct {float_type},
            max_pct {float_type},
            min_pct {float_type},
            total_yr {float_type},
            tot_yr {float_type},
            fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (tab_type, sc_id, year, month)
        )""",
        # 6. mc_stock_vitals (fetched_at added 2026-08-13, see note above)
        f"""CREATE TABLE IF NOT EXISTS mc_stock_vitals (
            symbol TEXT NOT NULL,
            metric_name TEXT NOT NULL,
            score TEXT,
            description TEXT,
            fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (symbol, metric_name)
        )""",
        # 7. mc_stock_scans (fetched_at added 2026-08-13, see note above)
        f"""CREATE TABLE IF NOT EXISTS mc_stock_scans (
            symbol TEXT NOT NULL,
            scan_name TEXT NOT NULL,
            description TEXT,
            fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (symbol, scan_name)
        )""",
        # 8. mc_general_metrics
        f"""CREATE TABLE IF NOT EXISTS mc_general_metrics (
            symbol TEXT NOT NULL,
            source_api TEXT NOT NULL,
            metric_group TEXT NOT NULL,
            metric_name TEXT NOT NULL,
            metric_value_num {float_type},
            metric_value_text TEXT,
            fetched_at TEXT NOT NULL,
            PRIMARY KEY (symbol, source_api, metric_group, metric_name, fetched_at)
        )""",
        # 9. Ensure bulk_deals and insider_trades exist in standard schema
        f"""CREATE TABLE IF NOT EXISTS insider_trades (
            id {id_type},
            symbol TEXT NOT NULL,
            "acquirerName" TEXT NOT NULL,
            category TEXT NOT NULL,
            "typeOfTransaction" TEXT NOT NULL,
            quantity BIGINT NOT NULL,
            "valueInr" {float_type} NOT NULL,
            date TEXT NOT NULL,
            date_iso TEXT
        )""",
        # Self-healing for any DB created before the 2026-07-30 date_iso fix (production
        # already has it via data_integrity_repair.py --insider-dates). Postgres-only syntax;
        # the per-statement try/except below tolerates it failing on the SQLite dev fallback.
        "ALTER TABLE insider_trades ADD COLUMN IF NOT EXISTS date_iso TEXT",
        f"""CREATE TABLE IF NOT EXISTS bulk_deals (
            id {id_type},
            date TEXT NOT NULL,
            symbol TEXT NOT NULL,
            "clientName" TEXT NOT NULL,
            "dealType" TEXT NOT NULL,
            quantity BIGINT NOT NULL,
            price {float_type} NOT NULL,
            "valueCr" {float_type} NOT NULL,
            source TEXT
        )""",
        # 10. Ensure intraday_ohlcv exists
        f"""CREATE TABLE IF NOT EXISTS intraday_ohlcv (
            symbol TEXT NOT NULL,
            datetime TEXT NOT NULL,
            open {float_type},
            high {float_type},
            low {float_type},
            close {float_type},
            volume BIGINT,
            vwap {float_type},
            interval TEXT DEFAULT '15m',
            PRIMARY KEY (symbol, datetime, interval)
        )"""
    ]

    with engine.begin() as conn:
        # Create tables
        for ddl in ddls:
            try:
                conn.execute(text(ddl))
            except Exception as e:
                print(f"[MC Fetcher] DDL Error: {e} - Query: {ddl[:80]}...", file=sys.stderr)

        # Create indexes
        indexes = [
            "CREATE INDEX IF NOT EXISTS idx_insider_sym ON insider_trades(symbol, date DESC)",
            "CREATE INDEX IF NOT EXISTS idx_bulk_sym_date ON bulk_deals(symbol, date DESC)",
            "CREATE INDEX IF NOT EXISTS idx_intra_sym ON intraday_ohlcv(symbol, datetime DESC)"
        ]
        for idx in indexes:
            try:
                conn.execute(text(idx))
            except Exception as e:
                pass


class MoneyControlFetcher:
    def __init__(self, target_symbols=None, batch_size=100):
        self.engine = get_engine()
        self.target_symbols = target_symbols
        self.batch_size = batch_size
        self.date_today = datetime.datetime.now().strftime("%Y-%m-%d")
        ensure_tables_exist(self.engine)

    def _resolve_target_batch(self) -> list[dict]:
        """Resolves the batch of active stocks to fetch using priority rules:
        1. Watchlist symbols
        2. Symbols with active signals/recommendations (last 7 days)
        3. Top 300 market cap symbols
        4. Rolling batch from the rest of the active stock universe
        """
        if self.target_symbols:
            # Manual filter override
            placeholders = ", ".join(f"'{s}'" for s in self.target_symbols)
            with self.engine.connect() as conn:
                res = conn.execute(text(f"""
                    SELECT symbol, name, mcsymbol 
                    FROM nse_stocks 
                    WHERE symbol IN ({placeholders}) AND status = 'ACTIVE'
                """)).fetchall()
                return [dict(r._mapping) for r in res]

        watchlist_syms = []
        active_signal_syms = []
        top_mktcap_syms = []
        rolling_syms = []

        with self.engine.connect() as conn:
            # 1. Watchlist symbols
            res = conn.execute(text("SELECT DISTINCT symbol FROM watchlist")).fetchall()
            watchlist_syms = [r[0] for r in res]

            # 2. Recent signals (past 7 days)
            cutoff_date = (datetime.datetime.now() - datetime.timedelta(days=7)).strftime("%Y-%m-%d")
            res = conn.execute(text("""
                SELECT DISTINCT symbol FROM unified_signals 
                WHERE signal_date >= :cutoff
            """), {"cutoff": cutoff_date}).fetchall()
            active_signal_syms = [r[0] for r in res]

            # 3. Top 300 active market cap symbols
            res = conn.execute(text("""
                SELECT symbol FROM nse_stocks 
                WHERE status = 'ACTIVE' AND market_cap IS NOT NULL 
                ORDER BY market_cap DESC LIMIT 300
            """)).fetchall()
            top_mktcap_syms = [r[0] for r in res]

            # Union of daily high-priority tickers
            high_priority = list(set(watchlist_syms + active_signal_syms + top_mktcap_syms))

            # Query all active stocks with mcsymbol
            all_active = [
                dict(r._mapping) for r in conn.execute(text("""
                    SELECT symbol, name, mcsymbol 
                    FROM nse_stocks 
                    WHERE status = 'ACTIVE' AND mcsymbol IS NOT NULL AND mcsymbol != ''
                """)).fetchall()
            ]

        # Filter high priority from all active
        hp_stocks = [s for s in all_active if s["symbol"] in high_priority]
        non_hp_stocks = [s for s in all_active if s["symbol"] not in high_priority]

        # 4. Rolling batch of remaining stocks
        # Get the cursor index from app_settings
        cursor = 0
        with self.engine.connect() as conn:
            try:
                res = conn.execute(text("SELECT value FROM app_settings WHERE key = 'mc_fetcher_cursor'")).fetchone()
                if res:
                    cursor = int(res[0])
            except Exception:
                pass

        # Select a slice of remaining stocks
        rolling_batch_size = max(50, self.batch_size - len(hp_stocks))
        if cursor >= len(non_hp_stocks):
            cursor = 0

        rolling_slice = non_hp_stocks[cursor : cursor + rolling_batch_size]
        new_cursor = cursor + len(rolling_slice)
        if new_cursor >= len(non_hp_stocks):
            new_cursor = 0

        # Update cursor in app_settings
        with self.engine.begin() as conn:
            # Ensure app_settings table can store it
            if use_postgres():
                conn.execute(text("""
                    INSERT INTO app_settings (key, value, "updatedAt") 
                    VALUES ('mc_fetcher_cursor', :val, now())
                    ON CONFLICT(key) DO UPDATE SET value = excluded.value, "updatedAt" = now()
                """), {"val": str(new_cursor)})
            else:
                conn.execute(text("""
                    INSERT OR REPLACE INTO app_settings (key, value, updatedAt) 
                    VALUES ('mc_fetcher_cursor', :val, CURRENT_TIMESTAMP)
                """), {"val": str(new_cursor)})

        target_batch = hp_stocks + rolling_slice
        # Limit total batch size
        target_batch = target_batch[:self.batch_size]
        
        print(f"[MC Fetcher] Targeting {len(target_batch)} stocks "
              f"(High-Priority: {len(hp_stocks)}, Rolling Batch: {len(rolling_slice)})")
        return target_batch

    def _fetch_url(self, url: str) -> requests.Response | None:
        """Fetch URL with curl_cffi chrome impersonation and retries."""
        for attempt in range(3):
            try:
                # Add delay to be gentle on servers
                time.sleep(1.0)
                r = requests.get(url, headers=HEADERS, impersonate="chrome120", timeout=15)
                if r.status_code == 200:
                    return r
                elif r.status_code in (429, 503):
                    print(f"[MC Fetcher] Rate limited ({r.status_code}) fetching {url[:60]}, backing off...")
                    time.sleep(5.0 * (attempt + 1))
            except Exception as e:
                print(f"[MC Fetcher] Exception fetching {url[:60]}: {e}", file=sys.stderr)
                time.sleep(2.0)
        return None

    def fetch_stock_data(self, stock: dict):
        symbol = stock["symbol"]
        mcsymbol = stock["mcsymbol"]
        name = stock["name"]
        slug = make_slug(name, mcsymbol)

        print(f"[MC Fetcher] Crawling {symbol} (mcsymbol: {mcsymbol})...")

        # Endpoints
        endpoints = {
            "technicals": f"https://api.moneycontrol.com/mcapi/technicals/v2/details?scId={mcsymbol}&dur=D&deviceType=W",
            "essentials": f"https://api.moneycontrol.com/mcapi/extdata/v2/mc-essentials?deviceType=W&scId={mcsymbol}&type=ed",
            "insights": f"https://api.moneycontrol.com/mcapi/extdata/v2/mc-insights?scId={mcsymbol}&type=c&deviceType=W&appVersion=185",
            "analyst_rating": f"https://api.moneycontrol.com/mcapi/v1/stock/estimates/analyst-rating?deviceType=W&scId={mcsymbol}&ex=N",
            "price_forecast": f"https://api.moneycontrol.com/mcapi/v1/stock/estimates/price-forecast?scId={mcsymbol}&ex=N&deviceType=W",
            "earning_forecast": f"https://api.moneycontrol.com/mcapi/v1/stock/estimates/earning-forecast?scId={mcsymbol}&ex=N&deviceType=W&frequency=12&financialType=C",
            "hits_misses": f"https://api.moneycontrol.com/mcapi/v1/stock/estimates/hits-misses?deviceType=W&scId={mcsymbol}&ex=N&type=eps&financialType=C",
            "widget_insider": f"https://www.moneycontrol.com/mc/widget/mcinsider?classic=true&sc_did={mcsymbol}&sc_id={mcsymbol}",
            "widget_vitals": f"https://www.moneycontrol.com/mc/widget/stockvitals?classic=true&sc_did={mcsymbol}&sc_id={mcsymbol}&slug={slug}",
            "widget_scans": f"https://www.moneycontrol.com/mc/widget/stockscans?classic=true&sc_did={mcsymbol}&sc_id={mcsymbol}",
        }

        # Fetch Intraday 15m OHLCV bars
        self._fetch_intraday(symbol)

        # Iterate and parse endpoints
        for key, url in endpoints.items():
            resp = self._fetch_url(url)
            if not resp:
                continue

            try:
                if key == "widget_insider":
                    self._parse_insider(symbol, resp.text)
                elif key == "widget_vitals":
                    self._parse_vitals(symbol, resp.text)
                elif key == "widget_scans":
                    self._parse_scans(symbol, resp.text)
                else:
                    data = resp.json()
                    # MoneyControl APIs use either success=1, success=true, or status=200
                    is_success = (
                        data.get("success") == 1
                        or data.get("success") is True
                        or data.get("status") == 200
                        or data.get("status") == "success"
                    )
                    if not data or not is_success or not data.get("data"):
                        continue
                    payload = data["data"]
                    
                    if key == "technicals":
                        self._parse_general_technicals(symbol, payload)
                    elif key == "essentials":
                        self._parse_general_essentials(symbol, payload)
                    elif key == "insights":
                        self._parse_general_insights(symbol, payload)
                    elif key == "analyst_rating":
                        self._parse_analyst_rating(symbol, payload)
                    elif key == "price_forecast":
                        self._parse_price_forecast(symbol, payload)
                    elif key == "earning_forecast":
                        self._parse_earnings_forecast(symbol, payload)
                    elif key == "hits_misses":
                        self._parse_hits_misses(symbol, payload)
            except Exception as e:
                print(f"[MC Fetcher] Parse Error for {symbol} ({key}): {e}", file=sys.stderr)

    def _fetch_intraday(self, symbol: str):
        """Fetch 15-minute resolution intraday bars for the last 5 days."""
        to_ts = int(time.time())
        from_ts = to_ts - 5 * 24 * 3600
        url = (
            f"https://priceapi.moneycontrol.com/techCharts/indianMarket/stock/history?"
            f"symbol={symbol}&resolution=15&from={from_ts}&to={to_ts}&countback=300&currencyCode=INR"
        )
        resp = self._fetch_url(url)
        if not resp:
            return

        try:
            data = resp.json()
            if not data or not data.get("t"):
                return
            t_arr = data.get("t", [])
            o_arr = data.get("o", [])
            h_arr = data.get("h", [])
            l_arr = data.get("l", [])
            c_arr = data.get("c", [])
            v_arr = data.get("v", [])

            rows = []
            for i in range(len(t_arr)):
                dt_str = datetime.datetime.fromtimestamp(t_arr[i]).strftime("%Y-%m-%d %H:%M:%S")
                rows.append({
                    "symbol": symbol,
                    "datetime": dt_str,
                    "open": clean_float(o_arr[i]),
                    "high": clean_float(h_arr[i]),
                    "low": clean_float(l_arr[i]),
                    "close": clean_float(c_arr[i]),
                    "volume": clean_int(v_arr[i]),
                    "vwap": None,
                    "interval": "15m"
                })

            if rows:
                with self.engine.begin() as conn:
                    # Write to database
                    for r in rows:
                        conn.execute(text("""
                            INSERT INTO intraday_ohlcv (symbol, datetime, open, high, low, close, volume, vwap, interval)
                            VALUES (:symbol, :datetime, :open, :high, :low, :close, :volume, :vwap, :interval)
                            ON CONFLICT(symbol, datetime, interval) DO UPDATE SET
                                open   = excluded.open,
                                high   = excluded.high,
                                low    = excluded.low,
                                close  = excluded.close,
                                volume = excluded.volume,
                                vwap   = excluded.vwap
                        """), r)
                print(f"[MC Fetcher] Ingested {len(rows)} intraday 15m bars for {symbol}")
        except Exception as e:
            print(f"[MC Fetcher] Intraday parse error for {symbol}: {e}", file=sys.stderr)

    def _parse_insider(self, symbol: str, html: str):
        soup = BeautifulSoup(html, "html.parser")
        boxes = soup.find_all(class_="bd_bx")
        rows = []
        for box in boxes:
            date_el = box.find(class_="br_date")
            date_raw = date_el.get_text(strip=True) if date_el else ""
            if not date_raw:
                continue

            # Convert standard MoneyControl date format (e.g. 19-May-26) to ISO YYYY-MM-DD
            try:
                date_str = datetime.datetime.strptime(date_raw.strip(), "%d-%b-%y").strftime("%Y-%m-%d")
            except ValueError:
                date_str = date_raw

            btn_el = box.find("button", class_="btndeal")
            action_str = btn_el.get_text(strip=True) if btn_el else ""

            name_el = box.find(class_="brstk_name")
            name_str = name_el.find("h3").get_text(strip=True) if (name_el and name_el.find("h3")) else (name_el.get_text(strip=True) if name_el else "")

            des_el = box.find(class_="desinper")
            designation = des_el.get_text(strip=True) if des_el else ""

            table = box.find("table")
            qty, price = None, None
            if table:
                tds = table.find_all("td")
                for td in tds:
                    text_val = td.get_text(" ", strip=True)
                    strong = td.find("strong")
                    val = strong.get_text(strip=True) if strong else ""
                    if text_val.lower().startswith("qty"):
                        qty = clean_int(val)
                    elif text_val.lower().startswith("price"):
                        price = clean_float(val)

            if date_str and name_str:
                val_inr = (qty * price) if (qty and price) else 0.0
                # date_iso via the same parser data_integrity_repair.py's one-time backfill
                # used -- this is the dominant writer of insider_trades (moneycontrol_fetcher
                # is the primary source, not insider_transactions_fetcher.py) and never
                # populated date_iso itself, so every row it wrote after that backfill was
                # invisible to insider_features.py's `WHERE date_iso >= ?` filter (NULL is
                # excluded by both `>=` and `<=`). `date_str` is already ISO when the strptime
                # above succeeds, but parse_loose_date is re-run on it (not just re-used)
                # so the fallback-to-raw-MC-format branch above still gets a real ISO date.
                parsed = parse_loose_date(date_str)
                rows.append({
                    "symbol": symbol,
                    "acquirerName": name_str,
                    "category": designation or "Unknown",
                    "typeOfTransaction": action_str or "Trade",
                    "quantity": qty or 0,
                    "valueInr": val_inr,
                    "date": date_str,
                    "dateIso": parsed.isoformat() if parsed else None,
                })

        if rows:
            with self.engine.begin() as conn:
                for r in rows:
                    # Write to database (Postgres has ID sequence, SQLite has autoinc)
                    conn.execute(text("""
                        INSERT INTO insider_trades (symbol, "acquirerName", category, "typeOfTransaction", quantity, "valueInr", date, date_iso)
                        VALUES (:symbol, :acquirerName, :category, :typeOfTransaction, :quantity, :valueInr, :date, :dateIso)
                    """), r)
            print(f"[MC Fetcher] Ingested {len(rows)} insider trades for {symbol}")

    def _parse_vitals(self, symbol: str, html: str):
        soup = BeautifulSoup(html, "html.parser")
        cards = soup.find_all(class_="card")
        vitals_rows = []
        scores_rows = []

        for card in cards:
            heading_el = card.find(class_="heading2")
            heading = heading_el.get_text(strip=True) if heading_el else ""
            if not heading:
                continue

            score_el = card.find(class_="score")
            score = score_el.get_text(strip=True) if score_el else ""

            desc_el = card.find(class_="description")
            desc = desc_el.get_text(strip=True) if desc_el else ""

            vitals_rows.append({
                "symbol": symbol,
                "metric_name": heading,
                "score": score,
                "description": desc
            })

            # Map to proprietary_scores_history
            score_type = heading.lower().replace("-", "_").replace(" ", "_")
            score_value = clean_float(score)
            scores_rows.append({
                "symbol": symbol,
                "date": self.date_today,
                "source": "moneycontrol",
                "score_type": score_type,
                "score_value": score_value,
                "score_label": score
            })

        if vitals_rows:
            with self.engine.begin() as conn:
                for vr in vitals_rows:
                    conn.execute(text("""
                        INSERT INTO mc_stock_vitals (symbol, metric_name, score, description, fetched_at)
                        VALUES (:symbol, :metric_name, :score, :description, CURRENT_TIMESTAMP)
                        ON CONFLICT(symbol, metric_name) DO UPDATE SET
                            score       = excluded.score,
                            description = excluded.description,
                            fetched_at  = CURRENT_TIMESTAMP
                    """), vr)
                for sr in scores_rows:
                    conn.execute(text("""
                        INSERT INTO proprietary_scores_history (symbol, date, source, score_type, score_value, score_label)
                        VALUES (:symbol, :date, :source, :score_type, :score_value, :score_label)
                        ON CONFLICT(symbol, date, source, score_type) DO UPDATE SET
                            score_value = excluded.score_value,
                            score_label = excluded.score_label
                    """), sr)
            print(f"[MC Fetcher] Ingested {len(vitals_rows)} vitals scores for {symbol}")

    def _parse_scans(self, symbol: str, html: str):
        soup = BeautifulSoup(html, "html.parser")
        boxes = soup.find_all(class_="scanResGridBox")
        rows = []
        for b in boxes:
            head_el = b.find(class_="boxHead")
            head = head_el.get_text(strip=True) if head_el else ""
            if not head or head == "SCANS":
                continue

            qtr_el = b.find(class_="qtrYr")
            desc = qtr_el.get_text(strip=True) if qtr_el else ""
            if "subscribe to reveal" in desc.lower():
                desc = "Premium Scanner (Details locked)"

            rows.append({
                "symbol": symbol,
                "scan_name": head,
                "description": desc
            })

        if rows:
            with self.engine.begin() as conn:
                for r in rows:
                    conn.execute(text("""
                        INSERT INTO mc_stock_scans (symbol, scan_name, description, fetched_at)
                        VALUES (:symbol, :scan_name, :description, CURRENT_TIMESTAMP)
                        ON CONFLICT(symbol, scan_name) DO UPDATE SET
                            description = excluded.description,
                            fetched_at  = CURRENT_TIMESTAMP
                    """), r)
            print(f"[MC Fetcher] Ingested {len(rows)} scans for {symbol}")

    def _parse_analyst_rating(self, symbol: str, data: dict):
        final_rating = data.get("finalRating")
        analyst_count = clean_int(data.get("analystCount"))
        ratings = data.get("ratings", [])
        ratings_map = {r.get("name", "").lower(): clean_int(r.get("value")) for r in ratings if r.get("name")}

        row = {
            "symbol": symbol,
            "final_rating": final_rating,
            "analyst_count": analyst_count,
            "buy_count": ratings_map.get("buy", 0),
            "outperform_count": ratings_map.get("outperform", 0),
            "hold_count": ratings_map.get("hold", 0),
            "underperform_count": ratings_map.get("underperform", 0),
            "sell_count": ratings_map.get("sell", 0),
            "fetched_at": self.date_today
        }

        with self.engine.begin() as conn:
            conn.execute(text("""
                INSERT INTO mc_analyst_ratings (symbol, final_rating, analyst_count, buy_count, outperform_count, hold_count, underperform_count, sell_count, fetched_at)
                VALUES (:symbol, :final_rating, :analyst_count, :buy_count, :outperform_count, :hold_count, :underperform_count, :sell_count, :fetched_at)
                ON CONFLICT(symbol, fetched_at) DO UPDATE SET
                    final_rating       = excluded.final_rating,
                    analyst_count      = excluded.analyst_count,
                    buy_count          = excluded.buy_count,
                    outperform_count   = excluded.outperform_count,
                    hold_count         = excluded.hold_count,
                    underperform_count = excluded.underperform_count,
                    sell_count         = excluded.sell_count
            """), row)

    def _parse_price_forecast(self, symbol: str, data: dict):
        row = {
            "symbol": symbol,
            "high": clean_float(data.get("high")),
            "mean": clean_float(data.get("mean")),
            "low": clean_float(data.get("low")),
            "fetched_at": self.date_today
        }
        with self.engine.begin() as conn:
            conn.execute(text("""
                INSERT INTO mc_price_forecast (symbol, high, mean, low, fetched_at)
                VALUES (:symbol, :high, :mean, :low, :fetched_at)
                ON CONFLICT(symbol, fetched_at) DO UPDATE SET
                    high = excluded.high,
                    mean = excluded.mean,
                    low  = excluded.low
            """), row)

    def _parse_earnings_forecast(self, symbol: str, data: dict):
        rows = []
        for metric_type in ["eps", "netProfit", "revenue"]:
            m_list = data.get(metric_type, [])
            for item in m_list:
                rows.append({
                    "symbol": symbol,
                    "date": item.get("date"),
                    "metric_type": metric_type,
                    "high": clean_float(item.get("high")),
                    "low": clean_float(item.get("low")),
                    "avg": clean_float(item.get("avg")),
                    "actual": clean_float(item.get("actual"))
                })

        if rows:
            with self.engine.begin() as conn:
                for r in rows:
                    conn.execute(text("""
                        INSERT INTO mc_earnings_forecast (symbol, date, metric_type, high, low, avg, actual)
                        VALUES (:symbol, :date, :metric_type, :high, :low, :avg, :actual)
                        ON CONFLICT(symbol, date, metric_type) DO UPDATE SET
                            high   = excluded.high,
                            low    = excluded.low,
                            avg    = excluded.avg,
                            actual = excluded.actual
                    """), r)

    def _parse_hits_misses(self, symbol: str, data: dict):
        # KNOWN OPEN GAP (2026-08-07 dead-column sweep, NOT fixable by correcting this
        # code): live-verified against MC's real `estimates/hits-misses` endpoint (curl
        # against scId=RI/RELIANCE) that `item["estimates"]` and `item["surprise"]` are
        # both the literal empty string "" for every quarter, for every stock checked --
        # the keys exist and are read correctly, MoneyControl's own API has simply stopped
        # supplying the underlying numbers upstream. `actual` and `type` (MC's own
        # positive/negative/inline beat-miss classification) are still populated correctly
        # and are NOT affected. clean_float("") correctly returns None here -- do not
        # "fix" this by changing the key names, there's nothing wrong with them. mc_estimates_
        # hits_misses.estimates/.surprise will stay 100% NULL until MoneyControl restores
        # this field or a replacement consensus-estimate source is sourced and approved
        # (see CLAUDE.md's dead-column-sweep session note / the dead_data_sweep_2026_08_07
        # memory file -- do not silently build a guessed replacement, ask first per the
        # standing feedback_failing_urls convention).
        l_list = data.get("list", [])
        rows = []
        for item in l_list:
            rows.append({
                "symbol": symbol,
                "quarter": item.get("quarter"),
                "actual": clean_float(item.get("actual")),
                "estimates": clean_float(item.get("estimates")),
                "surprise": clean_float(item.get("surprise")),
                "type": item.get("type")
            })

        if rows:
            with self.engine.begin() as conn:
                for r in rows:
                    conn.execute(text("""
                        INSERT INTO mc_estimates_hits_misses (symbol, quarter, actual, estimates, surprise, type, fetched_at)
                        VALUES (:symbol, :quarter, :actual, :estimates, :surprise, :type, CURRENT_TIMESTAMP)
                        ON CONFLICT(symbol, quarter) DO UPDATE SET
                            actual     = excluded.actual,
                            estimates  = excluded.estimates,
                            surprise   = excluded.surprise,
                            type       = excluded.type,
                            fetched_at = CURRENT_TIMESTAMP
                    """), r)

    def _parse_general_technicals(self, symbol: str, data: dict):
        rows = []
        # sentiments
        summary = data.get("summary", [])
        if isinstance(summary, list):
            for item in summary:
                sent = item.get("sentiments")
                if sent:
                    rows.append((symbol, "technicals", "summary", f"{sent}_bearish", clean_float(item.get("bearishCount")), None, self.date_today))
                    rows.append((symbol, "technicals", "summary", f"{sent}_bullish", clean_float(item.get("bullishCount")), None, self.date_today))
                    rows.append((symbol, "technicals", "summary", f"{sent}_neutral", clean_float(item.get("neutralCount")), None, self.date_today))
        
        # overall indication
        overall = data.get("overall", {})
        if isinstance(overall, dict):
            for k, v in overall.items():
                rows.append((symbol, "technicals", "overall", k, clean_float(v) if k != "indication" else None, str(v), self.date_today))

        if rows:
            self._write_general_metrics(rows)

    def _parse_general_essentials(self, symbol: str, data: dict):
        e_data = data.get("essentialsData", {})
        rows = []
        for group_name in ["financials", "industry", "valuation", "shareholding"]:
            items = e_data.get(group_name, [])
            for item in items:
                q = item.get("question")
                a = item.get("answer")
                if q:
                    rows.append((symbol, "mc-essentials", group_name, q, None, str(a), self.date_today))
        if rows:
            self._write_general_metrics(rows)

    def _parse_general_insights(self, symbol: str, data: dict):
        c_data = data.get("classification", {})
        rows = []
        for k, v in c_data.items():
            num_val = clean_float(v)
            str_val = str(v) if num_val is None else None
            rows.append((symbol, "mc-insights", "classification", k, num_val, str_val, self.date_today))
            
            # Map score metrics to proprietary_scores_history
            if k.lower() in ("score", "stock_score"):
                with self.engine.begin() as conn:
                    conn.execute(text("""
                        INSERT INTO proprietary_scores_history (symbol, date, source, score_type, score_value, score_label)
                        VALUES (:symbol, :date, :source, :score_type, :score_value, :score_label)
                        ON CONFLICT(symbol, date, source, score_type) DO UPDATE SET
                            score_value = excluded.score_value,
                            score_label = excluded.score_label
                    """), {
                        "symbol": symbol,
                        "date": self.date_today,
                        "source": "moneycontrol",
                        "score_type": "insights_score",
                        "score_value": num_val,
                        "score_label": str(v)
                    })

        if rows:
            self._write_general_metrics(rows)

    def _write_general_metrics(self, rows):
        with self.engine.begin() as conn:
            for r in rows:
                conn.execute(text("""
                    INSERT INTO mc_general_metrics (symbol, source_api, metric_group, metric_name, metric_value_num, metric_value_text, fetched_at)
                    VALUES (:symbol, :source, :group, :name, :val_num, :val_text, :fetched_at)
                    ON CONFLICT(symbol, source_api, metric_group, metric_name, fetched_at) DO UPDATE SET
                        metric_value_num  = excluded.metric_value_num,
                        metric_value_text = excluded.metric_value_text
                """), {
                    "symbol": r[0],
                    "source": r[1],
                    "group": r[2],
                    "name": r[3],
                    "val_num": r[4],
                    "val_text": r[5],
                    "fetched_at": r[6]
                })

    # ── Seasonality (mc_seasonality_best_stocks) ──────────────────────────
    # Table schema existed since this file's original batch of table creates,
    # but no fetch/write logic was ever built for it (found 2026-08-07 during
    # a dead-column/dead-table sweep -- confirmed via a live COUNT(*), the
    # table had 0 rows while all 7 sibling tables from the same batch had
    # thousands to a million). getMcSeasonality (moneycontrol.router.ts) and
    # SeasonalityCalendar.tsx (mounted on the Smart Money page) were reading
    # an always-empty table with no error surfaced anywhere.
    #
    # Real endpoint confirmed live: api.moneycontrol.com/mcapi/v1/market/
    # seasonality-analysis/get-best-month-stocks?ex=N&id=7&month=MM&year=YYYY
    # &tab=hps&trend=bullish|bearish&limit=N -- "hps" (High Probability
    # Stocks) + trend is the one variant that returns a self-consistent
    # "these stocks have been positive/negative in this month in every
    # tracked year" set (confirmed live: total_yr == tot_yr and
    # perchg_years == "100.00" throughout a bullish-filtered sample --
    # both fields are only equal because the filter already selects for
    # 100% consistency). "bus"/"bes" tab codes exist too but their exact
    # MC-internal meaning is undocumented and getMcSeasonality's own SQL
    # doesn't filter on tab_type at all, so there's no reason to guess at
    # them -- hps+trend is the one unambiguous, literally-named variant.
    SEASONALITY_URL = (
        "https://api.moneycontrol.com/mcapi/v1/market/seasonality-analysis/"
        "get-best-month-stocks?ex=N&id=7&month={month:02d}&year={year}"
        "&tab=hps&trend={trend}&limit=50"
    )

    def fetch_seasonality(self, month: int, trend: str) -> list[dict]:
        year = datetime.datetime.now().year
        url = self.SEASONALITY_URL.format(month=month, year=year, trend=trend)
        resp = self._fetch_url(url)
        if resp is None:
            return []
        try:
            payload = resp.json()
        except Exception:
            return []
        if payload.get("success") != 1:
            return []
        rows = []
        for item in payload.get("data") or []:
            sc_id = item.get("sc_id")
            if not sc_id:
                continue
            rows.append({
                "tab_type": trend,  # human-readable ('bullish'/'bearish'), not MC's opaque 'hps' code
                "sc_id": sc_id,
                "sc_fullname": item.get("sc_fullname"),
                "year": year,
                "month": month,
                # DB columns are abbreviated (avg_pct/max_pct/min_pct); the API's real
                # field names are avg_perchg/max_perchg/min_perchg -- this mapping is
                # the piece that was never written.
                "avg_pct": clean_float(item.get("avg_perchg")),
                "max_pct": clean_float(item.get("max_perchg")),
                "min_pct": clean_float(item.get("min_perchg")),
                "total_yr": clean_float(item.get("total_yr")),
                "tot_yr": clean_float(item.get("tot_yr")),
            })
        return rows

    def _write_seasonality(self, rows: list[dict]) -> None:
        if not rows:
            return
        with self.engine.begin() as conn:
            for r in rows:
                conn.execute(text("""
                    INSERT INTO mc_seasonality_best_stocks
                        (tab_type, sc_id, sc_fullname, year, month, avg_pct, max_pct, min_pct, total_yr, tot_yr, fetched_at)
                    VALUES (:tab_type, :sc_id, :sc_fullname, :year, :month, :avg_pct, :max_pct, :min_pct, :total_yr, :tot_yr, CURRENT_TIMESTAMP)
                    ON CONFLICT(tab_type, sc_id, year, month) DO UPDATE SET
                        sc_fullname = excluded.sc_fullname,
                        avg_pct     = excluded.avg_pct,
                        max_pct     = excluded.max_pct,
                        min_pct     = excluded.min_pct,
                        total_yr    = excluded.total_yr,
                        tot_yr      = excluded.tot_yr,
                        fetched_at  = CURRENT_TIMESTAMP
                """), r)

    def run_seasonality(self) -> int:
        """Refreshes all 12 months x {bullish, bearish} -- 24 requests total.
        Seasonality patterns move slowly (they're historical-year aggregates),
        so this is intended to run weekly, not daily."""
        total = 0
        for month in range(1, 13):
            for trend in ("bullish", "bearish"):
                rows = self.fetch_seasonality(month, trend)
                self._write_seasonality(rows)
                total += len(rows)
                print(f"[MC Fetcher] Seasonality month={month:02d} trend={trend}: {len(rows)} rows")
        print(f"[MC Fetcher] Seasonality refresh complete: {total} rows upserted.")
        return total

    def run(self):
        targets = self._resolve_target_batch()
        if not targets:
            print("[MC Fetcher] No active target symbols to process.")
            return

        print(f"[MC Fetcher] Starting crawl of {len(targets)} stocks in parallel (6 workers) at {datetime.datetime.now()}")
        from concurrent.futures import ThreadPoolExecutor, as_completed
        success_count = 0

        def _fetch_worker(stock):
            self.fetch_stock_data(stock)
            return stock.get("symbol")

        with ThreadPoolExecutor(max_workers=6) as pool:
            futures = [pool.submit(_fetch_worker, stock) for stock in targets]
            for fut in as_completed(futures):
                try:
                    sym = fut.result()
                    success_count += 1
                except Exception as e:
                    print(f"[MC Fetcher] Execution error: {e}", file=sys.stderr)

        print(f"[MC Fetcher] Finished crawling. Successfully processed {success_count}/{len(targets)} stocks.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MoneyControl Data Fetcher Pipeline")
    parser.add_argument("--symbols", nargs="*", help="List of specific stock symbols to fetch")
    parser.add_argument("--batch-size", type=int, default=150, help="Max stocks to crawl in this batch")
    parser.add_argument("--seasonality", action="store_true", help="Refresh mc_seasonality_best_stocks only (market-wide, not per-stock)")
    args = parser.parse_args()

    fetcher = MoneyControlFetcher(target_symbols=args.symbols, batch_size=args.batch_size)
    if args.seasonality:
        fetcher.run_seasonality()
    else:
        fetcher.run()

def to_polars_df(data):
    """Converts pandas DataFrame or list of dicts to Polars DataFrame for fast vector operations."""
    if hasattr(data, 'empty') and data.empty:
        return pl.DataFrame()
    return pl.from_pandas(data) if hasattr(data, 'to_numpy') else pl.DataFrame(data)
