"""
The physical mapping: (table, column) -> property.

A flat list of triples, with an optional note where the column name and the property name
disagree or where the meaning needs qualifying. Sparse on purpose — only columns carrying
semantics a consumer needs are bound; `introspect.py` reports the remainder as explicitly
unbound rather than pretending every column has a modelled meaning.

Every name is copied verbatim from live `information_schema` (verified 2026-09-21).
`tests/test_ontology_definitions.py` re-runs that check against the live database, so a
column rename fails the suite instead of silently orphaning a binding.
"""
from typing import Tuple

from ..model import ColumnBinding

B = ColumnBinding

#: Rows are (table, column, property) or (table, column, property, note).
ROWS: list = [

    # ── price & volume: the only self-owned truth ─────────────────────────────
    ("stock_ohlcv", "symbol", "symbol"),
    ("stock_ohlcv", "date", "date"),
    ("stock_ohlcv", "open", "open"),
    ("stock_ohlcv", "high", "high"),
    ("stock_ohlcv", "low", "low"),
    ("stock_ohlcv", "close", "close"),
    ("stock_ohlcv", "volume", "volume"),
    ("stock_ohlcv", "is_suspect", "is_suspect"),
    ("stock_ohlcv", "adjustment_basis", "adjustment_basis"),
    ("stock_ohlcv", "suspect_reason", "suspect_reason"),

    ("intraday_ohlcv", "symbol", "symbol"),
    ("intraday_ohlcv", "datetime", "datetime"),
    ("intraday_ohlcv", "interval", "series",
     "Bar interval, not an NSE series; vocabulary `trading_interval`."),
    ("intraday_ohlcv", "open", "open"),
    ("intraday_ohlcv", "high", "high"),
    ("intraday_ohlcv", "low", "low"),
    ("intraday_ohlcv", "close", "close"),
    ("intraday_ohlcv", "volume", "volume"),
    ("intraday_ohlcv", "vwap", "vwap"),

    # ── delivery ─────────────────────────────────────────────────────────────
    ("stock_delivery_data", "symbol", "symbol"),
    ("stock_delivery_data", "date", "date"),
    ("stock_delivery_data", "delivery_pct", "delivery_pct"),
    ("stock_delivery_data", "delivery_qty", "delivery_qty"),
    ("stock_delivery_data", "traded_qty", "traded_qty"),
    ("stock_delivery_data", "updated_at", "fetched_at"),
    ("stock_delivery_volume", "symbol", "symbol"),
    ("stock_delivery_volume", "date", "date"),
    ("stock_delivery_volume", "series", "series"),
    ("stock_delivery_volume", "qty_traded", "traded_qty"),
    ("stock_delivery_volume", "deliverable_qty", "deliverable_qty"),
    ("stock_delivery_volume", "delivery_pct", "delivery_pct"),
    ("stock_delivery_volume", "fetched_at", "fetched_at"),

    # ── identity: one ticker, many vendor-private ids ────────────────────────
    ("stock_master", "symbol", "symbol"),
    ("stock_master", "isin", "isin"),
    ("stock_master", "company_name", "company_name"),
    ("stock_master", "mcsymbol", "id", "MoneyControl-private symbol id."),
    ("stock_master", "tlid", "id", "Trendlyne-private instrument id."),
    ("stock_master", "companyid", "id", "MoneyControl company id."),
    ("stock_master", "tickertape_sid", "id", "Tickertape-private security id."),
    ("stock_master", "scripcode", "id", "BSE scrip code."),
    ("stock_master", "fincode", "id", "Finology-private code."),
    ("stock_master", "updated_at", "last_updated"),

    ("company_profiles", "symbol", "symbol"),
    ("company_profiles", "company_name", "company_name"),
    ("company_profiles", "description", "description"),
    ("company_profiles", "high_growth_scope", "high_growth_scope"),
    ("company_profiles", "last_updated", "last_updated"),
    ("company_profiles", "growth_score", "fundamental_score"),

    # ── corporate actions ────────────────────────────────────────────────────
    ("corporate_actions", "symbol", "symbol"),
    ("corporate_actions", "ex_date", "ex_date"),
    ("corporate_actions", "action_type", "action_type"),
    ("corporate_actions", "amount", "value_inr", "Dividend amount per share where applicable."),
    ("corporate_actions", "source", "source"),
    ("corporate_actions", "ingested_at", "fetched_at"),

    # ── fundamentals, estimates, surprises ───────────────────────────────────
    ("fundamentals_history", "symbol", "symbol"),
    ("fundamentals_history", "as_of_date", "as_of_date"),
    ("fundamentals_history", "market_cap", "market_cap"),
    ("fundamentals_history", "return_on_equity", "return_on_equity"),
    ("fundamentals_history", "debt_to_equity", "debt_to_equity"),
    ("fundamentals_history", "operating_margins", "operating_margins"),
    ("fundamentals_history", "revenue_growth", "revenue_growth"),
    ("fundamentals_history", "earnings_growth", "earnings_growth"),
    ("fundamentals_history", "price_to_book", "price_to_book"),
    ("fundamentals_history", "piotroski_f_score", "piotroski_f_score"),
    ("fundamentals_history", "pledge_pct", "pledge_pct"),
    ("fundamentals_history", "captured_at", "captured_at"),

    ("analyst_estimates_history", "symbol", "symbol"),
    ("analyst_estimates_history", "as_of_date", "as_of_date"),
    ("analyst_estimates_history", "n_analysts", "n_analysts"),
    ("analyst_estimates_history", "target_mean", "target_mean"),
    ("analyst_estimates_history", "final_rating", "classification"),
    ("analyst_estimates_history", "buy_count", "bullish_screener_count",
     "Reuse note: analysts rating buy — NOT a screener count."),
    ("analyst_estimates_history", "sell_count", "bearish_screener_count",
     "Reuse note: analysts rating sell, NOT a screener count."),
    ("analyst_estimates_history", "captured_at", "captured_at"),

    ("eps_surprise_history", "scid", "scid"),
    ("eps_surprise_history", "symbol", "symbol"),
    ("eps_surprise_history", "quarter", "series", "Fiscal quarter label, not an NSE series."),
    ("eps_surprise_history", "eps_actual", "eps_actual"),
    ("eps_surprise_history", "eps_estimate", "eps_estimate"),
    ("eps_surprise_history", "eps_surprise", "eps_surprise"),
    ("eps_surprise_history", "np_surprise", "np_surprise"),
    ("eps_surprise_history", "fetched_at", "fetched_at"),

    # ── institutional & insider flow ─────────────────────────────────────────
    ("insider_trades", "symbol", "symbol"),
    ("insider_trades", "acquirerName", "company_name",
     "The acquirer's display name; vendor free text, not a foreign key."),
    ("insider_trades", "category", "category"),
    ("insider_trades", "typeOfTransaction", "trade_type"),
    ("insider_trades", "quantity", "quantity"),
    ("insider_trades", "valueInr", "value_inr"),
    ("insider_trades", "date_iso", "date"),
    ("insider_trades", "pct_transacted", "pct_transacted"),
    ("insider_trades", "source", "source"),

    ("block_deals", "symbol", "symbol"),
    ("block_deals", "date", "date"),
    ("block_deals", "session", "session"),
    ("block_deals", "qty", "quantity"),
    ("block_deals", "price", "close", "Deal price: a transacted price, not a session close."),
    ("block_deals", "value_cr", "value_cr"),
    ("block_deals", "client_name", "client_name"),
    ("block_deals", "trade_type", "trade_type"),
    ("block_deals", "category", "category"),
    ("block_deals", "source", "source"),
    ("block_deals", "fetched_at", "fetched_at"),

    ("stock_mf_holdings", "symbol", "symbol"),
    ("stock_mf_holdings", "date", "date"),
    ("stock_mf_holdings", "mf_holding_pct", "mf_holding_pct"),
    ("stock_mf_holdings", "num_funds", "num_funds"),
    ("stock_mf_holdings", "fetched_at", "fetched_at"),

    # ── news ─────────────────────────────────────────────────────────────────
    ("news_sentiment_items", "id", "id"),
    ("news_sentiment_items", "title", "title"),
    ("news_sentiment_items", "summary", "summary"),
    ("news_sentiment_items", "source", "source"),
    ("news_sentiment_items", "source_type", "category"),
    ("news_sentiment_items", "url", "url"),
    ("news_sentiment_items", "published_at", "published_at"),
    ("news_sentiment_items", "sentiment", "sentiment"),
    ("news_sentiment_items", "sentiment_score", "sentiment_score"),
    ("news_sentiment_items", "impact", "impact"),
    ("news_sentiment_items", "category", "category"),
    ("news_sentiment_items", "symbols_json", "symbols_json"),
    ("news_sentiment_items", "sector", "sector"),
    ("news_sentiment_items", "ai_scored", "ai_scored"),
    ("news_sentiment_items", "tone_label", "tone_label"),
    ("news_sentiment_items", "tone_score", "tone_score"),
    ("news_sentiment_items", "sentiment_conflict", "sentiment_conflict"),
    ("news_symbol_link", "news_id", "id", "FK to news_sentiment_items.id."),
    ("news_symbol_link", "symbol", "symbol"),
    ("news_symbol_link", "published_at", "published_at"),
    ("news_symbol_link", "sentiment_score", "sentiment_score"),

    # ── derivatives ──────────────────────────────────────────────────────────
    ("so_option_chain", "symbol", "symbol"),
    ("so_option_chain", "date", "date"),
    ("so_option_chain", "expiry", "expiry"),
    ("so_option_chain", "strike", "strike"),
    ("so_option_chain", "ce_price", "option_premium"),
    ("so_option_chain", "ce_volume", "option_volume"),
    ("so_option_chain", "ce_oi", "option_oi"),
    ("so_option_chain", "ce_oi_chg_pct", "option_oi_chg_pct"),
    ("so_option_chain", "ce_iv", "option_iv"),
    ("so_option_chain", "ce_buildup", "option_buildup"),
    ("so_option_chain", "pe_price", "option_premium"),
    ("so_option_chain", "pe_volume", "option_volume"),
    ("so_option_chain", "pe_oi", "option_oi"),
    ("so_option_chain", "pe_oi_chg_pct", "option_oi_chg_pct"),
    ("so_option_chain", "pe_iv", "option_iv"),
    ("so_option_chain", "pe_buildup", "option_buildup"),
    ("so_option_chain", "fetched_at", "fetched_at"),

    ("stock_futures_oi_history", "symbol", "symbol"),
    ("stock_futures_oi_history", "date", "date"),
    ("stock_futures_oi_history", "expiry", "expiry"),
    ("stock_futures_oi_history", "open_interest", "open_interest"),
    ("stock_futures_oi_history", "oi_change", "oi_change"),
    ("stock_futures_oi_history", "oi_pct_change", "oi_pct_change"),
    ("stock_futures_oi_history", "oi_buildup", "oi_buildup"),
    ("stock_futures_oi_history", "rollover_pct", "rollover_pct"),
    ("stock_futures_oi_history", "oi_pcr", "pcr_oi"),
    ("stock_futures_oi_history", "futures_price", "futures_price"),
    ("stock_futures_oi_history", "spot_price", "spot_price"),
    ("stock_futures_oi_history", "basis", "basis"),
    ("stock_futures_oi_history", "contracts", "contracts"),
    ("stock_futures_oi_history", "futures_volume", "volume"),
    ("stock_futures_oi_history", "lot_size", "lot_size"),
    ("stock_futures_oi_history", "source", "source"),
    ("stock_futures_oi_history", "fetched_at", "fetched_at"),

    ("fno_rollover", "symbol", "symbol"),
    ("fno_rollover", "date", "date"),
    ("fno_rollover", "near_expiry", "expiry"),
    ("fno_rollover", "next_expiry", "expiry", "The next expiry in the same row."),
    ("fno_rollover", "near_oi", "open_interest", "Open interest on the near expiry."),
    ("fno_rollover", "next_oi", "open_interest", "Open interest on the next expiry."),
    ("fno_rollover", "total_oi", "total_oi"),
    ("fno_rollover", "rollover_pct", "rollover_pct"),
    ("fno_rollover", "cost_of_carry_ann", "cost_of_carry_ann"),
    ("fno_rollover", "spot_price", "spot_price"),
    ("fno_rollover", "near_close", "close", "Closing price of the near futures leg."),
    ("fno_rollover", "fetched_at", "fetched_at"),

    ("index_max_pain", "index_name", "index_name"),
    ("index_max_pain", "date", "date"),
    ("index_max_pain", "expiry", "expiry"),
    ("index_max_pain", "max_pain", "max_pain"),
    ("index_max_pain", "pcr_oi", "pcr_oi"),
    ("index_max_pain", "total_ce_oi", "option_oi", "Aggregate call-leg open interest."),
    ("index_max_pain", "total_pe_oi", "option_oi", "Aggregate put-leg open interest."),
    ("index_max_pain", "source", "source"),
    ("index_max_pain", "fetched_at", "fetched_at"),

    ("nt_index_pcr_ts", "index_name", "index_name"),
    ("nt_index_pcr_ts", "ts", "datetime"),
    ("nt_index_pcr_ts", "expiry", "expiry"),
    ("nt_index_pcr_ts", "pcr", "pcr"),
    ("nt_index_pcr_ts", "volume_pcr", "pcr", "PCR measured on volume rather than OI."),
    ("nt_index_pcr_ts", "change_oi_pcr", "pcr", "PCR measured on OI change."),
    ("nt_index_pcr_ts", "index_close", "close"),
    ("nt_index_pcr_ts", "fetched_at", "fetched_at"),

    # ── intraday movers and event detectors ──────────────────────────────────
    ("mover_snapshots", "source", "source"),
    ("mover_snapshots", "trade_date", "date"),
    ("mover_snapshots", "symbol", "symbol"),
    ("mover_snapshots", "rank", "rank_position"),
    ("mover_snapshots", "pct_change", "change_pct"),
    ("mover_snapshots", "payload_json", "payload_json"),
    ("mover_snapshots", "captured_at", "captured_at"),

    ("stock_event_triggers", "date", "date"),
    ("stock_event_triggers", "symbol", "symbol"),
    ("stock_event_triggers", "news_count_5d", "news_count_5d"),
    ("stock_event_triggers", "news_sent_5d", "sentiment_score",
     "Five-session news sentiment aggregate."),
    ("stock_event_triggers", "triggers", "triggers"),
    ("stock_event_triggers", "computed_at", "computed_at"),

    # ── market context ───────────────────────────────────────────────────────
    ("market_regimes", "date", "date"),
    ("market_regimes", "regime", "regime"),
    ("market_regimes", "regime_prob", "regime_prob"),
    ("market_regimes", "features_json", "features_json"),
    ("market_regimes", "viterbi_path_json", "viterbi_path_json"),
    ("market_regimes", "computed_at", "computed_at"),

    ("market_breadth", "date", "date"),
    ("market_breadth", "pct_above_200dma", "pct_above_200dma"),
    ("market_breadth", "adv_decline_ratio", "adv_decline_ratio"),
    ("market_breadth", "computed_at", "computed_at"),

    ("intraday_regime_history", "computed_at", "computed_at"),
    ("intraday_regime_history", "date", "date"),
    ("intraday_regime_history", "regime", "intraday_regime"),
    ("intraday_regime_history", "composite", "composite"),
    ("intraday_regime_history", "pcr", "pcr"),
    ("intraday_regime_history", "breadth_score", "composite", "Breadth sub-score."),

    ("sector_rrg_history", "sector", "sector"),
    ("sector_rrg_history", "week_date", "week_date"),
    ("sector_rrg_history", "quadrant", "quadrant"),
    ("sector_rrg_history", "sector_return", "return_pct", "Weekly sector return."),
    ("sector_rrg_history", "stocks_count", "stocks_count"),
    ("sector_rrg_history", "source", "source"),
    ("sector_rrg_history", "fetched_at", "fetched_at"),

    # ── derived intelligence ─────────────────────────────────────────────────
    ("technical_signals", "symbol", "symbol"),
    ("technical_signals", "date", "date"),
    ("technical_signals", "signal_score", "signal_score"),
    ("technical_signals", "rsi", "rsi"),
    ("technical_signals", "sma50", "sma50"),
    ("technical_signals", "sma200", "sma200"),
    ("technical_signals", "macd", "macd"),
    ("technical_signals", "adx", "adx"),
    ("technical_signals", "bb_width", "bb_width"),
    ("technical_signals", "volume_ratio", "volume_ratio"),
    ("technical_signals", "above_sma200", "above_sma200"),
    ("technical_signals", "cmp", "cmp"),
    ("technical_signals", "change_pct", "change_pct"),
    ("technical_signals", "ai_insight", "ai_insight"),
    ("technical_signals", "stop_loss", "stop_loss"),
    ("technical_signals", "time_horizon", "timeframe", "Stored horizon, mixed case."),
    ("technical_signals", "computed_at", "computed_at"),
    ("technical_signals", "delivery_pct", "delivery_pct"),
    ("technical_signals", "fii_3d_net", "fii_3d_net"),
    ("technical_signals", "dii_3d_net", "dii_3d_net"),
    ("technical_signals", "win_probability", "win_probability"),
    ("technical_signals", "calibrated_win_probability", "calibrated_win_probability"),
    ("technical_signals", "iv_rank", "iv_rank"),
    ("technical_signals", "cs_score", "cs_score"),
    ("technical_signals", "oi_net_change_pct", "oi_pct_change"),
    ("technical_signals", "rollover_pct", "rollover_pct"),
    ("technical_signals", "cost_of_carry_ann", "cost_of_carry_ann"),
    ("technical_signals", "mf_holding_pct", "mf_holding_pct"),
    ("technical_signals", "block_deal_value_cr", "value_cr"),
    ("technical_signals", "roe_annual", "return_on_equity"),
    ("technical_signals", "ebitda_margin", "operating_margins"),
    ("technical_signals", "np_margin", "operating_margins", "Net margin, not operating margin."),
    ("technical_signals", "pledge_pct", "pledge_pct"),
    ("technical_signals", "analyst_count", "n_analysts"),
    ("technical_signals", "pcr_oi", "pcr_oi"),
    ("technical_signals", "asm_flag", "asm_flag"),
    ("technical_signals", "fcf_positive", "fcf_positive"),
    ("technical_signals", "signals_json", "signals_json"),
    ("technical_signals", "news_sentiment_score", "sentiment_score"),
    ("technical_signals", "nifty_regime", "regime", "Regime stamped at write time."),
    # NO `technical_signals.sector`: information_schema confirms the column does not exist.
    # An earlier draft of this file asserted it, and live coverage caught it — the first true
    # positive from `python -m ontology coverage`. Sector reaches the platform through
    # nse_stocks / unified_recommendations / confluence_signals instead (all bound below).

    ("feature_store", "symbol", "symbol"),
    ("feature_store", "date", "date"),
    ("feature_store", "timeframe", "timeframe"),
    ("feature_store", "sma50", "sma50"),
    ("feature_store", "sma200", "sma200"),
    ("feature_store", "above_sma200", "above_sma200"),
    ("feature_store", "macd", "macd"),
    ("feature_store", "adx", "adx"),
    ("feature_store", "bb_width", "bb_width"),
    ("feature_store", "vwap", "vwap"),
    ("feature_store", "rsi_14", "rsi", "Feature-store RSI column."),
    ("feature_store", "atr_14", "atr", "Feature-store ATR column."),
    ("feature_store", "volume_ratio_20d", "volume_ratio", "20-day base window."),

    ("unified_recommendations", "symbol", "symbol"),
    ("unified_recommendations", "computed_at", "computed_at"),
    ("unified_recommendations", "generated_at", "last_updated"),
    ("unified_recommendations", "regime", "regime"),
    ("unified_recommendations", "unified_score", "unified_score"),
    ("unified_recommendations", "conviction_level", "conviction_level"),
    ("unified_recommendations", "screener_stock_score", "screener_stock_score"),
    ("unified_recommendations", "ml_score", "ml_score"),
    ("unified_recommendations", "confluence_score", "confluence_score"),
    ("unified_recommendations", "technical_score", "technical_score"),
    ("unified_recommendations", "dl_score", "dl_score"),
    ("unified_recommendations", "cs_score", "cs_score"),
    ("unified_recommendations", "breakout_score", "breakout_score"),
    ("unified_recommendations", "smart_money_score", "smart_money_score"),
    ("unified_recommendations", "fundamental_score", "fundamental_score"),
    ("unified_recommendations", "bullish_screener_count", "bullish_screener_count"),
    ("unified_recommendations", "bearish_screener_count", "bearish_screener_count"),
    ("unified_recommendations", "screener_names_json", "screener_names_json"),
    ("unified_recommendations", "entry_zone_low", "entry_zone_low"),
    ("unified_recommendations", "entry_zone_high", "entry_zone_high"),
    ("unified_recommendations", "stop_loss", "stop_loss"),
    ("unified_recommendations", "target_1", "target_1"),
    ("unified_recommendations", "target_2", "target_2"),
    ("unified_recommendations", "target_3", "target_3"),
    ("unified_recommendations", "risk_reward", "risk_reward"),
    ("unified_recommendations", "timeframe", "timeframe"),
    ("unified_recommendations", "sector", "sector"),
    ("unified_recommendations", "trade_reasoning", "trade_reasoning"),
    ("unified_recommendations", "classification", "classification"),
    ("unified_recommendations", "position_size_pct", "position_size_pct"),
    ("unified_recommendations", "engine_coverage_count", "engine_coverage_count"),

    ("unified_recommendations_history", "symbol", "symbol"),
    ("unified_recommendations_history", "computed_at", "computed_at"),
    ("unified_recommendations_history", "generated_at", "last_updated"),
    ("unified_recommendations_history", "regime", "regime"),
    ("unified_recommendations_history", "unified_score", "unified_score"),
    ("unified_recommendations_history", "conviction_level", "conviction_level"),
    ("unified_recommendations_history", "classification", "classification"),
    ("unified_recommendations_history", "screener_stock_score", "screener_stock_score"),
    ("unified_recommendations_history", "ml_score", "ml_score"),
    ("unified_recommendations_history", "confluence_score", "confluence_score"),
    ("unified_recommendations_history", "technical_score", "technical_score"),
    ("unified_recommendations_history", "cs_score", "cs_score"),
    ("unified_recommendations_history", "breakout_score", "breakout_score"),
    ("unified_recommendations_history", "smart_money_score", "smart_money_score"),
    ("unified_recommendations_history", "fundamental_score", "fundamental_score"),
    ("unified_recommendations_history", "engine_coverage_count", "engine_coverage_count"),
    ("unified_recommendations_history", "entry_zone_low", "entry_zone_low"),
    ("unified_recommendations_history", "stop_loss", "stop_loss"),
    ("unified_recommendations_history", "target_1", "target_1"),
    ("unified_recommendations_history", "position_size_pct", "position_size_pct"),
    ("unified_recommendations_history", "sector", "sector"),
    ("unified_recommendations_history", "dl_score", "dl_score"),
    ("unified_recommendations_history", "win_probability", "win_probability"),

    ("intraday_recommendations", "symbol", "symbol"),
    ("intraday_recommendations", "computed_at", "computed_at"),
    ("intraday_recommendations", "computed_ts", "computed_at", "Second timestamp column."),
    ("intraday_recommendations", "intraday_regime", "intraday_regime"),
    ("intraday_recommendations", "conviction_level", "conviction_level"),
    ("intraday_recommendations", "classification", "classification"),
    ("intraday_recommendations", "screener_score", "screener_stock_score"),
    ("intraday_recommendations", "breakout_score", "breakout_score"),
    ("intraday_recommendations", "bullish_count", "bullish_screener_count"),
    ("intraday_recommendations", "bearish_count", "bearish_screener_count"),
    ("intraday_recommendations", "cmp", "cmp"),
    ("intraday_recommendations", "entry_price", "entry_price"),
    ("intraday_recommendations", "stop_loss", "stop_loss"),
    ("intraday_recommendations", "target_1", "target_1"),
    ("intraday_recommendations", "risk_reward", "risk_reward"),
    ("intraday_recommendations", "position_size_pct", "position_size_pct"),
    ("intraday_recommendations", "reasoning", "trade_reasoning"),
    ("intraday_recommendations", "news_sentiment", "sentiment_score"),

    ("confluence_signals", "symbol", "symbol"),
    ("confluence_signals", "computed_at", "computed_at"),
    ("confluence_signals", "confluence_score", "confluence_score"),
    ("confluence_signals", "conviction_level", "conviction_level"),
    ("confluence_signals", "active_screener_count", "active_screener_count"),
    ("confluence_signals", "bullish_screener_count", "bullish_screener_count"),
    ("confluence_signals", "bearish_screener_count", "bearish_screener_count"),
    ("confluence_signals", "screener_ids_json", "screener_ids_json"),
    ("confluence_signals", "screener_names_json", "screener_names_json"),
    ("confluence_signals", "screener_weights_json", "screener_weights_json"),
    ("confluence_signals", "fundamental_score", "fundamental_score"),
    ("confluence_signals", "ml_breakout_probability", "ml_breakout_probability"),
    ("confluence_signals", "ml_trend_probability", "ml_trend_probability"),
    ("confluence_signals", "entry_zone_low", "entry_zone_low"),
    ("confluence_signals", "entry_zone_high", "entry_zone_high"),
    ("confluence_signals", "stop_loss", "stop_loss"),
    ("confluence_signals", "target_1", "target_1"),
    ("confluence_signals", "target_2", "target_2"),
    ("confluence_signals", "target_3", "target_3"),
    ("confluence_signals", "risk_reward", "risk_reward"),
    ("confluence_signals", "ai_conclusion", "ai_insight"),
    ("confluence_signals", "trade_reasoning", "trade_reasoning"),
    ("confluence_signals", "sector", "sector"),
    ("confluence_signals", "market_cap", "market_cap"),
    ("confluence_signals", "current_price", "current_price"),
    ("confluence_signals", "current_volume", "current_volume"),
    ("confluence_signals", "rsi", "rsi"),
    ("confluence_signals", "atr", "atr"),
    ("confluence_signals", "expires_at", "expiry", "Signal validity expiry."),

    ("engine_composite_scores", "symbol", "symbol"),
    ("engine_composite_scores", "date", "date"),
    ("engine_composite_scores", "composite", "composite"),
    ("engine_composite_scores", "n_engines", "engine_coverage_count"),
    ("engine_composite_scores", "computed_at", "computed_at"),

    ("stock_scores", "symbol", "symbol"),
    ("stock_scores", "timeframe", "timeframe"),
    ("stock_scores", "score", "composite", "Per-domain score in a multi-domain table."),
    ("stock_scores", "confidence", "win_probability",
     "A confidence value, not a calibrated probability."),
    ("stock_scores", "classification", "classification"),
    ("stock_scores", "last_updated", "last_updated"),

    # ── outcomes: the ground truth ───────────────────────────────────────────
    ("signal_outcomes", "symbol", "symbol"),
    ("signal_outcomes", "signal_date", "signal_date"),
    ("signal_outcomes", "horizon_days", "horizon_days"),
    ("signal_outcomes", "entry_price", "entry_price"),
    ("signal_outcomes", "check_date", "check_date"),
    ("signal_outcomes", "exit_price", "exit_price"),
    ("signal_outcomes", "return_pct", "return_pct"),
    ("signal_outcomes", "outcome", "outcome"),
    ("signal_outcomes", "signal_score", "signal_score"),
    ("signal_outcomes", "signals_json", "signals_json"),
    ("signal_outcomes", "computed_at", "computed_at"),
    ("signal_outcomes", "max_return_pct", "max_return_pct"),
    ("signal_outcomes", "label_definition", "label_definition"),
    ("signal_outcomes", "is_suspect", "is_suspect"),
    ("signal_outcomes", "signal_source", "signal_source"),

    ("unified_signal_outcomes", "unified_signal_id", "id",
     "FK to the served signal row; not stable across a rebuild."),
    ("unified_signal_outcomes", "symbol", "symbol"),
    ("unified_signal_outcomes", "signal_date", "signal_date"),
    ("unified_signal_outcomes", "signal_source", "signal_source"),
    ("unified_signal_outcomes", "horizon_days", "horizon_days"),
    ("unified_signal_outcomes", "entry_price", "entry_price"),
    ("unified_signal_outcomes", "check_date", "check_date"),
    ("unified_signal_outcomes", "exit_price", "exit_price"),
    ("unified_signal_outcomes", "return_pct", "return_pct"),
    ("unified_signal_outcomes", "outcome", "outcome"),
    ("unified_signal_outcomes", "exit_reason", "exit_reason"),
    ("unified_signal_outcomes", "signal_score", "signal_score"),
    ("unified_signal_outcomes", "computed_at", "computed_at"),

    ("signal_excursions", "symbol", "symbol"),
    ("signal_excursions", "signal_date", "signal_date"),
    ("signal_excursions", "horizon_days", "horizon_days"),
    ("signal_excursions", "entry_price", "entry_price"),
    ("signal_excursions", "mfe_pct", "mfe_pct"),
    ("signal_excursions", "mae_pct", "mae_pct"),
    ("signal_excursions", "computed_at", "computed_at"),
    ("signal_excursions", "atr_pct", "atr", "ATR expressed as a percentage at signal time."),
    ("signal_excursions", "tb_label", "label_definition", "Triple-barrier label."),

    # ── candidate generation ─────────────────────────────────────────────────
    ("screener_master", "scan_id", "id"),
    ("screener_master", "name", "name"),
    ("screener_master", "source", "source"),
    ("screener_master", "inferred_sentiment", "inferred_sentiment"),
    ("screener_master", "inferred_category", "inferred_category"),
    ("screener_master", "tier", "tier"),
    ("screener_master", "last_updated", "last_updated"),
    ("screener_master", "created_at", "computed_at"),

    ("live_screener_appearances", "id", "id"),
    ("live_screener_appearances", "run_id", "id", "FK to the screener run."),
    ("live_screener_appearances", "symbol", "symbol"),
    ("live_screener_appearances", "filter_key", "name", "The screener that surfaced the name."),
    ("live_screener_appearances", "price", "cmp", "Price at the moment of surfacing."),
    ("live_screener_appearances", "change_per", "change_pct"),
    ("live_screener_appearances", "volume", "volume"),

    ("live_screener_outcomes", "appearance_id", "id", "FK to live_screener_appearances.id."),
    ("live_screener_outcomes", "symbol", "symbol"),
    ("live_screener_outcomes", "entry_price", "entry_price"),
    ("live_screener_outcomes", "return_1d", "return_pct", "One-session forward return."),
    ("live_screener_outcomes", "return_3d", "return_pct", "Three-session forward return."),
    ("live_screener_outcomes", "return_5d", "return_pct", "Five-session forward return."),
    ("live_screener_outcomes", "appeared_at", "check_date", "When the name was surfaced."),

    # ── governance & provenance ──────────────────────────────────────────────
    ("job_heartbeat", "job_name", "job_name"),
    ("job_heartbeat", "last_status", "last_status"),
    ("job_heartbeat", "last_run_at", "computed_at"),
    ("job_heartbeat", "last_success_at", "computed_at", "Last SUCCESSFUL run, not last run."),
    ("job_heartbeat", "last_error", "last_error"),
    ("job_heartbeat", "run_count", "run_count"),
    ("job_heartbeat", "fail_count", "fail_count"),

    ("data_quality_results", "check_id", "check_id"),
    ("data_quality_results", "label", "name"),
    ("data_quality_results", "category", "category"),
    ("data_quality_results", "status", "status"),
    ("data_quality_results", "detail", "detail"),
    ("data_quality_results", "checked_at", "captured_at", "When the check ran."),

    ("model_registry", "id", "id"),
    ("model_registry", "model_name", "name"),
    ("model_registry", "model_type", "category"),
    ("model_registry", "trained_at", "computed_at"),
    ("model_registry", "horizon_days", "horizon_days"),
    ("model_registry", "top_features_json", "top_features_json"),

    ("feature_importance_log", "id", "id"),
    ("feature_importance_log", "model_name", "name"),
    ("feature_importance_log", "computed_at", "computed_at"),
    ("feature_importance_log", "feature_name", "name", "The feature's own name."),
    ("feature_importance_log", "importance", "importance"),
    ("feature_importance_log", "rank_position", "rank_position"),

    ("factor_edge_history", "run_at", "computed_at"),
    ("factor_edge_history", "table_name", "source", "The table whose factor was graded."),
    ("factor_edge_history", "score_col", "name", "The graded column."),
    ("factor_edge_history", "horizon_days", "horizon_days"),
    ("factor_edge_history", "rank_ic", "rank_ic"),
    ("factor_edge_history", "hit_auc", "hit_auc"),
    ("factor_edge_history", "eff_dates", "eff_dates"),
    ("factor_edge_history", "verdict", "verdict"),

    ("market_endpoint_registry", "uid", "id"),
    ("market_endpoint_registry", "endpoint_name", "name"),
    ("market_endpoint_registry", "provider", "source"),
    ("market_endpoint_registry", "data_domain", "data_domain"),
    ("market_endpoint_registry", "category", "category"),
    ("market_endpoint_registry", "scope", "scope"),
    ("market_endpoint_registry", "update_frequency", "update_frequency"),
    ("market_endpoint_registry", "use_case", "use_case"),
    ("market_endpoint_registry", "http_method", "method"),
    ("market_endpoint_registry", "target_url", "target_url"),
    ("market_endpoint_registry", "url_template", "url_template"),
    ("market_endpoint_registry", "auth_type", "auth_type"),
    ("market_endpoint_registry", "output_fields", "output_fields"),
    ("market_endpoint_registry", "validated_at", "captured_at"),

    ("url_endpoints", "id", "id"),
    ("url_endpoints", "template", "url_template"),
    ("url_endpoints", "host", "source"),
    ("url_endpoints", "method", "method"),
    ("url_endpoints", "provider", "source", "Provider name, distinct from host."),
    ("url_endpoints", "category", "category"),
    ("url_endpoints", "description", "description"),
    ("url_endpoints", "updated_at", "last_updated"),

    # ── identity hub, vendor crosswalk, and loose ends found by `ontology verify` ──
    #
    # Added 2026-09-23. The four properties below were declared but bound to nothing, which
    # made them unusable: a semantic layer that says "exchange exists" while naming no column
    # teaches a consumer nothing. Each binding names a column verified in
    # information_schema, and the two cards added alongside (`nse_stocks`, `mc_scid_map`) are
    # the tables that carry them.
    ("nse_stocks", "symbol", "symbol"),
    ("nse_stocks", "name", "company_name"),
    ("nse_stocks", "isin", "isin"),
    ("nse_stocks", "sector", "sector"),
    ("nse_stocks", "industry", "industry"),
    ("nse_stocks", "exchange", "exchange",
     "The canonical venue column — see the Exchange class caveat."),
    ("nse_stocks", "market_cap", "market_cap",
     "Unit undeclared in the schema; do not aggregate without confirming it."),
    ("nse_stocks", "lot_size", "lot_size"),
    ("nse_stocks", "is_asm", "asm_flag",
     "Stored as 0/1 bigint, not boolean."),
    ("nse_stocks", "last_updated", "last_updated"),

    ("mc_scid_map", "scid", "scid"),
    ("mc_scid_map", "symbol", "symbol"),
    ("mc_scid_map", "stock_name", "company_name"),

    ("stock_master", "industry", "industry"),
    ("technical_signals", "iv_hv_ratio", "iv_hv_ratio"),
    ("block_deals", "id", "id",
     "The card's primary key. A surrogate id, not stable across a re-fetch."),


    # ── semantic control plane / canonical identity / graph / decision evidence ──
    ("market_issuer", "issuer_id", "id"),
    ("market_issuer", "issuer_key", "issuer_key"),
    ("market_issuer", "legal_name", "legal_name"),
    ("market_issuer", "identity_basis", "identity_basis"),
    ("market_issuer", "confidence", "confidence"),
    ("market_issuer", "attributes", "attributes"),
    ("market_issuer", "valid_from", "valid_from"),
    ("market_issuer", "valid_to", "valid_to"),
    ("market_issuer", "available_at", "available_at"),
    ("market_issuer", "recorded_at", "recorded_at"),
    ("market_issuer", "source", "source"),
    ("market_issuer", "source_ref", "source_ref"),
    ("market_instrument", "instrument_id", "id"),
    ("market_instrument", "instrument_key", "instrument_key"),
    ("market_instrument", "issuer_id", "id"),
    ("market_instrument", "name", "name"),
    ("market_instrument", "instrument_type", "instrument_type"),
    ("market_instrument", "isin", "isin"),
    ("market_instrument", "identity_basis", "identity_basis"),
    ("market_instrument", "confidence", "confidence"),
    ("market_instrument", "attributes", "attributes"),
    ("market_instrument", "valid_from", "valid_from"),
    ("market_instrument", "valid_to", "valid_to"),
    ("market_instrument", "available_at", "available_at"),
    ("market_instrument", "recorded_at", "recorded_at"),
    ("market_instrument", "source", "source"),
    ("market_instrument", "source_ref", "source_ref"),
    ("market_listing", "listing_id", "id"),
    ("market_listing", "listing_key", "listing_key"),
    ("market_listing", "instrument_id", "id"),
    ("market_listing", "exchange", "exchange"),
    ("market_listing", "market_segment", "market_segment"),
    ("market_listing", "symbol", "symbol"),
    ("market_listing", "status", "listing_status"),
    ("market_listing", "listed_from", "date"),
    ("market_listing", "listed_to", "date"),
    ("market_listing", "attributes", "attributes"),
    ("market_listing", "valid_from", "valid_from"),
    ("market_listing", "valid_to", "valid_to"),
    ("market_listing", "available_at", "available_at"),
    ("market_listing", "recorded_at", "recorded_at"),
    ("market_listing", "source", "source"),
    ("market_listing", "source_ref", "source_ref"),
    ("market_identifier", "identifier_id", "id"),
    ("market_identifier", "mapping_key", "mapping_key"),
    ("market_identifier", "instrument_id", "id"),
    ("market_identifier", "provider", "provider"),
    ("market_identifier", "scheme", "scheme"),
    ("market_identifier", "identifier_value", "identifier_value"),
    ("market_identifier", "mapping_status", "mapping_status"),
    ("market_identifier", "confidence", "confidence"),
    ("market_identifier", "valid_from", "valid_from"),
    ("market_identifier", "valid_to", "valid_to"),
    ("market_identifier", "available_at", "available_at"),
    ("market_identifier", "recorded_at", "recorded_at"),
    ("market_identifier", "source", "source"),
    ("market_identifier", "source_ref", "source_ref"),
    ("market_identifier_gap", "provider", "provider"),
    ("market_identifier_gap", "scheme", "scheme"),
    ("market_identifier_gap", "identifier_value", "identifier_value"),
    ("market_identifier_gap", "instrument_id", "id"),
    ("market_identifier_gap", "reason", "reason"),
    ("market_identifier_gap", "candidate_instrument_ids", "candidate_instrument_ids"),
    ("market_identifier_gap", "first_seen", "first_seen"),
    ("market_identifier_gap", "last_seen", "last_seen"),
    ("market_identifier_gap", "attempts", "attempts"),

]


_SEMANTIC_ROWS = [

    ("market_graph_node", "node_id", "id"),
    ("market_graph_node", "node_key", "node_key"),
    ("market_graph_node", "node_type", "node_type"),
    ("market_graph_node", "label", "name"),
    ("market_graph_node", "canonical_symbol", "symbol"),
    ("market_graph_node", "attributes", "attributes"),
    ("market_graph_node", "valid_from", "valid_from"),
    ("market_graph_node", "valid_to", "valid_to"),
    ("market_graph_node", "available_at", "available_at"),
    ("market_graph_node", "recorded_at", "recorded_at"),
    ("market_graph_node", "source", "source"),
    ("market_graph_node", "source_ref", "source_ref"),
    ("market_graph_node", "revision", "revision"),
    ("market_graph_edge", "edge_id", "id"),
    ("market_graph_edge", "from_node_id", "id"),
    ("market_graph_edge", "to_node_id", "id"),
    ("market_graph_edge", "predicate", "predicate"),
    ("market_graph_edge", "object_value", "object_value"),
    ("market_graph_edge", "valid_from", "valid_from"),
    ("market_graph_edge", "valid_to", "valid_to"),
    ("market_graph_edge", "available_at", "available_at"),
    ("market_graph_edge", "recorded_at", "recorded_at"),
    ("market_graph_edge", "source", "source"),
    ("market_graph_edge", "source_ref", "source_ref"),
    ("market_graph_edge", "assertion_key", "assertion_key"),
    ("market_evidence", "evidence_key", "evidence_key"),
    ("market_evidence", "source_type", "source_type"),
    ("market_evidence", "source_ref", "source_ref"),
    ("market_evidence", "source_uri", "source_uri"),
    ("market_evidence", "content_hash", "content_hash"),
    ("market_evidence", "content", "content"),
    ("market_evidence", "observed_at", "observed_at"),
    ("market_evidence", "available_at", "available_at"),
    ("market_evidence", "recorded_at", "recorded_at"),
    ("market_evidence", "extraction_method", "extraction_method"),
    ("market_evidence", "extraction_version", "extraction_version"),
    ("market_evidence", "quality_status", "quality_status"),

    ("market_claim", "claim_key", "claim_key"),
    ("market_claim", "subject_node_id", "id"),
    ("market_claim", "predicate", "predicate"),
    ("market_claim", "object_value", "object_value"),
    ("market_claim", "horizon", "horizon"),
    ("market_claim", "stance", "stance"),
    ("market_claim", "claim_status", "claim_status"),
    ("market_claim", "method", "method"),
    ("market_claim", "available_at", "available_at"),
    ("market_claim", "recorded_at", "recorded_at"),
    ("market_claim", "superseded_by", "superseded_by"),
    ("market_claim_evidence", "claim_key", "claim_key"),
    ("market_claim_evidence", "evidence_key", "evidence_key"),
    ("market_claim_evidence", "relation", "relation"),
    ("market_claim_evidence", "contribution", "contribution"),
    ("market_claim_evidence", "note", "note"),
    ("market_decision_event", "decision_key", "decision_key"),
    ("market_decision_event", "symbol", "symbol"),
    ("market_decision_event", "computed_at", "computed_at"),
    ("market_decision_event", "generated_at", "generated_at"),
    ("market_decision_event", "knowledge_cutoff", "knowledge_cutoff"),
    ("market_decision_event", "knowledge_cutoff_kind", "knowledge_cutoff_kind"),
    ("market_decision_event", "source_table", "source_table"),
    ("market_decision_event", "source_key", "source_key"),
    ("market_decision_event", "ranker_policy_version", "ranker_policy_version"),
    ("market_decision_event", "feature_set_version", "feature_set_version"),
    ("market_decision_event", "model_versions", "model_versions"),
    ("market_decision_event", "score", "unified_score"),
    ("market_decision_event", "classification", "classification"),
    ("market_decision_event", "timeframe", "timeframe"),
    ("market_decision_event", "decision_status", "decision_status"),
    ("market_decision_event", "quality_snapshot", "quality_snapshot"),
    ("market_decision_event", "data_watermarks", "data_watermarks"),
    ("market_decision_event", "veto_reasons", "veto_reasons"),
    ("market_decision_event", "guardrails", "guardrails"),
    ("market_decision_event", "created_at", "created_at"),

    ("market_decision_evidence", "decision_key", "decision_key"),
    ("market_decision_evidence", "evidence_key", "evidence_key"),
    ("market_decision_evidence", "relation", "relation"),
    ("market_decision_evidence", "evidence_type", "evidence_type"),
    ("market_decision_evidence", "metric", "metric"),
    ("market_decision_evidence", "value_json", "value_json"),
    ("market_decision_evidence", "source_table", "source_table"),
    ("market_decision_evidence", "source_ref", "source_ref"),
    ("market_decision_evidence", "observed_at", "observed_at"),
    ("market_decision_evidence", "available_at", "available_at"),
    ("market_decision_evidence", "confidence_kind", "confidence_kind"),
    ("market_decision_evidence", "note", "note"),
    ("market_decision_outcome", "decision_key", "decision_key"),
    ("market_decision_outcome", "label_definition", "label_definition"),
    ("market_decision_outcome", "horizon_days", "horizon_days"),
    ("market_decision_outcome", "outcome_status", "outcome_status"),
    ("market_decision_outcome", "entry_price", "entry_price"),
    ("market_decision_outcome", "exit_price", "exit_price"),
    ("market_decision_outcome", "return_pct", "return_pct"),
    ("market_decision_outcome", "mfe_pct", "mfe_pct"),
    ("market_decision_outcome", "mae_pct", "mae_pct"),
    ("market_decision_outcome", "resolved_at", "resolved_at"),
    ("market_decision_outcome", "source_table", "source_table"),
    ("market_decision_outcome", "source_ref", "source_ref"),
    ("market_decision_outcome", "created_at", "created_at"),
    ("market_data_contract", "contract_key", "contract_key"),
    ("market_data_contract", "dataset", "dataset"),
    ("market_data_contract", "version", "contract_version"),
    ("market_data_contract", "grain", "grain"),
    ("market_data_contract", "cadence", "cadence"),
    ("market_data_contract", "unit", "unit"),
    ("market_data_contract", "time_semantics", "time_semantics"),
    ("market_data_contract", "source_kind", "source_kind"),
    ("market_data_contract", "training_use", "training_use"),
    ("market_data_contract", "ontology_version", "ontology_version"),
    ("market_data_contract", "contract", "contract"),
    ("market_data_contract", "active", "active"),
    ("market_data_contract", "created_at", "created_at"),
    ("market_data_contract", "updated_at", "updated_at"),

    ("semantic_feature_definition", "feature_key", "feature_key"),
    ("semantic_feature_definition", "property_name", "property_name"),
    ("semantic_feature_definition", "version", "version"),
    ("semantic_feature_definition", "description", "description"),
    ("semantic_feature_definition", "semantic_type", "semantic_type"),
    ("semantic_feature_definition", "datatype", "datatype"),
    ("semantic_feature_definition", "unit", "unit"),
    ("semantic_feature_definition", "timing", "timing"),
    ("semantic_feature_definition", "derivation", "derivation"),
    ("semantic_feature_definition", "leakage_risk", "leakage_risk"),
    ("semantic_feature_definition", "pit_notes", "pit_notes"),
    ("semantic_feature_definition", "physical_bindings", "physical_bindings"),
    ("semantic_feature_definition", "usable_as_feature", "usable_as_feature"),
    ("semantic_feature_definition", "is_label", "is_label"),
    ("semantic_feature_definition", "active", "active"),
    ("semantic_feature_definition", "created_at", "created_at"),
    ("semantic_feature_definition", "updated_at", "updated_at"),
    ("market_data_watermark", "dataset", "dataset"),
    ("market_data_watermark", "partition_key", "partition_key"),
    ("market_data_watermark", "as_of", "as_of"),
    ("market_data_watermark", "input_watermark", "input_watermark"),
    ("market_data_watermark", "output_watermark", "output_watermark"),
    ("market_data_watermark", "expected_rows", "expected_rows"),
    ("market_data_watermark", "accepted_rows", "accepted_rows"),
    ("market_data_watermark", "rejected_rows", "rejected_rows"),
    ("market_data_watermark", "completeness_status", "completeness_status"),
    ("market_data_watermark", "source_version", "source_version"),
    ("market_data_watermark", "run_ref", "run_ref"),
    ("market_data_watermark", "recorded_at", "recorded_at"),
]




def bindings() -> Tuple[ColumnBinding, ...]:
    """Expand authored physical bindings into immutable records."""
    rows = list(ROWS) + list(_SEMANTIC_ROWS)
    return tuple(B(row[0], row[1], row[2], row[3] if len(row) > 3 else "") for row in rows)

