-- Up Migration
--
-- technical_signals_backup_20260719 is a one-time, frozen backup snapshot table created
-- during the 2026-08-03 technical_analysis_signals -> unified_signals consolidation
-- (score_signal_table_consolidation_2026_08_03 memory) and never touched again. Grep-confirmed
-- zero references anywhere in src/server/*.ts, src/server/*.py, or any router/component -- not
-- a live writer, not a live reader, not referenced by any test. Found during the 2026-08-07
-- dead-column/dead-table sweep: pg_stats flagged ~50 of its 268 columns at 100% null (expected
-- for a July snapshot predating those columns' introduction, not a bug in itself) and the
-- table has had 0 activity since.
--
-- This is a point-in-time backup, not a live schema -- dropping it does not lose anything a
-- real database backup wouldn't already have, and its own reason for existing (a safety net
-- immediately after the 2026-08-03 consolidation) has been satisfied for weeks.
DROP TABLE IF EXISTS "technical_signals_backup_20260719";

-- Down Migration
--
-- Schema-only restore (columns/types verified 2026-08-07 via information_schema.columns
-- against the live table, then round-tripped through a real CREATE TABLE in a scratch schema
-- to confirm valid DDL before this migration was written) -- this recreates the EMPTY shell,
-- not the actual backed-up rows. If the real snapshot data is ever needed, restore it from an
-- actual database backup/pg_dump taken before this migration ran, not from this DDL alone.
CREATE TABLE IF NOT EXISTS "technical_signals_backup_20260719" (
  "symbol" TEXT,
  "date" TEXT,
  "signals_json" TEXT,
  "signal_score" BIGINT,
  "rsi" DOUBLE PRECISION,
  "sma50" DOUBLE PRECISION,
  "sma200" DOUBLE PRECISION,
  "macd" DOUBLE PRECISION,
  "macd_signal" DOUBLE PRECISION,
  "bb_width" DOUBLE PRECISION,
  "volume_ratio" DOUBLE PRECISION,
  "above_sma200" BIGINT,
  "cmp" DOUBLE PRECISION,
  "change_pct" DOUBLE PRECISION,
  "ai_insight" TEXT,
  "entry_zone" TEXT,
  "stop_loss" TEXT,
  "targets" TEXT,
  "setup_quality" TEXT,
  "time_horizon" TEXT,
  "computed_at" TIMESTAMP WITH TIME ZONE,
  "adx" DOUBLE PRECISION,
  "nifty_regime" TEXT,
  "delivery_pct" DOUBLE PRECISION,
  "fii_3d_net" DOUBLE PRECISION,
  "win_probability" DOUBLE PRECISION,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "news_sentiment_score" DOUBLE PRECISION,
  "pcr_oi" DOUBLE PRECISION,
  "pcr_vol" DOUBLE PRECISION,
  "fii_10d_net" DOUBLE PRECISION,
  "dii_3d_net" DOUBLE PRECISION,
  "sector_ret_5d" DOUBLE PRECISION,
  "sector_ret_21d" DOUBLE PRECISION,
  "calibrated_win_probability" DOUBLE PRECISION,
  "iv_rank" DOUBLE PRECISION,
  "iv_skew" DOUBLE PRECISION,
  "rs_rank_21d" DOUBLE PRECISION,
  "rs_rank_63d" DOUBLE PRECISION,
  "insider_buy_pct_90d" DOUBLE PRECISION,
  "opening_range_break" DOUBLE PRECISION,
  "vwap_deviation_pct" DOUBLE PRECISION,
  "first_hour_vol_share" DOUBLE PRECISION,
  "cs_score" DOUBLE PRECISION,
  "avwap_deviation_pct" DOUBLE PRECISION,
  "oi_net_change_pct" DOUBLE PRECISION,
  "eps_beat_last_q" BIGINT,
  "eps_beat_streak_4q" BIGINT,
  "eps_miss_streak_4q" BIGINT,
  "eps_surprise_last_yr" DOUBLE PRECISION,
  "eps_estimate_dispersion" DOUBLE PRECISION,
  "rollover_pct" DOUBLE PRECISION,
  "cost_of_carry_ann" DOUBLE PRECISION,
  "mf_holding_pct" DOUBLE PRECISION,
  "mf_fund_count" BIGINT,
  "mf_chg_vs_prev" DOUBLE PRECISION,
  "sector_global_corr_21d" DOUBLE PRECISION,
  "sector_benchmark" TEXT,
  "block_deal_net_qty" BIGINT,
  "block_deal_value_cr" DOUBLE PRECISION,
  "eps_ttm" DOUBLE PRECISION,
  "eps_growth_yoy" DOUBLE PRECISION,
  "eps_growth_qoq" DOUBLE PRECISION,
  "eps_acceleration" DOUBLE PRECISION,
  "pe_ttm" DOUBLE PRECISION,
  "dvm_durability" BIGINT,
  "dvm_valuation" BIGINT,
  "dvm_momentum" BIGINT,
  "pe_pct_rank_252d" DOUBLE PRECISION,
  "pe_vs_median_1yr" DOUBLE PRECISION,
  "pb_pct_rank_252d" DOUBLE PRECISION,
  "div_yield_ttm" DOUBLE PRECISION,
  "ma_bull_frac" DOUBLE PRECISION,
  "osc_bull_frac" DOUBLE PRECISION,
  "adx_tl" DOUBLE PRECISION,
  "atr_pct_tl" DOUBLE PRECISION,
  "mfi_tl" DOUBLE PRECISION,
  "pivot_dist_pct_tl" DOUBLE PRECISION,
  "delivery_avg_1m_tl" DOUBLE PRECISION,
  "beta_1y_tl" DOUBLE PRECISION,
  "ret_1m_tl" DOUBLE PRECISION,
  "ret_3m_tl" DOUBLE PRECISION,
  "ret_6m_tl" DOUBLE PRECISION,
  "ret_1y_tl" DOUBLE PRECISION,
  "analyst_upside_pct" DOUBLE PRECISION,
  "analyst_count" BIGINT,
  "analyst_buy_pct" DOUBLE PRECISION,
  "roe_annual" DOUBLE PRECISION,
  "roce_annual" DOUBLE PRECISION,
  "ebitda_margin" DOUBLE PRECISION,
  "np_margin" DOUBLE PRECISION,
  "promoter_pct" DOUBLE PRECISION,
  "fii_pct" DOUBLE PRECISION,
  "pledge_pct" DOUBLE PRECISION,
  "rev_growth_yoy_q" DOUBLE PRECISION,
  "np_growth_yoy_q" DOUBLE PRECISION,
  "days_since_dividend" BIGINT,
  "last_dividend_amt" DOUBLE PRECISION,
  "mc_52w_high_dist_pct" DOUBLE PRECISION,
  "mc_52w_low_dist_pct" DOUBLE PRECISION,
  "mc_days_from_52wh" BIGINT,
  "mc_cagr_3y" DOUBLE PRECISION,
  "mc_cagr_5y" DOUBLE PRECISION,
  "mc_ind_pe" DOUBLE PRECISION,
  "mc_pe_vs_ind" DOUBLE PRECISION,
  "mc_consensus_pe" DOUBLE PRECISION,
  "mc_ma50_dist_pct" DOUBLE PRECISION,
  "mc_ma200_dist_pct" DOUBLE PRECISION,
  "mc_del_pct_20d" DOUBLE PRECISION,
  "mc_vol_ratio" DOUBLE PRECISION,
  "mc_circuit_dist_pct" DOUBLE PRECISION,
  "mc_cp_bull_count" BIGINT,
  "mc_cp_bear_count" BIGINT,
  "mc_cp_net_score" BIGINT,
  "mc_cp_avg_target_pct" DOUBLE PRECISION,
  "tl_vs_nifty_1m" DOUBLE PRECISION,
  "tl_vs_nifty_3m" DOUBLE PRECISION,
  "tl_vs_nifty_6m" DOUBLE PRECISION,
  "tl_vs_ind_1m" DOUBLE PRECISION,
  "tl_vs_ind_3m" DOUBLE PRECISION,
  "tl_seasonal_month_5y" DOUBLE PRECISION,
  "tl_dist_3m_high_pct" DOUBLE PRECISION,
  "tl_dist_3m_low_pct" DOUBLE PRECISION,
  "mc_cagr_10y" DOUBLE PRECISION,
  "mc_consensus_pb" DOUBLE PRECISION,
  "mc_ma30_dist_pct" DOUBLE PRECISION,
  "mc_ma150_dist_pct" DOUBLE PRECISION,
  "mc_del_pct_3d" DOUBLE PRECISION,
  "mc_del_pct_5d" DOUBLE PRECISION,
  "mc_del_acceleration" DOUBLE PRECISION,
  "mc_fno_eligible" BIGINT,
  "mc_3d_return" DOUBLE PRECISION,
  "mc_ytd_return" DOUBLE PRECISION,
  "mc_price_cash" DOUBLE PRECISION,
  "mc_consensus_eps" DOUBLE PRECISION,
  "mc_eps_vs_cons" DOUBLE PRECISION,
  "mc_pe_fwd_discount" DOUBLE PRECISION,
  "nt_max_pain_dist_pct" DOUBLE PRECISION,
  "nt_oi_direction" DOUBLE PRECISION,
  "nt_pcr" DOUBLE PRECISION,
  "nt_option_volume_log" DOUBLE PRECISION,
  "days_to_next_results" BIGINT,
  "earnings_category_yoy" BIGINT,
  "earnings_category_qoq" BIGINT,
  "earnings_np_growth_yoy" DOUBLE PRECISION,
  "earnings_np_growth_qoq" DOUBLE PRECISION,
  "earnings_shocker_flag" BIGINT,
  "earnings_shocker_gain" DOUBLE PRECISION,
  "mc_broker_buy_7d" BIGINT,
  "mc_broker_sell_7d" BIGINT,
  "mc_broker_upside" DOUBLE PRECISION,
  "hv_10d" DOUBLE PRECISION,
  "hv_20d" DOUBLE PRECISION,
  "hv_30d" DOUBLE PRECISION,
  "hv_60d" DOUBLE PRECISION,
  "iv_hv_ratio" DOUBLE PRECISION,
  "eps_revision_3m_pct" DOUBLE PRECISION,
  "target_revision_3m_pct" DOUBLE PRECISION,
  "analyst_count_chg" BIGINT,
  "rs_vs_sector_21d" DOUBLE PRECISION,
  "rs_vs_sector_63d" DOUBLE PRECISION,
  "asm_flag" BIGINT,
  "gsm_stage" BIGINT,
  "crude_corr_90d" DOUBLE PRECISION,
  "gold_corr_90d" DOUBLE PRECISION,
  "dxy_corr_90d" DOUBLE PRECISION,
  "sp500_corr_90d" DOUBLE PRECISION,
  "is_nifty50" BIGINT,
  "is_nifty100" BIGINT,
  "is_nifty200" BIGINT,
  "is_midcap150" BIGINT,
  "is_smallcap250" BIGINT,
  "nifty_tier" BIGINT,
  "pledge_chg_90d" DOUBLE PRECISION,
  "iep_gap_pct" DOUBLE PRECISION,
  "preopen_imbalance" DOUBLE PRECISION,
  "expected_move_pct" DOUBLE PRECISION,
  "stock_gex_proxy" DOUBLE PRECISION,
  "eps_surprise_q1" DOUBLE PRECISION,
  "eps_surprise_q2" DOUBLE PRECISION,
  "eps_beat_streak" BIGINT,
  "eps_miss_after_streak" BIGINT,
  "rev_surprise_q1" DOUBLE PRECISION,
  "fcf_yield" DOUBLE PRECISION,
  "interest_coverage" DOUBLE PRECISION,
  "fcf_positive" BIGINT,
  "debt_coverage_risk" BIGINT,
  "delivery_trend_30d" DOUBLE PRECISION,
  "block_deal_flag" BIGINT,
  "block_deal_direction" BIGINT,
  "short_interest_proxy" DOUBLE PRECISION,
  "promoter_buy_90d_cr" DOUBLE PRECISION,
  "promoter_sell_90d_cr" DOUBLE PRECISION,
  "promoter_net_90d" DOUBLE PRECISION,
  "insider_buy_flag" BIGINT,
  "insider_sell_flag" BIGINT,
  "rating_upgrade_180d" BIGINT,
  "rating_downgrade_180d" BIGINT,
  "days_since_upgrade" BIGINT,
  "mf_sector_flow_pct" DOUBLE PRECISION,
  "receivables_days_ttm" DOUBLE PRECISION,
  "ccc_ttm" DOUBLE PRECISION,
  "ccc_trend" DOUBLE PRECISION,
  "wc_deteriorating" BIGINT,
  "wc_improving" BIGINT,
  "pead_score" DOUBLE PRECISION,
  "event_signal_score" DOUBLE PRECISION,
  "event_type_flags" TEXT,
  "days_to_ex_div" DOUBLE PRECISION,
  "days_to_board_meeting" DOUBLE PRECISION,
  "upcoming_div_pct" DOUBLE PRECISION,
  "positive_turnaround" INTEGER,
  "negative_turnaround" INTEGER,
  "screener_bull_count" REAL,
  "screener_bear_count" REAL,
  "screener_cat_breadth" REAL,
  "screener_tier1_count" REAL,
  "screener_momentum_score" REAL,
  "screener_streak_days" REAL,
  "screener_name_signal" REAL,
  "screener_alpha_score" REAL,
  "atm_iv" REAL,
  "signal_type" TEXT,
  "fcf_yield_approx" DOUBLE PRECISION,
  "breakout_probability" DOUBLE PRECISION,
  "mc_bullish_scan_count" BIGINT,
  "mc_scan_52w_high" BIGINT,
  "mc_scan_squeeze_bo" BIGINT,
  "mc_tech_rating" BIGINT,
  "call_wall_dist_pct" REAL,
  "put_wall_dist_pct" REAL,
  "near_expiry_gamma" REAL,
  "roce" REAL,
  "roce_trend" REAL,
  "quick_ratio" REAL,
  "ev_ebitda" REAL,
  "asset_turnover" REAL,
  "cfo_growth" REAL,
  "mf_net_share_chg_pct" REAL,
  "mf_funds_adding" BIGINT,
  "mf_funds_trimming" BIGINT,
  "mf_add_trim_ratio" DOUBLE PRECISION,
  "mf_pct" DOUBLE PRECISION,
  "promoter_chg_qoq" DOUBLE PRECISION,
  "fii_chg_qoq" DOUBLE PRECISION,
  "mf_chg_qoq" DOUBLE PRECISION,
  "pledge_chg_qoq" DOUBLE PRECISION,
  "mf_avg_pct_assets" DOUBLE PRECISION,
  "mf_big_fund_flow" DOUBLE PRECISION,
  "mf_flow_vs_sector" DOUBLE PRECISION,
  "mf_flow_rank" DOUBLE PRECISION,
  "ext_fii_holding_pct" DOUBLE PRECISION,
  "ext_dii_holding_pct" DOUBLE PRECISION,
  "ext_fii_qoq_chg" DOUBLE PRECISION,
  "ext_dii_qoq_chg" DOUBLE PRECISION,
  "ext_t80_tech_score" DOUBLE PRECISION,
  "ext_t80_quality_rank" DOUBLE PRECISION,
  "ext_t80_valuation_rank" DOUBLE PRECISION,
  "ext_t80_financial_pts" DOUBLE PRECISION,
  "ext_mojo_quality_rank" DOUBLE PRECISION,
  "ext_mojo_valuation_rank" DOUBLE PRECISION,
  "ext_mojo_financial_pts" DOUBLE PRECISION,
  "movement_probability" REAL,
  "days_to_expiry" INTEGER,
  "is_expiry_day" INTEGER,
  "next_expiry_iv" REAL,
  "iv_term_slope" REAL
);
