-- Up Migration
--
-- AF-20261003-07: data_ingestion_dlq had two readers (worker_service /ingestion/dlq and the MCP
-- inspect_ingestion_health tool) and no writer anywhere, so both could only ever report "no dead
-- letters". Both readers and the boot-time CREATE were removed in 796e2e39; fetch failures are
-- recorded per step in job_run_history. The guard refuses to drop a table that has since acquired rows.
DO $$
DECLARE n bigint;
BEGIN
  IF to_regclass('public.data_ingestion_dlq') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.data_ingestion_dlq' INTO n;
    IF n > 0 THEN RAISE EXCEPTION 'data_ingestion_dlq has % rows; refusing to drop', n; END IF;
  END IF;
END $$;

DROP TABLE IF EXISTS data_ingestion_dlq;

-- Down Migration
CREATE TABLE IF NOT EXISTS data_ingestion_dlq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fetcher_name TEXT NOT NULL,
  domain TEXT,
  payload_sample TEXT,
  error_message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  status TEXT DEFAULT 'NEW'
);
