-- Up Migration
--
-- AF-20261003-06: two tables nothing writes and nothing reads, still sitting in the schema where a
-- model can mistake them for live feature sources.
--   * timeframe_scores: the computeTimeframeScores / getTimeframeRanking cluster that wrote it was
--     removed 2026-08-30 (scoring-authority.md); zero rows ever.
--   * order_book_snapshots: no tick/order-book feed exists; zero rows ever, zero code references
--     (factor_backtest.py only mentions it in a comment saying it is empty).
-- Both were 0 rows when this was written (2026-10-04). The guard refuses to drop a table that has
-- since acquired data, so this cannot destroy anything a later writer started to fill.
DO $$
DECLARE n bigint;
BEGIN
  IF to_regclass('public.timeframe_scores') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.timeframe_scores' INTO n;
    IF n > 0 THEN RAISE EXCEPTION 'timeframe_scores has % rows; refusing to drop', n; END IF;
  END IF;
  IF to_regclass('public.order_book_snapshots') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.order_book_snapshots' INTO n;
    IF n > 0 THEN RAISE EXCEPTION 'order_book_snapshots has % rows; refusing to drop', n; END IF;
  END IF;
END $$;

DROP TABLE IF EXISTS timeframe_scores;
DROP TABLE IF EXISTS order_book_snapshots;

-- Down Migration
-- Recreates the (empty) tables with their previous shape.
CREATE TABLE IF NOT EXISTS timeframe_scores (
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  run_id TEXT NOT NULL,
  score DOUBLE PRECISION,
  confidence DOUBLE PRECISION,
  domains_json TEXT,
  reasons_json TEXT,
  suggested_holding_days BIGINT,
  stop_loss DOUBLE PRECISION,
  targets_json TEXT,
  computed_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (symbol, timeframe, run_id)
);
CREATE INDEX IF NOT EXISTS idx_ts_run_id ON timeframe_scores USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_ts_score ON timeframe_scores USING btree (score DESC);

CREATE TABLE IF NOT EXISTS order_book_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL,
  total_buy_qty BIGINT,
  total_sell_qty BIGINT,
  bid_ask_spread DOUBLE PRECISION,
  vwap DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ob_symbol_time ON order_book_snapshots USING btree (symbol, "timestamp" DESC);
