-- Market semantic control plane + bitemporal graph/decision evidence.
-- One DO block is intentional: node-pg-migrate's SQL runner has historically
-- executed only the first statement in a file. All objects are additive and
-- are created in dependency order.
DO $$
BEGIN
  CREATE TABLE IF NOT EXISTS market_data_contract (
    contract_key TEXT PRIMARY KEY,
    dataset TEXT NOT NULL,
    version TEXT NOT NULL,
    grain TEXT NOT NULL DEFAULT '',
    cadence TEXT NOT NULL DEFAULT '',
    unit TEXT,
    time_semantics TEXT NOT NULL DEFAULT 'unknown',
    source_kind TEXT NOT NULL DEFAULT 'unknown',
    training_use TEXT NOT NULL DEFAULT 'caution',
    ontology_version TEXT NOT NULL,
    contract JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (dataset, version)
  );
  CREATE INDEX IF NOT EXISTS idx_market_data_contract_dataset
    ON market_data_contract(dataset, active);

  CREATE TABLE IF NOT EXISTS semantic_feature_definition (
    feature_key TEXT PRIMARY KEY,
    property_name TEXT NOT NULL,
    version TEXT NOT NULL,
    description TEXT NOT NULL,
    semantic_type TEXT NOT NULL,
    datatype TEXT NOT NULL,
    unit TEXT,
    timing TEXT NOT NULL,
    derivation TEXT NOT NULL,
    leakage_risk TEXT NOT NULL,
    pit_notes TEXT NOT NULL DEFAULT '',
    physical_bindings JSONB NOT NULL DEFAULT '[]'::jsonb,
    usable_as_feature BOOLEAN NOT NULL,
    is_label BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (property_name, version)
  );
  CREATE INDEX IF NOT EXISTS idx_semantic_feature_definition_name
    ON semantic_feature_definition(property_name, active);

  CREATE TABLE IF NOT EXISTS market_data_watermark (
    dataset TEXT NOT NULL,
    partition_key TEXT NOT NULL DEFAULT 'ALL',
    as_of TIMESTAMPTZ,
    input_watermark TEXT,
    output_watermark TEXT,
    expected_rows BIGINT,
    accepted_rows BIGINT,
    rejected_rows BIGINT,
    completeness_status TEXT NOT NULL DEFAULT 'unknown'
      CHECK (completeness_status IN ('unknown', 'partial', 'complete', 'blocked')),
    source_version TEXT,
    run_ref TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (dataset, partition_key)
  );
  CREATE INDEX IF NOT EXISTS idx_market_data_watermark_status
    ON market_data_watermark(completeness_status, as_of DESC);

  CREATE TABLE IF NOT EXISTS market_issuer (
    issuer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_key TEXT NOT NULL UNIQUE,
    legal_name TEXT NOT NULL,
    identity_basis TEXT NOT NULL CHECK (identity_basis IN ('isin_issuer_prefix', 'provisional_symbol')),
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL,
    source_ref TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_market_issuer_name
    ON market_issuer(legal_name);

  CREATE TABLE IF NOT EXISTS market_instrument (
    instrument_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_key TEXT NOT NULL UNIQUE,
    issuer_id BIGINT NOT NULL REFERENCES market_issuer(issuer_id),
    name TEXT NOT NULL,
    instrument_type TEXT NOT NULL DEFAULT 'equity',
    isin TEXT,
    identity_basis TEXT NOT NULL CHECK (identity_basis IN ('isin', 'provisional_symbol')),
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL,
    source_ref TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_market_instrument_isin
    ON market_instrument(isin);
  CREATE INDEX IF NOT EXISTS idx_market_instrument_issuer
    ON market_instrument(issuer_id);

  CREATE TABLE IF NOT EXISTS market_listing (
    listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_key TEXT NOT NULL UNIQUE,
    instrument_id BIGINT NOT NULL REFERENCES market_instrument(instrument_id),
    exchange TEXT NOT NULL,
    market_segment TEXT NOT NULL DEFAULT 'equity',
    symbol TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    listed_from DATE,
    listed_to DATE,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL,
    source_ref TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_market_listing_instrument
    ON market_listing(instrument_id);
  CREATE INDEX IF NOT EXISTS idx_market_listing_symbol
    ON market_listing(symbol, exchange);
  CREATE UNIQUE INDEX IF NOT EXISTS uq_market_listing_active
    ON market_listing(exchange, market_segment, symbol) WHERE valid_to IS NULL;

  CREATE TABLE IF NOT EXISTS market_identifier (
    identifier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_key TEXT NOT NULL UNIQUE,
    instrument_id BIGINT NOT NULL REFERENCES market_instrument(instrument_id),
    provider TEXT NOT NULL,
    scheme TEXT NOT NULL,
    identifier_value TEXT NOT NULL,
    mapping_status TEXT NOT NULL DEFAULT 'verified'
      CHECK (mapping_status IN ('verified', 'ambiguous', 'unresolved', 'rejected')),
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL,
    source_ref TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_market_identifier_lookup
    ON market_identifier(provider, scheme, identifier_value, mapping_status);
  CREATE INDEX IF NOT EXISTS idx_market_identifier_instrument
    ON market_identifier(instrument_id, provider, scheme);

  CREATE TABLE IF NOT EXISTS market_identifier_gap (
    provider TEXT NOT NULL,
    scheme TEXT NOT NULL,
    identifier_value TEXT NOT NULL,
    instrument_id BIGINT REFERENCES market_instrument(instrument_id),
    reason TEXT NOT NULL,
    candidate_instrument_ids BIGINT[] NOT NULL DEFAULT '{}',
    first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempts INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (provider, scheme, identifier_value)
  );

  CREATE TABLE IF NOT EXISTS market_graph_node (
    node_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_key TEXT NOT NULL,
    node_type TEXT NOT NULL,
    label TEXT NOT NULL,
    canonical_symbol TEXT,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL,
    source_ref TEXT,
    revision TEXT,
    UNIQUE (node_type, node_key)
  );
  CREATE INDEX IF NOT EXISTS idx_market_graph_node_symbol
    ON market_graph_node(canonical_symbol, node_type);
  CREATE INDEX IF NOT EXISTS idx_market_graph_node_validity
    ON market_graph_node(node_type, valid_from, valid_to);

  CREATE TABLE IF NOT EXISTS market_graph_edge (
    edge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_node_id BIGINT NOT NULL REFERENCES market_graph_node(node_id),
    to_node_id BIGINT REFERENCES market_graph_node(node_id),
    predicate TEXT NOT NULL,
    object_value JSONB,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL,
    source_ref TEXT,
    assertion_key TEXT NOT NULL UNIQUE,
    CHECK (to_node_id IS NOT NULL OR object_value IS NOT NULL)
  );
  CREATE INDEX IF NOT EXISTS idx_market_graph_edge_from
    ON market_graph_edge(from_node_id, predicate);
  CREATE INDEX IF NOT EXISTS idx_market_graph_edge_to
    ON market_graph_edge(to_node_id, predicate);

  CREATE TABLE IF NOT EXISTS market_evidence (
    evidence_key TEXT PRIMARY KEY,
    source_type TEXT NOT NULL,
    source_ref TEXT,
    source_uri TEXT,
    content_hash TEXT,
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    observed_at TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    extraction_method TEXT,
    extraction_version TEXT,
    quality_status TEXT NOT NULL DEFAULT 'unverified'
      CHECK (quality_status IN ('unverified', 'candidate', 'verified', 'rejected'))
  );
  CREATE INDEX IF NOT EXISTS idx_market_evidence_available
    ON market_evidence(available_at DESC, quality_status);

  CREATE TABLE IF NOT EXISTS market_claim (
    claim_key TEXT PRIMARY KEY,
    subject_node_id BIGINT NOT NULL REFERENCES market_graph_node(node_id),
    predicate TEXT NOT NULL,
    object_value JSONB NOT NULL DEFAULT '{}'::jsonb,
    horizon TEXT,
    stance TEXT NOT NULL DEFAULT 'unknown'
      CHECK (stance IN ('bullish', 'bearish', 'neutral', 'unknown')),
    claim_status TEXT NOT NULL DEFAULT 'ungraded'
      CHECK (claim_status IN ('observed', 'vendor_asserted', 'inferred', 'measured', 'ungraded', 'contradicted', 'expired', 'rejected')),
    method TEXT NOT NULL,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    superseded_by TEXT REFERENCES market_claim(claim_key)
  );
  CREATE INDEX IF NOT EXISTS idx_market_claim_subject
    ON market_claim(subject_node_id, claim_status, available_at DESC);

  CREATE TABLE IF NOT EXISTS market_claim_evidence (
    claim_key TEXT NOT NULL REFERENCES market_claim(claim_key) ON DELETE CASCADE,
    evidence_key TEXT NOT NULL REFERENCES market_evidence(evidence_key) ON DELETE CASCADE,
    relation TEXT NOT NULL CHECK (relation IN ('supports', 'opposes', 'context')),
    contribution DOUBLE PRECISION,
    note TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (claim_key, evidence_key)
  );


  CREATE TABLE IF NOT EXISTS market_decision_event (
    decision_key TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    computed_at TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    knowledge_cutoff TIMESTAMPTZ NOT NULL,
    knowledge_cutoff_kind TEXT NOT NULL DEFAULT 'generation_upper_bound',
    source_table TEXT NOT NULL DEFAULT 'unified_recommendations',
    source_key TEXT NOT NULL,
    ranker_policy_version TEXT NOT NULL,
    feature_set_version TEXT NOT NULL,
    model_versions JSONB NOT NULL DEFAULT '[]'::jsonb,
    score DOUBLE PRECISION,
    classification TEXT,
    timeframe TEXT,
    decision_status TEXT NOT NULL DEFAULT 'advisory'
      CHECK (decision_status IN ('advisory', 'shadow', 'publishable', 'blocked', 'expired')),
    quality_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    data_watermarks JSONB NOT NULL DEFAULT '{}'::jsonb,
    veto_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    guardrails JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  CREATE INDEX IF NOT EXISTS idx_market_decision_event_symbol
    ON market_decision_event(symbol, generated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_market_decision_event_status
    ON market_decision_event(decision_status, generated_at DESC);

  CREATE TABLE IF NOT EXISTS market_decision_evidence (
    decision_key TEXT NOT NULL REFERENCES market_decision_event(decision_key) ON DELETE CASCADE,
    evidence_key TEXT NOT NULL,
    relation TEXT NOT NULL CHECK (relation IN ('supports', 'contradicts', 'context', 'veto')),
    evidence_type TEXT NOT NULL,
    metric TEXT,
    value_json JSONB,
    source_table TEXT,
    source_ref TEXT,
    observed_at TIMESTAMPTZ,
    available_at TIMESTAMPTZ,
    confidence_kind TEXT NOT NULL DEFAULT 'unknown',
    note TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (decision_key, evidence_key)
  );
  CREATE INDEX IF NOT EXISTS idx_market_decision_evidence_relation
    ON market_decision_evidence(decision_key, relation);

  CREATE TABLE IF NOT EXISTS market_decision_outcome (
    decision_key TEXT NOT NULL REFERENCES market_decision_event(decision_key) ON DELETE CASCADE,
    label_definition TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    outcome_status TEXT NOT NULL DEFAULT 'pending'
      CHECK (outcome_status IN ('pending', 'resolved', 'invalid')),
    entry_price DOUBLE PRECISION,
    exit_price DOUBLE PRECISION,
    return_pct DOUBLE PRECISION,
    mfe_pct DOUBLE PRECISION,
    mae_pct DOUBLE PRECISION,
    resolved_at TIMESTAMPTZ,
    source_table TEXT,
    source_ref TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (decision_key, label_definition, horizon_days)
  );
END $$;

