-- GENERATED by scripts/generate_pg_schema.py — do not edit by hand.
-- Apply with:  psql "$POSTGRES_URL" -f db/schema.postgres.sql
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ── _migrations ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "_migrations" (
  "name" TEXT,
  "applied_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("name")
);

-- ── agent_audit_reports ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "agent_audit_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_date" TEXT NOT NULL,
  "audit_for_date" TEXT NOT NULL,
  "timeframe" TEXT NOT NULL,
  "total_picks" BIGINT,
  "hits" BIGINT,
  "misses" BIGINT,
  "open_positions" BIGINT,
  "hit_rate" DOUBLE PRECISION,
  "avg_return_pct" DOUBLE PRECISION,
  "profit_factor" DOUBLE PRECISION,
  "nifty_return_pct" DOUBLE PRECISION,
  "alpha_pct" DOUBLE PRECISION,
  "best_pick" TEXT,
  "worst_pick" TEXT,
  "signal_attribution_json" TEXT,
  "narrative" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_aar_run_date_tf ON agent_audit_reports(run_date, timeframe);
CREATE INDEX idx_aar_run_date  ON agent_audit_reports(run_date DESC);
CREATE INDEX idx_aar_timeframe ON agent_audit_reports(timeframe);

-- ── agent_data_scientist_reports ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "agent_data_scientist_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_date" TEXT NOT NULL,
  "ohlcv_coverage_pct" DOUBLE PRECISION,
  "stale_symbols_count" BIGINT,
  "fundamentals_fresh_count" BIGINT,
  "model_auc" DOUBLE PRECISION,
  "model_drift_detected" BIGINT DEFAULT 0,
  "signal_resolution_rate" DOUBLE PRECISION,
  "data_quality_score" DOUBLE PRECISION,
  "quality_grade" TEXT,
  "issues_json" TEXT,
  "narrative" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_ads_run_date ON agent_data_scientist_reports(run_date);

-- ── agent_optimizer_reports ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "agent_optimizer_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_date" TEXT NOT NULL,
  "trigger" TEXT NOT NULL,
  "baseline_win_rate" DOUBLE PRECISION,
  "new_win_rate" DOUBLE PRECISION,
  "improvement_pct" DOUBLE PRECISION,
  "weights_changed" BIGINT DEFAULT 0,
  "full_optimizer_triggered" BIGINT DEFAULT 0,
  "changes_json" TEXT,
  "underperforming_segments_json" TEXT,
  "narrative" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_aor_run_date ON agent_optimizer_reports(run_date);

-- ── agent_strategy_picks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "agent_strategy_picks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_date" TEXT NOT NULL,
  "timeframe" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "rank" BIGINT NOT NULL,
  "conviction" TEXT NOT NULL,
  "entry_zone_low" DOUBLE PRECISION,
  "entry_zone_high" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "target_2" DOUBLE PRECISION,
  "target_3" DOUBLE PRECISION,
  "composite_score" DOUBLE PRECISION,
  "quant_rank" DOUBLE PRECISION,
  "confluence_score" DOUBLE PRECISION,
  "regime_alignment" TEXT,
  "supporting_signals_json" TEXT,
  "narrative" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_asp_run_date_tf ON agent_strategy_picks(run_date, timeframe);
CREATE INDEX idx_asp_symbol      ON agent_strategy_picks(symbol);
CREATE INDEX idx_asp_run_date  ON agent_strategy_picks(run_date DESC);
CREATE INDEX idx_asp_timeframe ON agent_strategy_picks(timeframe, rank);

-- ── analyst_estimates_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "analyst_estimates_history" (
  "symbol" TEXT NOT NULL,
  "as_of_date" TEXT NOT NULL,
  "n_analysts" BIGINT,
  "final_rating" TEXT,
  "buy_count" BIGINT,
  "hold_count" BIGINT,
  "sell_count" BIGINT,
  "target_high" DOUBLE PRECISION,
  "target_mean" DOUBLE PRECISION,
  "target_low" DOUBLE PRECISION,
  "eps_est_next" DOUBLE PRECISION,
  "revenue_est_next" DOUBLE PRECISION,
  "captured_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "as_of_date")
);
CREATE INDEX idx_aeh_sym_date ON analyst_estimates_history(symbol, as_of_date DESC);

-- ── app_settings ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "app_settings" (
  "key" TEXT,
  "value" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("key")
);

-- ── backtest_strategies ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "backtest_strategies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "timeframe" TEXT,
  "params" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- ── backtesting_runs ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "backtesting_runs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_name" TEXT,
  "strategy_config_json" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "symbols_count" BIGINT,
  "total_trades" BIGINT,
  "win_rate" DOUBLE PRECISION,
  "total_return_pct" DOUBLE PRECISION,
  "cagr_pct" DOUBLE PRECISION,
  "sharpe_ratio" DOUBLE PRECISION,
  "calmar_ratio" DOUBLE PRECISION,
  "sortino_ratio" DOUBLE PRECISION,
  "max_drawdown_pct" DOUBLE PRECISION,
  "nifty_return_pct" DOUBLE PRECISION,
  "alpha_pct" DOUBLE PRECISION,
  "avg_trade_return_pct" DOUBLE PRECISION,
  "profit_factor" DOUBLE PRECISION,
  "avg_holding_days" DOUBLE PRECISION,
  "monthly_returns_json" TEXT,
  "equity_curve_json" TEXT,
  "trade_log_json" TEXT,
  "run_at" TIMESTAMPTZ DEFAULT now(),
  "walk_forward_folds_json" TEXT
);

-- ── bulk_block_deals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "bulk_block_deals" (
  "symbol" TEXT NOT NULL,
  "deal_date" TEXT NOT NULL,
  "deal_type" TEXT NOT NULL,
  "client_name" TEXT NOT NULL,
  "buy_sell" TEXT,
  "quantity" DOUBLE PRECISION,
  "price" DOUBLE PRECISION,
  "value_cr" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("symbol", "deal_date", "client_name", "deal_type")
);

-- ── bulk_deals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "bulk_deals" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "clientName" TEXT NOT NULL,
  "dealType" TEXT NOT NULL,
  "quantity" BIGINT NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "valueCr" DOUBLE PRECISION NOT NULL,
  "source" TEXT
);
CREATE INDEX idx_bulk_sym_date ON bulk_deals(symbol, date DESC);

-- ── chart_patterns ─────────────────────────────────────────────
-- chart_patterns dropped 2026-07-30 (migrations/1785500000001_drop-dead-tables.sql) --
-- confirmed zero writers/readers anywhere in the live app; superseded by mc_chart_patterns.

-- ── company_profiles ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "company_profiles" (
  "symbol" TEXT,
  "company_name" TEXT,
  "description" TEXT,
  "high_growth_scope" BIGINT DEFAULT 0,
  "in_news_for_growth" BIGINT DEFAULT 0,
  "growth_score" DOUBLE PRECISION DEFAULT 0,
  "ai_analysis" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol")
);

-- ── confluence_signals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "confluence_signals" (
  "symbol" TEXT NOT NULL,
  "computed_at" TIMESTAMPTZ NOT NULL,
  "confluence_score" DOUBLE PRECISION NOT NULL,
  "conviction_level" TEXT NOT NULL,
  "active_screener_count" BIGINT NOT NULL DEFAULT 0,
  "bullish_screener_count" BIGINT NOT NULL DEFAULT 0,
  "bearish_screener_count" BIGINT NOT NULL DEFAULT 0,
  "screener_ids_json" TEXT NOT NULL DEFAULT '[]',
  "screener_names_json" TEXT NOT NULL DEFAULT '[]',
  "screener_weights_json" TEXT NOT NULL DEFAULT '{}',
  "trend_alignment_score" DOUBLE PRECISION DEFAULT 0,
  "volume_score" DOUBLE PRECISION DEFAULT 0,
  "sector_strength_score" DOUBLE PRECISION DEFAULT 0,
  "fundamental_score" DOUBLE PRECISION DEFAULT 0,
  "ml_breakout_probability" DOUBLE PRECISION,
  "ml_trend_probability" DOUBLE PRECISION,
  "suggested_timeframe" TEXT DEFAULT 'POSITIONAL',
  "entry_zone_low" DOUBLE PRECISION,
  "entry_zone_high" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "target_2" DOUBLE PRECISION,
  "target_3" DOUBLE PRECISION,
  "risk_reward" DOUBLE PRECISION,
  "ai_conclusion" TEXT,
  "trade_reasoning" TEXT,
  "sector" TEXT,
  "market_cap" DOUBLE PRECISION,
  "current_price" DOUBLE PRECISION,
  "current_volume" BIGINT,
  "rsi" DOUBLE PRECISION,
  "atr" DOUBLE PRECISION,
  "expires_at" TIMESTAMPTZ,
  PRIMARY KEY ("symbol", "computed_at")
);
CREATE INDEX idx_csi_score   ON confluence_signals(confluence_score DESC);
CREATE INDEX idx_csi_symbol  ON confluence_signals(symbol);
CREATE INDEX idx_csi_computed ON confluence_signals(computed_at DESC);
CREATE INDEX idx_csi_level   ON confluence_signals(conviction_level);
CREATE INDEX idx_csi_sector  ON confluence_signals(sector);

-- ── corporate_actions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "corporate_actions" (
  "symbol" TEXT NOT NULL,
  "ex_date" TEXT NOT NULL,
  "action_type" TEXT NOT NULL,
  "ratio" DOUBLE PRECISION,
  "amount" DOUBLE PRECISION,
  "source" TEXT DEFAULT 'yfinance',
  "ingested_at" TEXT DEFAULT now(),
  PRIMARY KEY ("symbol", "ex_date", "action_type")
);

-- ── credit_rating_events ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "credit_rating_events" (
  "bse_code" TEXT NOT NULL,
  "symbol" TEXT,
  "isin" TEXT,
  "announcement_date" TEXT NOT NULL,
  "rating_agency" TEXT NOT NULL,
  "action" TEXT,
  "instrument_type" TEXT,
  "headline" TEXT,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("bse_code", "announcement_date", "rating_agency")
);

-- ── daily_research_reports ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "daily_research_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_date" TEXT NOT NULL,
  "report_type" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "generated_at" TIMESTAMPTZ,
  "market_regime" TEXT,
  "sentiment_score" DOUBLE PRECISION,
  "fii_net_5d" DOUBLE PRECISION,
  "top_picks_json" TEXT,
  "report_json" TEXT,
  "ai_blurbs_json" TEXT,
  "error_message" TEXT,
  UNIQUE ("report_date", "report_type")
);

-- ── deep_learning_predictions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "deep_learning_predictions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "prediction_date" TEXT NOT NULL,
  "model_name" TEXT NOT NULL,
  "model_version" TEXT NOT NULL,
  "prob_up_1d" DOUBLE PRECISION,
  "prob_up_5d" DOUBLE PRECISION,
  "prob_up_15d" DOUBLE PRECISION,
  "prob_dn_1d" DOUBLE PRECISION,
  "prob_dn_5d" DOUBLE PRECISION,
  "prob_dn_15d" DOUBLE PRECISION,
  "exp_ret_1d" DOUBLE PRECISION,
  "exp_ret_5d" DOUBLE PRECISION,
  "exp_ret_15d" DOUBLE PRECISION,
  "confidence" DOUBLE PRECISION,
  "uncertainty" DOUBLE PRECISION,
  "regime" TEXT,
  "regime_confidence" DOUBLE PRECISION,
  "top_features_json" TEXT,
  "attention_json" TEXT,
  "actual_ret_5d" DOUBLE PRECISION,
  "actual_ret_15d" DOUBLE PRECISION,
  "outcome_5d" TEXT,
  "outcome_15d" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("symbol", "prediction_date", "model_name")
);

-- ── dl_model_performance ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "dl_model_performance" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" TEXT NOT NULL,
  "model_version" TEXT NOT NULL,
  "eval_date" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "directional_accuracy" DOUBLE PRECISION,
  "roc_auc" DOUBLE PRECISION,
  "precision_up" DOUBLE PRECISION,
  "recall_up" DOUBLE PRECISION,
  "f1_score" DOUBLE PRECISION,
  "sharpe_ratio" DOUBLE PRECISION,
  "profit_factor" DOUBLE PRECISION,
  "sample_count" BIGINT,
  "drift_score" DOUBLE PRECISION,
  "retrain_triggered" BIGINT DEFAULT 0,
  UNIQUE ("model_name", "eval_date", "horizon_days")
);

-- ── early_hours_predictions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "early_hours_predictions" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "score" DOUBLE PRECISION NOT NULL,
  "iep_gap_pct" DOUBLE PRECISION,
  "preopen_imbalance" DOUBLE PRECISION,
  "delivery_spike_pct" DOUBLE PRECISION,
  "has_corporate_action" BIGINT DEFAULT 0,
  "corporate_action_title" TEXT,
  "breakout_signals" TEXT,
  "reasons_json" TEXT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "date")
);
CREATE INDEX idx_ehp_date ON early_hours_predictions(date DESC);

-- ── eco_calendar ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "eco_calendar" (
  "calendar_id" TEXT,
  "event_date" TEXT,
  "event_time" TEXT,
  "country" TEXT,
  "country_name" TEXT,
  "event_name" TEXT,
  "category" TEXT,
  "impact" BIGINT,
  "actual" TEXT,
  "previous" TEXT,
  "consensus" TEXT,
  "reference" TEXT,
  "symbol" TEXT,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("calendar_id")
);

-- ── eps_surprise_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "eps_surprise_history" (
  "scid" TEXT NOT NULL,
  "symbol" TEXT,
  "quarter" TEXT NOT NULL,
  "np_actual" DOUBLE PRECISION,
  "np_estimate" DOUBLE PRECISION,
  "np_surprise" DOUBLE PRECISION,
  "rev_actual" DOUBLE PRECISION,
  "rev_estimate" DOUBLE PRECISION,
  "rev_surprise" DOUBLE PRECISION,
  "eps_actual" DOUBLE PRECISION,
  "eps_estimate" DOUBLE PRECISION,
  "eps_surprise" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("scid", "quarter")
);

-- ── etnow_screener_stocks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "etnow_screener_stocks" (
  "screener_id" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "stock_name" TEXT,
  "first_seen" TEXT,
  "last_seen" TEXT,
  PRIMARY KEY ("screener_id", "symbol")
);

-- ── etnow_screeners ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "etnow_screeners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screener_id" TEXT NOT NULL,
  "screener_name" TEXT NOT NULL,
  "query_condition" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("screener_id")
);

-- ── et_marketstats_screener_stocks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "et_marketstats_screener_stocks" (
  "screener_key" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "stock_name" TEXT,
  "asset_id" TEXT,
  "exchange_id" TEXT,
  "last_traded_price" DOUBLE PRECISION,
  "percent_change" DOUBLE PRECISION,
  "raw_data" TEXT,
  "first_seen" TEXT,
  "last_seen" TEXT,
  PRIMARY KEY ("screener_key", "symbol")
);
CREATE INDEX IF NOT EXISTS "idx_ems_stock_symbol" ON "et_marketstats_screener_stocks" ("symbol");

-- ── et_marketstats_screeners ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "et_marketstats_screeners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screener_key" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "endpoint" TEXT NOT NULL,
  "view_id" BIGINT,
  "first_operand" TEXT,
  "operation_type" TEXT,
  "second_operand" TEXT,
  "api_type" TEXT,
  "duration" TEXT,
  "timespan" TEXT,
  "screener_page_url" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("screener_key")
);

-- ── feature_importance_log ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "feature_importance_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_id" BIGINT,
  "model_name" TEXT NOT NULL,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  "feature_name" TEXT NOT NULL,
  "importance" DOUBLE PRECISION,
  "rank_position" BIGINT
);
CREATE INDEX idx_feat_model ON feature_importance_log(model_name, computed_at DESC);

-- ── gdelt_sentiment ─────────────────────────────────────────────
-- Per-stock GDELT news tone (gdeltService.ts); mirrored in pgClient.ts's pgEnsureColumns()
-- since this table historically had no schema entry here.
CREATE TABLE IF NOT EXISTS "gdelt_sentiment" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "avg_tone" DOUBLE PRECISION,
  "computed_at" TEXT,
  PRIMARY KEY ("symbol", "date")
);

-- ── feature_store ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "feature_store" (
  "symbol" TEXT NOT NULL,
  "date" DATE NOT NULL,
  "timeframe" TEXT NOT NULL DEFAULT 'D',
  "ret_1d" DOUBLE PRECISION,
  "ret_5d" DOUBLE PRECISION,
  "ret_15d" DOUBLE PRECISION,
  "ret_21d" DOUBLE PRECISION,
  "ret_63d" DOUBLE PRECISION,
  "ret_126d" DOUBLE PRECISION,
  "ret_252d" DOUBLE PRECISION,
  "sma20" DOUBLE PRECISION,
  "sma50" DOUBLE PRECISION,
  "sma200" DOUBLE PRECISION,
  "ema8" DOUBLE PRECISION,
  "ema21" DOUBLE PRECISION,
  "dist_sma20_pct" DOUBLE PRECISION,
  "dist_sma200_pct" DOUBLE PRECISION,
  "above_sma200" BIGINT,
  "rsi_14" DOUBLE PRECISION,
  "rsi_28" DOUBLE PRECISION,
  "macd" DOUBLE PRECISION,
  "macd_signal" DOUBLE PRECISION,
  "macd_hist" DOUBLE PRECISION,
  "adx" DOUBLE PRECISION,
  "di_plus" DOUBLE PRECISION,
  "di_minus" DOUBLE PRECISION,
  "stoch_k" DOUBLE PRECISION,
  "stoch_d" DOUBLE PRECISION,
  "cci" DOUBLE PRECISION,
  "williams_r" DOUBLE PRECISION,
  "atr_14" DOUBLE PRECISION,
  "atr_pct" DOUBLE PRECISION,
  "bb_upper" DOUBLE PRECISION,
  "bb_lower" DOUBLE PRECISION,
  "bb_width" DOUBLE PRECISION,
  "bb_pct" DOUBLE PRECISION,
  "hist_vol_21d" DOUBLE PRECISION,
  "hist_vol_63d" DOUBLE PRECISION,
  "vol_regime" TEXT,
  "volume_ratio_20d" DOUBLE PRECISION,
  "volume_ratio_5d" DOUBLE PRECISION,
  "obv" DOUBLE PRECISION,
  "obv_slope" DOUBLE PRECISION,
  "vwap" DOUBLE PRECISION,
  "vwap_dist_pct" DOUBLE PRECISION,
  "trend_1d" TEXT,
  "trend_1w" TEXT,
  "trend_1m" TEXT,
  "mtf_alignment_score" DOUBLE PRECISION,
  "pcr_oi" DOUBLE PRECISION,
  "pcr_vol" DOUBLE PRECISION,
  "iv_rank" DOUBLE PRECISION,
  "max_pain" DOUBLE PRECISION,
  "fii_3d_net" DOUBLE PRECISION,
  "fii_10d_net" DOUBLE PRECISION,
  "dii_3d_net" DOUBLE PRECISION,
  "delivery_pct" DOUBLE PRECISION,
  "trailing_pe" DOUBLE PRECISION,
  "pb" DOUBLE PRECISION,
  "roe" DOUBLE PRECISION,
  "debt_to_equity" DOUBLE PRECISION,
  "op_margins" DOUBLE PRECISION,
  "rev_growth" DOUBLE PRECISION,
  "eps_growth" DOUBLE PRECISION,
  "piotroski_f" DOUBLE PRECISION,
  "earnings_yield" DOUBLE PRECISION,
  "nifty_vix" DOUBLE PRECISION,
  "nifty_pe" DOUBLE PRECISION,
  "advance_decline_ratio" DOUBLE PRECISION,
  "nifty_ret_5d" DOUBLE PRECISION,
  "nifty_ret_21d" DOUBLE PRECISION,
  "us_10y_yield" DOUBLE PRECISION,
  "dxy" DOUBLE PRECISION,
  "crude_ret_5d" DOUBLE PRECISION,
  "gold_ret_5d" DOUBLE PRECISION,
  "sp500_ret_5d" DOUBLE PRECISION,
  "news_sentiment_score" DOUBLE PRECISION,
  "news_impact_count" BIGINT,
  "target_ret_1d" DOUBLE PRECISION,
  "target_ret_5d" DOUBLE PRECISION,
  "target_ret_15d" DOUBLE PRECISION,
  "target_dir_1d" BIGINT,
  "target_dir_5d" BIGINT,
  "target_dir_15d" BIGINT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  "ret_12m_ex1m" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "date", "timeframe")
);
CREATE INDEX idx_fs_sym_tf_date ON feature_store(symbol, timeframe, date);
CREATE INDEX idx_fs_date ON feature_store(date);

-- ── fii_dii_flow ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "fii_dii_flow" (
  "date" TEXT,
  "fii_buy" DOUBLE PRECISION,
  "fii_sell" DOUBLE PRECISION,
  "fii_net" DOUBLE PRECISION,
  "dii_buy" DOUBLE PRECISION,
  "dii_sell" DOUBLE PRECISION,
  "dii_net" DOUBLE PRECISION,
  -- Segment breakdown from investsights (fii_dii_history_fetcher.py). fii_net stays CASH
  -- EQUITY; fii_net_all_segments is the derivatives-dominated all-segment figure, and mf_*
  -- is mutual-funds-only -- a subset of dii_net, not a substitute. See the 1785600000000
  -- migration for the live measurements behind keeping these apart.
  "fii_equity" DOUBLE PRECISION,
  "fii_debt" DOUBLE PRECISION,
  "fii_derivatives" DOUBLE PRECISION,
  "fii_net_all_segments" DOUBLE PRECISION,
  "mf_equity" DOUBLE PRECISION,
  "mf_debt" DOUBLE PRECISION,
  "mf_derivatives" DOUBLE PRECISION,
  "mf_total" DOUBLE PRECISION,
  "source" TEXT DEFAULT 'NSE',
  "fetched_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("date")
);
CREATE INDEX idx_fii_date ON fii_dii_flow(date DESC);

-- ── fundamentals_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "fundamentals_history" (
  "symbol" TEXT NOT NULL,
  "as_of_date" TEXT NOT NULL,
  "fifty_two_week_high" DOUBLE PRECISION,
  "piotroski_f_score" BIGINT,
  "debt_to_equity" DOUBLE PRECISION,
  "operating_margins" DOUBLE PRECISION,
  "return_on_equity" DOUBLE PRECISION,
  "revenue_growth" DOUBLE PRECISION,
  "earnings_growth" DOUBLE PRECISION,
  "earnings_yield" DOUBLE PRECISION,
  "price_to_book" DOUBLE PRECISION,
  "market_cap" DOUBLE PRECISION,
  "captured_at" TIMESTAMPTZ DEFAULT now(),
  "pledge_pct" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "as_of_date")
);
CREATE INDEX idx_fh_sym_date ON fundamentals_history(symbol, as_of_date DESC);

-- ── historical_fno_sentiment ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "historical_fno_sentiment" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "pcr_oi" DOUBLE PRECISION,
  "pcr_vol" DOUBLE PRECISION,
  "max_pain" DOUBLE PRECISION,
  "atm_iv" DOUBLE PRECISION,
  "iv_skew" DOUBLE PRECISION,
  "total_ce_oi" BIGINT,
  "total_pe_oi" BIGINT,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "date")
);

-- ── historical_fundamentals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "historical_fundamentals" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "trailing_pe" DOUBLE PRECISION,
  "forward_pe" DOUBLE PRECISION,
  "price_to_book" DOUBLE PRECISION,
  "book_value" DOUBLE PRECISION,
  "earnings_yield" DOUBLE PRECISION,
  "eps_ttm" DOUBLE PRECISION,
  "eps_forward" DOUBLE PRECISION,
  "revenue_growth" DOUBLE PRECISION,
  "debt_to_equity" DOUBLE PRECISION,
  "roe" DOUBLE PRECISION,
  "roce" DOUBLE PRECISION,
  "operating_margin" DOUBLE PRECISION,
  "net_margin" DOUBLE PRECISION,
  "piotroski_score" BIGINT,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "date")
);

-- ── index_max_pain ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "index_max_pain" (
  "index_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "max_pain" DOUBLE PRECISION,
  "pcr_oi" DOUBLE PRECISION,
  "total_ce_oi" BIGINT,
  "total_pe_oi" BIGINT,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("index_name", "date", "expiry")
);

-- ── index_option_oi ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "index_option_oi" (
  "index_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "strike" DOUBLE PRECISION NOT NULL,
  "ce_oi" BIGINT,
  "pe_oi" BIGINT,
  "ce_oi_change" BIGINT,
  "pe_oi_change" BIGINT,
  "ce_ltp" DOUBLE PRECISION,
  "pe_ltp" DOUBLE PRECISION,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("index_name", "date", "expiry", "strike")
);

-- ── index_provider_map ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "index_provider_map" (
  "index_name" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "provider_id" TEXT NOT NULL,
  PRIMARY KEY ("index_name", "provider")
);

-- ── index_valuation ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "index_valuation" (
  "index_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "pe" DOUBLE PRECISION,
  "pb" DOUBLE PRECISION,
  "div_yield" DOUBLE PRECISION,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("index_name", "date")
);
CREATE INDEX idx_iv_name_date ON index_valuation(index_name, date DESC);

-- ── insider_trades ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "insider_trades" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "acquirerName" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "typeOfTransaction" TEXT NOT NULL,
  "quantity" BIGINT NOT NULL,
  "valueInr" DOUBLE PRECISION NOT NULL,
  "date" TEXT NOT NULL
);
CREATE INDEX idx_insider_sym ON insider_trades(symbol, date DESC);

-- ── insider_transactions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "insider_transactions" (
  "symbol" TEXT NOT NULL,
  "person_name" TEXT NOT NULL,
  "person_category" TEXT,
  "transaction_mode" TEXT NOT NULL,
  "quantity" DOUBLE PRECISION,
  "value_cr" DOUBLE PRECISION,
  "before_pct" DOUBLE PRECISION,
  "after_pct" DOUBLE PRECISION,
  "transaction_date" TEXT NOT NULL,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("symbol", "person_name", "transaction_date", "transaction_mode")
);

-- ── institutional_rankings ─────────────────────────────────────────────
-- institutional_rankings dropped 2026-07-30 (migrations/1785500000001_drop-dead-tables.sql) --
-- confirmed zero writers/readers anywhere in the live app; superseded by quant_scores.

-- ── intraday_breadth_snapshots ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_breadth_snapshots" (
  "snapshot_at" TEXT,
  "date" TEXT,
  "adv" BIGINT,
  "dec" BIGINT,
  "unch" BIGINT,
  "total" BIGINT,
  "adv_decline_ratio" DOUBLE PRECISION,
  "pct_positive" DOUBLE PRECISION,
  "avg_change_pct" DOUBLE PRECISION,
  "breadth_score" DOUBLE PRECISION,
  "risk_tilt" TEXT,
  "computed_at" TEXT,
  PRIMARY KEY ("snapshot_at")
);

-- ── intraday_ohlcv ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_ohlcv" (
  "symbol" TEXT NOT NULL,
  "datetime" TIMESTAMPTZ NOT NULL,
  "open" DOUBLE PRECISION,
  "high" DOUBLE PRECISION,
  "low" DOUBLE PRECISION,
  "close" DOUBLE PRECISION,
  "volume" BIGINT,
  "vwap" DOUBLE PRECISION,
  "interval" TEXT DEFAULT '15m',
  PRIMARY KEY ("symbol", "datetime", "interval")
);
CREATE INDEX idx_intra_sym ON intraday_ohlcv(symbol, datetime DESC);

-- ── intraday_recommendation_outcomes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_recommendation_outcomes" (
  "symbol" TEXT,
  "computed_at" TEXT,
  "entry_price" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "day_high" DOUBLE PRECISION,
  "day_low" DOUBLE PRECISION,
  "day_close" DOUBLE PRECISION,
  "exit_price" DOUBLE PRECISION,
  "exit_reason" TEXT,
  "pnl_pct" DOUBLE PRECISION,
  "outcome" TEXT,
  "resolved_at" TIMESTAMPTZ,
  PRIMARY KEY ("symbol", "computed_at")
);

-- ── intraday_recommendations ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_recommendations" (
  "symbol" TEXT,
  "computed_at" TEXT,
  "intraday_regime" TEXT,
  "intraday_score" DOUBLE PRECISION,
  "conviction_level" TEXT,
  "classification" TEXT,
  "screener_score" DOUBLE PRECISION,
  "breakout_score" DOUBLE PRECISION,
  "bullish_count" BIGINT,
  "bearish_count" BIGINT,
  "cmp" DOUBLE PRECISION,
  "entry_price" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "risk_reward" DOUBLE PRECISION,
  "position_size_pct" DOUBLE PRECISION,
  "reasoning" TEXT,
  "computed_ts" TIMESTAMPTZ,
  PRIMARY KEY ("symbol", "computed_at")
);

-- ── intraday_recommendations_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_recommendations_history" (
  "symbol" TEXT NOT NULL,
  "computed_at" TEXT NOT NULL,
  "cycle_at" TEXT NOT NULL,
  "intraday_regime" TEXT,
  "intraday_score" DOUBLE PRECISION,
  "conviction_level" TEXT,
  "classification" TEXT,
  "screener_score" DOUBLE PRECISION,
  "breakout_score" DOUBLE PRECISION,
  "news_sentiment" DOUBLE PRECISION,
  "bullish_count" BIGINT,
  "bearish_count" BIGINT,
  "cmp" DOUBLE PRECISION,
  "entry_price" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "risk_reward" DOUBLE PRECISION,
  "position_size_pct" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "cycle_at")
);
CREATE INDEX idx_irh_symbol_date ON intraday_recommendations_history(symbol, computed_at, cycle_at);

-- ── intraday_regime_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_regime_history" (
  "computed_at" TEXT,
  "date" TEXT,
  "regime" TEXT,
  "composite" DOUBLE PRECISION,
  "vix" DOUBLE PRECISION,
  "mmi" DOUBLE PRECISION,
  "usdinr_chg" DOUBLE PRECISION,
  "basis" DOUBLE PRECISION,
  "breadth_score" DOUBLE PRECISION,
  PRIMARY KEY ("computed_at")
);

-- ── intraday_strategy_lifts ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "intraday_strategy_lifts" (
  "as_of" TEXT,
  "dimension" TEXT,
  "bucket" TEXT,
  "n" BIGINT,
  "wins" BIGINT,
  "win_rate" DOUBLE PRECISION,
  "lift" DOUBLE PRECISION,
  "avg_pnl" DOUBLE PRECISION,
  PRIMARY KEY ("as_of", "dimension", "bucket")
);

-- ── job_heartbeat ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "job_heartbeat" (
  "job_name" TEXT,
  "last_status" TEXT,
  "last_run_at" BIGINT,
  "last_success_at" BIGINT,
  "last_error" TEXT,
  "run_count" BIGINT DEFAULT 0,
  "fail_count" BIGINT DEFAULT 0,
  "last_alert_sent_at" BIGINT,
  PRIMARY KEY ("job_name")
);

-- ── live_screener_appearances ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "live_screener_appearances" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_id" BIGINT NOT NULL,
  "symbol" TEXT NOT NULL,
  "filter_key" TEXT NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "change_per" DOUBLE PRECISION,
  "volume" BIGINT
);
CREATE INDEX idx_lsa_run ON live_screener_appearances(run_id);
CREATE INDEX idx_lsa_symbol_filter ON live_screener_appearances(symbol, filter_key);

-- ── live_screener_outcomes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "live_screener_outcomes" (
  "appearance_id" BIGINT,
  "symbol" TEXT NOT NULL,
  "filter_key" TEXT NOT NULL,
  "appeared_at" TEXT NOT NULL,
  "entry_price" DOUBLE PRECISION NOT NULL,
  "return_1d" DOUBLE PRECISION,
  "return_3d" DOUBLE PRECISION,
  "return_5d" DOUBLE PRECISION,
  "return_intraday" DOUBLE PRECISION,
  PRIMARY KEY ("appearance_id")
);

-- ── live_screener_runs ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "live_screener_runs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" TEXT NOT NULL,
  "filters_completed" BIGINT NOT NULL,
  "total_filters" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "error_log" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now()
);

-- ── live_screener_ml_scores ─────────────────────────────────────────────
-- ML win-probability per (run, symbol) from live_screener_ml_ranker.py, scored against
-- the currently-active live_screener_intraday_clf.pkl right after each collection cycle.
CREATE TABLE IF NOT EXISTS "live_screener_ml_scores" (
  "run_id" BIGINT NOT NULL,
  "symbol" TEXT NOT NULL,
  "win_probability" DOUBLE PRECISION NOT NULL,
  "model_version" TEXT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("run_id", "symbol")
);
CREATE INDEX IF NOT EXISTS idx_lsms_run ON live_screener_ml_scores(run_id);

-- ── macro_asset_prices ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "macro_asset_prices" (
  "date" DATE NOT NULL,
  "symbol" TEXT NOT NULL,
  "close" DOUBLE PRECISION,
  "ret_1d" DOUBLE PRECISION,
  "ret_5d" DOUBLE PRECISION,
  "fetched_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("date", "symbol")
);

-- ── macro_indicators ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "macro_indicators" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "indicator_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "value" DOUBLE PRECISION,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("indicator_name", "date")
);
CREATE INDEX idx_macro_date ON macro_indicators(date DESC);

-- ── market_breadth ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "market_breadth" (
  "date" TEXT,
  "pct_above_200dma" DOUBLE PRECISION,
  "adv_decline_ratio" DOUBLE PRECISION,
  "pct_at_20d_high" DOUBLE PRECISION,
  "net_highs_lows" DOUBLE PRECISION,
  "computed_at" TEXT,
  PRIMARY KEY ("date")
);

-- ── market_holidays ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "market_holidays" (
  "date" TEXT NOT NULL,
  "exchange" TEXT NOT NULL DEFAULT 'NSE',
  "description" TEXT,
  PRIMARY KEY ("date", "exchange")
);

-- ── market_regimes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "market_regimes" (
  "date" TEXT,
  "regime" TEXT NOT NULL,
  "regime_prob" DOUBLE PRECISION,
  "hmm_state" BIGINT,
  "viterbi_path_json" TEXT,
  "features_json" TEXT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("date")
);

-- ── market_sentiment_snapshots ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "market_sentiment_snapshots" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "snapshot_at" TIMESTAMPTZ DEFAULT now(),
  "overall_score" DOUBLE PRECISION DEFAULT 0,
  "overall_label" TEXT DEFAULT 'Neutral',
  "bullish_count" BIGINT DEFAULT 0,
  "bearish_count" BIGINT DEFAULT 0,
  "neutral_count" BIGINT DEFAULT 0,
  "high_impact_count" BIGINT DEFAULT 0,
  "nifty_bias" TEXT DEFAULT 'Neutral',
  "nifty_support" DOUBLE PRECISION,
  "nifty_resistance" DOUBLE PRECISION,
  "nifty_last_close" DOUBLE PRECISION,
  "global_cue" TEXT DEFAULT 'Mixed',
  "global_score" DOUBLE PRECISION DEFAULT 0,
  "key_themes_json" TEXT,
  "source_count" BIGINT DEFAULT 0
);
CREATE INDEX idx_mss_at ON market_sentiment_snapshots(snapshot_at DESC);

-- ── mc_advance_decline ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_advance_decline" (
  "date" TEXT NOT NULL,
  "exchange" TEXT NOT NULL DEFAULT 'NSE',
  "advances" BIGINT,
  "declines" BIGINT,
  "unchanged" BIGINT,
  "adv_dec_ratio" DOUBLE PRECISION,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("date", "exchange")
);

-- ── mc_analyst_ratings ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_analyst_ratings" (
  "symbol" TEXT NOT NULL,
  "final_rating" TEXT,
  "analyst_count" BIGINT,
  "buy_count" BIGINT,
  "outperform_count" BIGINT,
  "hold_count" BIGINT,
  "underperform_count" BIGINT,
  "sell_count" BIGINT,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("symbol", "fetched_at")
);

-- ── mc_broker_reco ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_broker_reco" (
  "scid" TEXT NOT NULL,
  "stock_name" TEXT,
  "organization" TEXT NOT NULL,
  "recommend_flag" TEXT,
  "recommended_price" DOUBLE PRECISION,
  "target" DOUBLE PRECISION,
  "entry_date" TEXT,
  "recommend_date" TEXT,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("scid", "organization", "entry_date")
);

-- ── mc_chart_patterns ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_chart_patterns" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mcsymbol" TEXT NOT NULL,
  "symbol" TEXT,
  "pattern_id" BIGINT NOT NULL,
  "pattern_name" TEXT NOT NULL,
  "comment" TEXT,
  "time_frame" TEXT,
  "exchange" TEXT DEFAULT 'nse',
  "p_status" TEXT,
  "is_closed" TEXT DEFAULT 'N',
  "entry_price" DOUBLE PRECISION,
  "target_price" DOUBLE PRECISION,
  "stoploss_price" DOUBLE PRECISION,
  "target_return_pct" DOUBLE PRECISION,
  "stoploss_pct" DOUBLE PRECISION,
  "cmp" DOUBLE PRECISION,
  "metadata_json" TEXT,
  "end_date" TEXT,
  "analyst_name" TEXT,
  "analyst_image" TEXT,
  "fetched_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("mcsymbol", "pattern_id")
);
CREATE INDEX idx_mcp_symbol ON mc_chart_patterns(mcsymbol);
CREATE INDEX idx_mcp_nse_symbol ON mc_chart_patterns(symbol);
CREATE INDEX idx_mcp_pattern_id ON mc_chart_patterns(pattern_id);
CREATE INDEX idx_mcp_fetched ON mc_chart_patterns(fetched_at DESC);

-- ── mc_earnings_forecast ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_earnings_forecast" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "metric_type" TEXT NOT NULL,
  "high" DOUBLE PRECISION,
  "low" DOUBLE PRECISION,
  "avg" DOUBLE PRECISION,
  "actual" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "date", "metric_type")
);

-- ── mc_earnings_rapid ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_earnings_rapid" (
  "scid" TEXT NOT NULL,
  "sub_type" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "result_date" TEXT,
  "stock_name" TEXT,
  "ltp" DOUBLE PRECISION,
  "change_pct" DOUBLE PRECISION,
  "revenue_curr" DOUBLE PRECISION,
  "revenue_prev" DOUBLE PRECISION,
  "revenue_growth" DOUBLE PRECISION,
  "np_curr" DOUBLE PRECISION,
  "np_prev" DOUBLE PRECISION,
  "np_growth" DOUBLE PRECISION,
  "category_score" BIGINT,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("scid", "sub_type", "category")
);

-- ── mc_estimates_hits_misses ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_estimates_hits_misses" (
  "symbol" TEXT NOT NULL,
  "quarter" TEXT NOT NULL,
  "actual" DOUBLE PRECISION,
  "estimates" DOUBLE PRECISION,
  "surprise" DOUBLE PRECISION,
  "type" TEXT,
  PRIMARY KEY ("symbol", "quarter")
);

-- ── mc_general_metrics ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_general_metrics" (
  "symbol" TEXT NOT NULL,
  "source_api" TEXT NOT NULL,
  "metric_group" TEXT NOT NULL,
  "metric_name" TEXT NOT NULL,
  "metric_value_num" DOUBLE PRECISION,
  "metric_value_text" TEXT,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("symbol", "source_api", "metric_group", "metric_name", "fetched_at")
);

-- ── mc_price_forecast ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_price_forecast" (
  "symbol" TEXT NOT NULL,
  "high" DOUBLE PRECISION,
  "mean" DOUBLE PRECISION,
  "low" DOUBLE PRECISION,
  "fetched_at" TEXT NOT NULL,
  PRIMARY KEY ("symbol", "fetched_at")
);

-- ── mc_price_shockers ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_price_shockers" (
  "scid" TEXT,
  "stock_name" TEXT,
  "result_date" TEXT,
  "gain_since_result" DOUBLE PRECISION,
  "ltp" DOUBLE PRECISION,
  "change_pct" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("scid")
);

-- ── mc_seasonality_best_stocks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_seasonality_best_stocks" (
  "tab_type" TEXT NOT NULL,
  "sc_id" TEXT NOT NULL,
  "sc_fullname" TEXT,
  "year" BIGINT NOT NULL,
  "month" BIGINT NOT NULL,
  "avg_pct" DOUBLE PRECISION,
  "max_pct" DOUBLE PRECISION,
  "min_pct" DOUBLE PRECISION,
  "total_yr" DOUBLE PRECISION,
  "tot_yr" DOUBLE PRECISION,
  PRIMARY KEY ("tab_type", "sc_id", "year", "month")
);

-- ── mc_sector_earnings ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_sector_earnings" (
  "sector_name" TEXT,
  "market_cap" DOUBLE PRECISION,
  "rev_growth_yoy" DOUBLE PRECISION,
  "rev_growth_qoq" DOUBLE PRECISION,
  "np_growth_yoy" DOUBLE PRECISION,
  "np_growth_qoq" DOUBLE PRECISION,
  "gp_growth_yoy" DOUBLE PRECISION,
  "gp_growth_qoq" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("sector_name")
);

-- ── mc_stock_scans ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_stock_scans" (
  "symbol" TEXT NOT NULL,
  "scan_name" TEXT NOT NULL,
  "description" TEXT,
  PRIMARY KEY ("symbol", "scan_name")
);

-- ── mc_stock_vitals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mc_stock_vitals" (
  "symbol" TEXT NOT NULL,
  "metric_name" TEXT NOT NULL,
  "score" TEXT,
  "description" TEXT,
  PRIMARY KEY ("symbol", "metric_name")
);

-- ── mf_sector_allocation ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mf_sector_allocation" (
  "month" TEXT NOT NULL,
  "sector" TEXT NOT NULL,
  "aum_cr" DOUBLE PRECISION,
  "aum_pct" DOUBLE PRECISION,
  PRIMARY KEY ("month", "sector")
);

-- ── model_registry ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "model_registry" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" TEXT NOT NULL,
  "model_version" TEXT NOT NULL,
  "model_type" TEXT NOT NULL,
  "trained_at" TIMESTAMPTZ DEFAULT now(),
  "training_samples" BIGINT,
  "cv_roc_auc" DOUBLE PRECISION,
  "cv_accuracy" DOUBLE PRECISION,
  "test_roc_auc" DOUBLE PRECISION,
  "precision_score" DOUBLE PRECISION,
  "recall_score" DOUBLE PRECISION,
  "f1_score" DOUBLE PRECISION,
  "feature_count" BIGINT,
  "top_features_json" TEXT,
  "model_path" TEXT,
  "is_active" BIGINT DEFAULT 0,
  "horizon_days" BIGINT DEFAULT 15,
  "notes" TEXT
);

-- ── moneycontrol_screener_stocks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "moneycontrol_screener_stocks" (
  "scan_id" TEXT NOT NULL,
  "mcsymbol" TEXT NOT NULL,
  "stock_name" TEXT,
  "symbol" TEXT,
  "first_seen" TEXT,
  "last_seen" TEXT,
  PRIMARY KEY ("scan_id", "mcsymbol")
);
CREATE INDEX idx_mss_mcsymbol ON moneycontrol_screener_stocks(mcsymbol);
CREATE INDEX idx_mss_symbol ON moneycontrol_screener_stocks(symbol);

-- ── moneycontrol_screeners ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "moneycontrol_screeners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scan_id" TEXT NOT NULL,
  "cat_id" TEXT NOT NULL,
  "screener_name" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "is_positive" BIGINT DEFAULT 1,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("scan_id")
);
CREATE INDEX idx_mc_scan_id ON moneycontrol_screeners(scan_id);

-- ── news_articles ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "news_articles" (
  "id" TEXT,
  "title" TEXT NOT NULL,
  "summary" TEXT,
  "source" TEXT,
  "sentiment" TEXT,
  "category" TEXT,
  "url" TEXT,
  "symbols" TEXT,
  "timestamp" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

-- ── news_sentiment_items ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "news_sentiment_items" (
  "id" TEXT,
  "title" TEXT NOT NULL,
  "summary" TEXT,
  "source" TEXT NOT NULL,
  "source_type" TEXT DEFAULT 'INDIAN',
  "url" TEXT,
  "published_at" TIMESTAMPTZ,
  "fetched_at" TIMESTAMPTZ DEFAULT now(),
  "sentiment" TEXT DEFAULT 'NEUTRAL',
  "sentiment_score" DOUBLE PRECISION DEFAULT 0,
  "impact" TEXT DEFAULT 'LOW',
  "category" TEXT DEFAULT 'GENERAL',
  "symbols_json" TEXT,
  "sector" TEXT,
  "ai_scored" BIGINT DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX idx_nsi_published ON news_sentiment_items(published_at DESC);
CREATE INDEX idx_nsi_sentiment ON news_sentiment_items(sentiment);
CREATE INDEX idx_nsi_category  ON news_sentiment_items(category);
CREATE INDEX idx_nsi_fetched   ON news_sentiment_items(fetched_at DESC);
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_nsi_symbols_json_trgm ON news_sentiment_items USING GIN (symbols_json gin_trgm_ops);
CREATE INDEX idx_nsi_title_trgm        ON news_sentiment_items USING GIN (title gin_trgm_ops);

-- ── nse_stocks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "nse_stocks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "sector" TEXT,
  "industry" TEXT,
  "isin" TEXT,
  "listing_date" TEXT,
  "exchange" TEXT DEFAULT 'NSE',
  "status" TEXT DEFAULT 'ACTIVE',
  "market_cap" DOUBLE PRECISION,
  "pe_ratio" DOUBLE PRECISION,
  "dividend_yield" DOUBLE PRECISION,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  "mcsymbol" TEXT,
  "tlid" TEXT,
  "tlname" TEXT,
  "is_asm" BIGINT DEFAULT 0,
  "gsm_stage" BIGINT DEFAULT 0,
  "surveillance_updated_at" TEXT,
  "is_nifty50" BIGINT DEFAULT 0,
  "is_nifty100" BIGINT DEFAULT 0,
  "is_nifty200" BIGINT DEFAULT 0,
  "is_midcap150" BIGINT DEFAULT 0,
  "is_smallcap250" BIGINT DEFAULT 0,
  "index_flags_updated_at" TEXT,
  "fno_eligible" BIGINT DEFAULT 0,
  "lot_size" DOUBLE PRECISION,
  "fno_lot_updated_at" TEXT,
  UNIQUE ("symbol")
);
CREATE INDEX idx_nse_symbol ON nse_stocks(symbol);
CREATE INDEX idx_nse_sector ON nse_stocks(sector);
CREATE INDEX idx_nse_industry ON nse_stocks(industry);
CREATE INDEX idx_nse_status ON nse_stocks(status);

-- ── nt_fno_expiry ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "nt_fno_expiry" (
  "symbol" TEXT NOT NULL,
  "exchange" TEXT NOT NULL DEFAULT 'NSE',
  "expiry" TEXT NOT NULL,
  "lot_size" BIGINT,
  PRIMARY KEY ("symbol", "exchange", "expiry")
);

-- ── nt_index_change_oi ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "nt_index_change_oi" (
  "index_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "strike" DOUBLE PRECISION NOT NULL,
  "snap_time" TEXT NOT NULL,
  "index_close" DOUBLE PRECISION,
  "calls_change_oi" DOUBLE PRECISION,
  "calls_change_oi_val" DOUBLE PRECISION,
  "puts_change_oi" DOUBLE PRECISION,
  "puts_change_oi_val" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("index_name", "date", "expiry", "strike")
);
CREATE INDEX idx_nt_chg_oi ON nt_index_change_oi(index_name, date DESC);

-- ── nt_index_oi_eod ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "nt_index_oi_eod" (
  "index_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "strike" DOUBLE PRECISION NOT NULL,
  "snap_time" TEXT NOT NULL,
  "index_close" DOUBLE PRECISION,
  "calls_oi" DOUBLE PRECISION,
  "puts_oi" DOUBLE PRECISION,
  "calls_change_oi" DOUBLE PRECISION,
  "puts_change_oi" DOUBLE PRECISION,
  "calls_volume" DOUBLE PRECISION,
  "puts_volume" DOUBLE PRECISION,
  "calls_oi_value" DOUBLE PRECISION,
  "puts_oi_value" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("index_name", "date", "expiry", "strike")
);
CREATE INDEX idx_nt_oi_eod ON nt_index_oi_eod(index_name, date DESC);

-- ── nt_index_pcr_ts ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "nt_index_pcr_ts" (
  "index_name" TEXT NOT NULL,
  "ts" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "pcr" DOUBLE PRECISION,
  "volume_pcr" DOUBLE PRECISION,
  "change_oi_pcr" DOUBLE PRECISION,
  "index_close" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("index_name", "ts", "expiry")
);
CREATE INDEX idx_nt_pcr_ts ON nt_index_pcr_ts(index_name, ts DESC);

-- ── order_book_snapshots ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "order_book_snapshots" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL,
  "total_buy_qty" BIGINT,
  "total_sell_qty" BIGINT,
  "bid_ask_spread" DOUBLE PRECISION,
  "vwap" DOUBLE PRECISION,
  "created_at" TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_ob_symbol_time ON order_book_snapshots(symbol, timestamp DESC);

-- ── preopen_snapshot ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "preopen_snapshot" (
  "snapshot_date" TEXT,
  "snapshot_time" TEXT,
  "gift_nifty" DOUBLE PRECISION,
  "gift_nifty_chg" DOUBLE PRECISION,
  "gift_nifty_pct" DOUBLE PRECISION,
  "dj_futures" DOUBLE PRECISION,
  "dj_futures_pct" DOUBLE PRECISION,
  "hang_seng_pct" DOUBLE PRECISION,
  "nikkei_pct" DOUBLE PRECISION,
  "nasdaq_pct" DOUBLE PRECISION,
  "asia_sentiment" DOUBLE PRECISION,
  "global_risk_score" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("snapshot_date")
);

-- ── preopen_stock_snapshot ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "preopen_stock_snapshot" (
  "symbol" TEXT NOT NULL,
  "snapshot_date" TEXT NOT NULL,
  "iep" DOUBLE PRECISION,
  "prev_close" DOUBLE PRECISION,
  "iep_gap_pct" DOUBLE PRECISION,
  "total_buy_qty" DOUBLE PRECISION,
  "total_sell_qty" DOUBLE PRECISION,
  "preopen_imbalance" DOUBLE PRECISION,
  "last_price" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("symbol", "snapshot_date")
);

-- ── proprietary_scores_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "proprietary_scores_history" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "score_type" TEXT NOT NULL,
  "score_value" DOUBLE PRECISION,
  "score_label" TEXT,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "date", "source", "score_type")
);

-- ── quant_scores ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "quant_scores" (
  "symbol" TEXT,
  "return_1m" DOUBLE PRECISION,
  "return_3m" DOUBLE PRECISION,
  "return_6m" DOUBLE PRECISION,
  "return_12m" DOUBLE PRECISION,
  "above_sma200" BIGINT,
  "sma200_distance_pct" DOUBLE PRECISION,
  "momentum_score" DOUBLE PRECISION,
  "annualized_vol" DOUBLE PRECISION,
  "sharpe_ratio" DOUBLE PRECISION,
  "max_drawdown_1y" DOUBLE PRECISION,
  "vol_rank" DOUBLE PRECISION,
  "sharpe_rank" DOUBLE PRECISION,
  "trailing_pe" DOUBLE PRECISION,
  "forward_pe" DOUBLE PRECISION,
  "debt_to_equity" DOUBLE PRECISION,
  "return_on_equity" DOUBLE PRECISION,
  "operating_margins" DOUBLE PRECISION,
  "revenue_growth" DOUBLE PRECISION,
  "piotroski_f_score" BIGINT,
  "valuation_score" DOUBLE PRECISION,
  "bullish_screener_count" BIGINT,
  "bearish_screener_count" BIGINT,
  "screener_category_breadth" BIGINT,
  "screener_net_score" DOUBLE PRECISION,
  "confluence_rank" DOUBLE PRECISION,
  "rank_momentum" DOUBLE PRECISION,
  "rank_quality" DOUBLE PRECISION,
  "rank_value" DOUBLE PRECISION,
  "rank_composite" DOUBLE PRECISION,
  "composite_class" TEXT,
  "ohlcv_days" BIGINT,
  "last_computed" TIMESTAMPTZ DEFAULT now(),
  "return_1w" DOUBLE PRECISION,
  "beta_1y" DOUBLE PRECISION,
  "beta_6m" DOUBLE PRECISION,
  "sortino_ratio" DOUBLE PRECISION,
  "var_95" DOUBLE PRECISION,
  "mf_quality_score" DOUBLE PRECISION,
  "mf_momentum_score" DOUBLE PRECISION,
  "mf_value_score" DOUBLE PRECISION,
  "mf_risk_adj_score" DOUBLE PRECISION,
  "mf_macro_score" DOUBLE PRECISION,
  "mf_composite_score" DOUBLE PRECISION,
  PRIMARY KEY ("symbol")
);
CREATE INDEX idx_qs_composite  ON quant_scores(rank_composite DESC);
CREATE INDEX idx_qs_momentum   ON quant_scores(rank_momentum DESC);
CREATE INDEX idx_qs_quality    ON quant_scores(rank_quality DESC);
CREATE INDEX idx_qs_value      ON quant_scores(rank_value DESC);
CREATE INDEX idx_qs_class      ON quant_scores(composite_class);

-- ── recommendation_log ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "recommendation_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "rec_type" TEXT NOT NULL,
  "signal_date" TEXT NOT NULL,
  "generated_at" TIMESTAMPTZ NOT NULL,
  "timeframe" TEXT,
  "entry_price" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "target_2" DOUBLE PRECISION,
  "target_3" DOUBLE PRECISION,
  "confidence_score" DOUBLE PRECISION,
  "signal_score" BIGINT,
  "nifty_regime" TEXT,
  "sector" TEXT,
  "signals_json" TEXT,
  "screener_score" DOUBLE PRECISION,
  "quant_score" DOUBLE PRECISION,
  "sentiment_score" DOUBLE PRECISION,
  "win_probability" DOUBLE PRECISION,
  "reasoning" TEXT,
  "source" TEXT DEFAULT 'platform',
  "status" TEXT DEFAULT 'ACTIVE',
  "actual_exit_price" DOUBLE PRECISION,
  "actual_return_pct" DOUBLE PRECISION,
  "outcome" TEXT,
  "resolved_at" TIMESTAMPTZ,
  "horizon_days" BIGINT DEFAULT 15
);
CREATE INDEX idx_rec_symbol ON recommendation_log(symbol, signal_date DESC);
CREATE INDEX idx_rec_outcome ON recommendation_log(outcome, signal_date DESC);
CREATE INDEX idx_rec_regime  ON recommendation_log(nifty_regime, signal_date DESC);
CREATE UNIQUE INDEX idx_rec_log_uniq
    ON recommendation_log(symbol, signal_date, timeframe, source);

-- ── rl_episodes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "rl_episodes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" TEXT NOT NULL,
  "state_key" TEXT NOT NULL,
  "action_taken" TEXT NOT NULL,
  "reward" DOUBLE PRECISION,
  "epsilon" DOUBLE PRECISION,
  "notes" TEXT
);
CREATE INDEX idx_rlepi_date ON rl_episodes(date DESC);

-- ── rl_q_table ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "rl_q_table" (
  "state_key" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "q_value" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  "visit_count" BIGINT NOT NULL DEFAULT 0,
  "last_updated" TEXT NOT NULL,
  PRIMARY KEY ("state_key", "action")
);

-- ── screener_appearances ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_appearances" (
  "screener_id" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "appeared_date" TIMESTAMPTZ NOT NULL,
  "exited_date" TIMESTAMPTZ,
  "return_5d" DOUBLE PRECISION,
  "return_10d" DOUBLE PRECISION,
  "return_20d" DOUBLE PRECISION,
  "return_60d" DOUBLE PRECISION,
  "return_120d" DOUBLE PRECISION,
  "nifty_ret_20d" DOUBLE PRECISION,
  "outcome_20d" TEXT,
  PRIMARY KEY ("screener_id", "symbol", "appeared_date")
);
CREATE INDEX idx_sa_date     ON screener_appearances(appeared_date);
CREATE INDEX idx_sa_screener ON screener_appearances(screener_id);
CREATE INDEX idx_scap_symbol ON screener_appearances(symbol, appeared_date DESC);

-- ── screener_catalog ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_catalog" (
  "screener_id" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "screener_name" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "subcategory" TEXT,
  "signal_bias" TEXT NOT NULL,
  "investment_horizon" TEXT,
  "confidence" DOUBLE PRECISION NOT NULL,
  "score_0_100" DOUBLE PRECISION,
  "tier" TEXT,
  "sub_mod" DOUBLE PRECISION,
  "horiz_mult" DOUBLE PRECISION,
  PRIMARY KEY ("screener_id", "source")
);

-- ── screener_history_log ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_history_log" (
  "symbol" TEXT NOT NULL,
  "screener_id" TEXT NOT NULL,
  "entry_date" TEXT NOT NULL,
  "exit_date" TEXT,
  "source" TEXT NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "screener_id", "entry_date")
);

-- ── screener_master ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_master" (
  "scan_id" TEXT,
  "name" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "inferred_sentiment" TEXT,
  "inferred_category" TEXT,
  "inferred_timeframe" TEXT DEFAULT 'long_term',
  "confidence" DOUBLE PRECISION,
  "weight_override" DOUBLE PRECISION,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  "signal_type_tag" TEXT DEFAULT 'OTHER',
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "subcategory" TEXT,
  "tier" TEXT,
  "category_confidence" DOUBLE PRECISION,
  "classified_by" TEXT,
  "stocks_synced_at" TEXT,
  PRIMARY KEY ("scan_id")
);
CREATE INDEX idx_screener_master_created_at ON screener_master(created_at DESC);

-- ── screener_performance_v2 ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_performance_v2" (
  "screener_id" TEXT,
  "source" TEXT NOT NULL,
  "total_appearances" BIGINT DEFAULT 0,
  "resolved_count" BIGINT DEFAULT 0,
  "wr_5d" DOUBLE PRECISION,
  "wr_10d" DOUBLE PRECISION,
  "wr_20d" DOUBLE PRECISION,
  "wr_60d" DOUBLE PRECISION,
  "wr_120d" DOUBLE PRECISION,
  "avg_ret_5d" DOUBLE PRECISION,
  "avg_ret_10d" DOUBLE PRECISION,
  "avg_ret_20d" DOUBLE PRECISION,
  "avg_ret_60d" DOUBLE PRECISION,
  "avg_ret_120d" DOUBLE PRECISION,
  "alpha_20d" DOUBLE PRECISION,
  "alpha_60d" DOUBLE PRECISION,
  "sharpe_20d" DOUBLE PRECISION,
  "max_drawdown" DOUBLE PRECISION,
  "median_ret_20d" DOUBLE PRECISION,
  "bayesian_score" DOUBLE PRECISION,
  "tier" TEXT,
  "data_source" TEXT,
  "last_computed" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("screener_id")
);

-- ── screener_reliability ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_reliability" (
  "scan_id" TEXT,
  "screener_name" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "total_signals" BIGINT DEFAULT 0,
  "wins_1d" BIGINT DEFAULT 0,
  "wins_3d" BIGINT DEFAULT 0,
  "wins_7d" BIGINT DEFAULT 0,
  "wins_14d" BIGINT DEFAULT 0,
  "wins_30d" BIGINT DEFAULT 0,
  "win_rate_1d" DOUBLE PRECISION DEFAULT 0,
  "win_rate_7d" DOUBLE PRECISION DEFAULT 0,
  "win_rate_30d" DOUBLE PRECISION DEFAULT 0,
  "avg_return_7d" DOUBLE PRECISION DEFAULT 0,
  "avg_return_30d" DOUBLE PRECISION DEFAULT 0,
  "max_drawdown" DOUBLE PRECISION DEFAULT 0,
  "avg_holding_days" DOUBLE PRECISION DEFAULT 0,
  "reliability_score" DOUBLE PRECISION DEFAULT 50,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  "win_rate_5d" DOUBLE PRECISION,
  "win_rate_10d" DOUBLE PRECISION,
  "win_rate_20d" DOUBLE PRECISION,
  "win_rate_60d" DOUBLE PRECISION,
  "win_rate_120d" DOUBLE PRECISION,
  PRIMARY KEY ("scan_id")
);
CREATE INDEX idx_sr_source   ON screener_reliability(source);

-- ── screener_runs ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_runs" (
  "run_id" TEXT,
  "screener_id" TEXT NOT NULL,
  "source" TEXT,
  "run_ts" TIMESTAMPTZ DEFAULT now(),
  "params_json" TEXT,
  "top_n" BIGINT DEFAULT 0,
  "raw_count" BIGINT DEFAULT 0,
  "records_json" TEXT,
  "status" TEXT DEFAULT 'COMPLETED',
  PRIMARY KEY ("run_id")
);
CREATE INDEX idx_sr_screener_id ON screener_runs(screener_id);
CREATE INDEX idx_sr_screener ON screener_runs(screener_id, run_ts DESC);
CREATE INDEX idx_sr_run_id   ON screener_runs(run_id);

-- ── screener_weight_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_weight_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "snapshot_at" TIMESTAMPTZ DEFAULT now(),
  "optimization_method" TEXT DEFAULT 'differential_evolution',
  "category_weights_json" TEXT,
  "source_weights_json" TEXT,
  "screener_overrides_json" TEXT,
  "baseline_win_rate" DOUBLE PRECISION,
  "optimized_win_rate" DOUBLE PRECISION,
  "improvement_pct" DOUBLE PRECISION,
  "training_samples" BIGINT,
  "notes" TEXT
);

-- ── signal_actions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_actions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "signal_id" BIGINT NOT NULL,
  "signal_source" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "user_id" TEXT,
  "action_type" TEXT NOT NULL,
  "executed_at" TIMESTAMPTZ NOT NULL,
  "quantity" BIGINT,
  "entry_price_rec" DOUBLE PRECISION,
  "entry_actual" DOUBLE PRECISION,
  "target_price_rec" DOUBLE PRECISION,
  "exit_price_actual" DOUBLE PRECISION,
  "exit_date" TIMESTAMPTZ,
  "pnl" DOUBLE PRECISION,
  "pnl_pct" DOUBLE PRECISION,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("signal_id", "user_id")
);
CREATE INDEX idx_sa_user_id ON signal_actions(user_id);
CREATE INDEX idx_sa_symbol ON signal_actions(symbol);
CREATE INDEX idx_sa_source ON signal_actions(signal_source);
CREATE INDEX idx_sa_executed_at ON signal_actions(executed_at DESC);

-- ── signal_excursions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_excursions" (
  "symbol" TEXT NOT NULL,
  "signal_date" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "entry_price" DOUBLE PRECISION NOT NULL,
  "mfe_pct" DOUBLE PRECISION,
  "mae_pct" DOUBLE PRECISION,
  "days_to_mfe" BIGINT,
  "days_to_mae" BIGINT,
  "mfe_before_mae" BIGINT,
  "trail_exit_pct" DOUBLE PRECISION,
  "trail_exit_day" BIGINT,
  "horizon_close_pct" DOUBLE PRECISION,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  "atr_pct" DOUBLE PRECISION,
  "tb_label" BIGINT,
  PRIMARY KEY ("symbol", "signal_date", "horizon_days")
);
CREATE INDEX idx_sexc_date ON signal_excursions(signal_date DESC);
CREATE INDEX idx_sexc_sym  ON signal_excursions(symbol);

-- ── signal_outcomes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_outcomes" (
  "symbol" TEXT NOT NULL,
  "signal_date" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "entry_price" DOUBLE PRECISION NOT NULL,
  "check_date" TEXT,
  "exit_price" DOUBLE PRECISION,
  "return_pct" DOUBLE PRECISION,
  "outcome" TEXT,
  "signal_score" BIGINT,
  "signals_json" TEXT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  "max_return_pct" DOUBLE PRECISION,
  -- label_definition ('terminal_pct2' | 'path_barrier' | 'unknown') / is_suspect were
  -- previously added only at runtime by data_integrity_repair.py's ALTER TABLE ... ADD
  -- COLUMN IF NOT EXISTS -- absent here, a fresh bootstrap or DR restore would silently lose
  -- them even though they already exist on the live table. Schema catch-up, 2026-08.
  "label_definition" TEXT,
  "is_suspect" SMALLINT DEFAULT 0,
  PRIMARY KEY ("symbol", "signal_date", "horizon_days")
);
CREATE INDEX idx_sout_date    ON signal_outcomes(signal_date DESC);
CREATE INDEX idx_sout_outcome ON signal_outcomes(outcome);
CREATE INDEX idx_sout_sym     ON signal_outcomes(symbol);
CREATE INDEX idx_so_label     ON signal_outcomes(label_definition);

-- ── signal_portfolio_correlation ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_portfolio_correlation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "signal_id" BIGINT NOT NULL,
  "portfolio_symbol" TEXT NOT NULL,
  "signal_symbol" TEXT NOT NULL,
  "weight" DOUBLE PRECISION,
  "correlation_score" DOUBLE PRECISION,
  "co_movement_pct" DOUBLE PRECISION,
  "hedge_potential" BIGINT,
  "momentum_alignment" BIGINT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("signal_id", "portfolio_symbol")
);
CREATE INDEX idx_spc_portfolio_symbol ON signal_portfolio_correlation(portfolio_symbol);
CREATE INDEX idx_spc_correlation_score ON signal_portfolio_correlation(correlation_score DESC);
CREATE INDEX idx_spc_hedge ON signal_portfolio_correlation(hedge_potential);

-- ── signal_source_weights ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_source_weights" (
  "signal_source" TEXT NOT NULL,
  "regime" TEXT NOT NULL,
  "sector" TEXT DEFAULT 'OTHER',
  "win_rate" DOUBLE PRECISION,
  "avg_return_pct" DOUBLE PRECISION,
  "total_signals" BIGINT DEFAULT 0,
  "total_wins" BIGINT DEFAULT 0,
  "total_losses" BIGINT DEFAULT 0,
  "avg_sharpe_ratio" DOUBLE PRECISION,
  "weight_multiplier" DOUBLE PRECISION DEFAULT 1.0,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("signal_source", "regime", "sector")
);
CREATE INDEX idx_source_weights_win_rate ON signal_source_weights(win_rate DESC);
CREATE INDEX idx_source_weights_sector ON signal_source_weights(sector);

-- ── signal_type_stats ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_type_stats" (
  "signal_type" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "market_regime" TEXT NOT NULL DEFAULT 'ALL',
  "total_occurrences" BIGINT DEFAULT 0,
  "win_count" BIGINT DEFAULT 0,
  "avg_return_pct" DOUBLE PRECISION,
  "median_return_pct" DOUBLE PRECISION,
  "win_rate" DOUBLE PRECISION,
  "last_computed" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("signal_type", "horizon_days", "market_regime")
);

-- ── signal_type_stats_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_type_stats_history" (
  "snapshot_date" TEXT NOT NULL,
  "signal_type" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "market_regime" TEXT NOT NULL DEFAULT 'ALL',
  "total_occurrences" BIGINT DEFAULT 0,
  "win_count" BIGINT DEFAULT 0,
  "avg_return_pct" DOUBLE PRECISION,
  "median_return_pct" DOUBLE PRECISION,
  "win_rate" DOUBLE PRECISION,
  PRIMARY KEY ("snapshot_date", "signal_type", "horizon_days", "market_regime")
);
CREATE INDEX idx_sts_hist_date ON signal_type_stats_history(snapshot_date DESC);

-- ── signal_type_weights ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_type_weights" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "signal_type" TEXT NOT NULL,
  "regime" TEXT NOT NULL,
  "sector" TEXT NOT NULL DEFAULT 'ALL',
  "weight" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "sample_count" BIGINT NOT NULL DEFAULT 0,
  "last_updated" TEXT NOT NULL,
  UNIQUE ("signal_type", "regime", "sector")
);
CREATE INDEX idx_stw_key ON signal_type_weights(signal_type, regime, sector);

-- ── signal_type_weights_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "signal_type_weights_history" (
  "snapshot_date" TEXT NOT NULL,
  "signal_type" TEXT NOT NULL,
  "regime" TEXT NOT NULL,
  "sector" TEXT NOT NULL DEFAULT 'ALL',
  "weight" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "sample_count" BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("snapshot_date", "signal_type", "regime", "sector")
);
CREATE INDEX idx_stw_hist_date ON signal_type_weights_history(snapshot_date DESC);

-- ── so_option_chain ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "so_option_chain" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "strike" DOUBLE PRECISION NOT NULL,
  "ce_price" DOUBLE PRECISION,
  "ce_volume" DOUBLE PRECISION,
  "ce_oi" DOUBLE PRECISION,
  "ce_oi_chg_pct" DOUBLE PRECISION,
  "ce_iv" DOUBLE PRECISION,
  "ce_iv_chg" DOUBLE PRECISION,
  "ce_delta" DOUBLE PRECISION,
  "ce_gamma" DOUBLE PRECISION,
  "ce_theta" DOUBLE PRECISION,
  "ce_vega" DOUBLE PRECISION,
  "ce_rho" DOUBLE PRECISION,
  "ce_buildup" TEXT,
  "pe_price" DOUBLE PRECISION,
  "pe_volume" DOUBLE PRECISION,
  "pe_oi" DOUBLE PRECISION,
  "pe_oi_chg_pct" DOUBLE PRECISION,
  "pe_iv" DOUBLE PRECISION,
  "pe_iv_chg" DOUBLE PRECISION,
  "pe_delta" DOUBLE PRECISION,
  "pe_gamma" DOUBLE PRECISION,
  "pe_theta" DOUBLE PRECISION,
  "pe_vega" DOUBLE PRECISION,
  "pe_rho" DOUBLE PRECISION,
  "pe_buildup" TEXT,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("symbol", "date", "expiry", "strike")
);
CREATE INDEX idx_soc_sym_date ON so_option_chain(symbol, date DESC);

-- ── so_stock_oi_summary ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "so_stock_oi_summary" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "max_pain" DOUBLE PRECISION,
  "atm" DOUBLE PRECISION,
  "mwpl" DOUBLE PRECISION,
  "iv_call" DOUBLE PRECISION,
  "iv_put" DOUBLE PRECISION,
  "pcr" DOUBLE PRECISION,
  "fut_price" DOUBLE PRECISION,
  "fut_oi" DOUBLE PRECISION,
  "fut_oi_chg" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("symbol", "date", "expiry")
);

-- ── stock_delivery_data ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_delivery_data" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "delivery_pct" DOUBLE PRECISION,
  "delivery_qty" BIGINT,
  "traded_qty" BIGINT,
  "trades" BIGINT,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "date")
);

-- ── stock_earnings_beats ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_earnings_beats" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "quarter_date" TEXT NOT NULL,
  "period_type" TEXT NOT NULL DEFAULT 'quarterly',
  "beat_type" TEXT NOT NULL,
  "beat_score" BIGINT NOT NULL DEFAULT 0,
  "eps_actual" DOUBLE PRECISION,
  "eps_avg" DOUBLE PRECISION,
  "eps_high" DOUBLE PRECISION,
  "eps_low" DOUBLE PRECISION,
  "surprise_pct" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  UNIQUE ("symbol", "quarter_date")
);
CREATE INDEX idx_seb_symbol ON stock_earnings_beats(symbol);
CREATE INDEX idx_seb_quarter ON stock_earnings_beats(quarter_date);

-- ── stock_earnings_dates ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_earnings_dates" (
  "scid" TEXT NOT NULL,
  "result_date" TEXT NOT NULL,
  "stock_name" TEXT,
  "result_type" TEXT,
  "result_time" TEXT,
  "market_cap" DOUBLE PRECISION,
  "exchange" TEXT,
  "fetched_at" TEXT DEFAULT now(),
  PRIMARY KEY ("scid", "result_date")
);

-- ── stock_factor_breakdown ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_factor_breakdown" (
  "symbol" TEXT NOT NULL,
  "timeframe" TEXT NOT NULL DEFAULT 'long_term',
  "technical" DOUBLE PRECISION DEFAULT 0,
  "fundamental" DOUBLE PRECISION DEFAULT 0,
  "momentum" DOUBLE PRECISION DEFAULT 0,
  "valuation" DOUBLE PRECISION DEFAULT 0,
  "delivery" DOUBLE PRECISION DEFAULT 0,
  "news" DOUBLE PRECISION DEFAULT 0,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "timeframe")
);
CREATE UNIQUE INDEX idx_sfb_uniq
    ON stock_factor_breakdown(symbol, timeframe);

-- ── stock_fundamentals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_fundamentals" (
  "symbol" TEXT,
  "trailing_pe" DOUBLE PRECISION,
  "forward_pe" DOUBLE PRECISION,
  "price_to_book" DOUBLE PRECISION,
  "book_value" DOUBLE PRECISION,
  "earnings_yield" DOUBLE PRECISION,
  "eps_ttm" DOUBLE PRECISION,
  "eps_forward" DOUBLE PRECISION,
  "market_cap" DOUBLE PRECISION,
  "shares_outstanding" BIGINT,
  "fifty_two_week_high" DOUBLE PRECISION,
  "fifty_two_week_low" DOUBLE PRECISION,
  "fifty_two_week_change_pct" DOUBLE PRECISION,
  "sma200" DOUBLE PRECISION,
  "price_vs_sma200_pct" DOUBLE PRECISION,
  "avg_volume_3m" BIGINT,
  "dividend_yield" DOUBLE PRECISION,
  "analyst_rating" TEXT,
  "debt_to_equity" DOUBLE PRECISION,
  "return_on_equity" DOUBLE PRECISION,
  "revenue_growth" DOUBLE PRECISION,
  "earnings_growth" DOUBLE PRECISION,
  "operating_margins" DOUBLE PRECISION,
  "current_ratio" DOUBLE PRECISION,
  "piotroski_f_score" BIGINT,
  "phase1_synced_at" TIMESTAMPTZ,
  "phase2_synced_at" TIMESTAMPTZ,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  PRIMARY KEY ("symbol")
);
CREATE INDEX idx_sf_pe ON stock_fundamentals(trailing_pe);
CREATE INDEX idx_sf_mktcap ON stock_fundamentals(market_cap);
CREATE INDEX idx_sf_roe ON stock_fundamentals(return_on_equity);

-- ── stock_ohlcv ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_ohlcv" (
  "symbol" TEXT NOT NULL,
  "date" DATE NOT NULL,
  "open" DOUBLE PRECISION,
  "high" DOUBLE PRECISION,
  "low" DOUBLE PRECISION,
  "close" DOUBLE PRECISION,
  "volume" BIGINT,
  "is_suspect" BIGINT DEFAULT 0,
  PRIMARY KEY ("symbol", "date")
);
CREATE INDEX idx_stock_ohlcv_date ON stock_ohlcv(date DESC);
CREATE INDEX idx_stock_ohlcv_sym_date ON stock_ohlcv(symbol, date DESC);

-- ── stock_option_features ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_option_features" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT,
  "spot" DOUBLE PRECISION,
  "atm_strike" DOUBLE PRECISION,
  "atm_call_ltp" DOUBLE PRECISION,
  "atm_put_ltp" DOUBLE PRECISION,
  "expected_move_pct" DOUBLE PRECISION,
  "total_call_oi" DOUBLE PRECISION,
  "total_put_oi" DOUBLE PRECISION,
  "gex_proxy" DOUBLE PRECISION,
  "fetched_at" TEXT DEFAULT now(),
  "atm_iv" DOUBLE PRECISION,
  "next_expiry_iv" DOUBLE PRECISION,
  "iv_term_slope" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "date")
);

-- ── stock_options_oi ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_options_oi" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "expiry" TEXT NOT NULL,
  "call_oi" BIGINT DEFAULT 0,
  "put_oi" BIGINT DEFAULT 0,
  "pcr" DOUBLE PRECISION,
  "total_call_oi" BIGINT DEFAULT 0,
  "total_put_oi" BIGINT DEFAULT 0,
  "market_pcr" DOUBLE PRECISION,
  "fetched_at" TIMESTAMPTZ DEFAULT now(),
  "atm_iv" DOUBLE PRECISION,
  "iv_skew" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "date", "expiry")
);
CREATE INDEX idx_options_sym_date ON stock_options_oi(symbol, date DESC);
CREATE INDEX idx_soo_date ON stock_options_oi(date DESC);

-- ── stock_scores ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "stock_scores" (
  "symbol" TEXT NOT NULL,
  "timeframe" TEXT NOT NULL,
  "score" DOUBLE PRECISION,
  "confidence" DOUBLE PRECISION,
  "classification" TEXT,
  "top_domain" TEXT,
  "positive_count" BIGINT,
  "negative_count" BIGINT,
  "reasons" TEXT,
  "last_updated" TEXT,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  PRIMARY KEY ("symbol", "timeframe")
);
CREATE INDEX idx_ss_score ON stock_scores(score);
CREATE INDEX idx_ss_class ON stock_scores(classification);
CREATE INDEX idx_ss_timeframe ON stock_scores(timeframe);
CREATE INDEX idx_stock_scores_symbol ON stock_scores(symbol);
CREATE INDEX idx_stock_scores_created_at ON stock_scores(created_at DESC);

-- ── strategy_performance ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "strategy_performance" (
  "perf_key" TEXT NOT NULL,
  "strategy_name" TEXT NOT NULL,
  "segment" TEXT NOT NULL,
  "segment_value" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "market_regime" TEXT NOT NULL DEFAULT 'ALL',
  "total_signals" BIGINT DEFAULT 0,
  "win_count" BIGINT DEFAULT 0,
  "loss_count" BIGINT DEFAULT 0,
  "neutral_count" BIGINT DEFAULT 0,
  "win_rate" DOUBLE PRECISION,
  "avg_return_pct" DOUBLE PRECISION,
  "median_return_pct" DOUBLE PRECISION,
  "avg_win_pct" DOUBLE PRECISION,
  "avg_loss_pct" DOUBLE PRECISION,
  "profit_factor" DOUBLE PRECISION,
  "sharpe_ratio" DOUBLE PRECISION,
  "max_drawdown_pct" DOUBLE PRECISION,
  "alpha_vs_nifty" DOUBLE PRECISION,
  "signal_decay_halflife_days" DOUBLE PRECISION,
  "false_positive_rate" DOUBLE PRECISION,
  "best_sector" TEXT,
  "worst_sector" TEXT,
  "last_computed" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("perf_key", "horizon_days", "market_regime")
);
CREATE INDEX idx_perfkey ON strategy_performance(strategy_name, horizon_days);

-- technical_analysis_signals folded into unified_signals (signal_source='technical'),
-- Cluster B-lite, 2026-08 -- see migration 074_drop_technical_analysis_signals in db.ts.

-- ── technical_composite_scores ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "technical_composite_scores" (
  "symbol" TEXT,
  "trend_score" DOUBLE PRECISION,
  "momentum_score" DOUBLE PRECISION,
  "oscillator_score" DOUBLE PRECISION,
  "volume_score" DOUBLE PRECISION,
  "trend_strength_score" DOUBLE PRECISION,
  "candlestick_score" DOUBLE PRECISION,
  "support_resistance_score" DOUBLE PRECISION,
  "risk_score" DOUBLE PRECISION,
  "composite_score" DOUBLE PRECISION,
  "bullish_flags" TEXT,
  "bearish_flags" TEXT,
  "ai_insight" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol")
);
CREATE INDEX idx_tcs_composite ON technical_composite_scores(composite_score DESC);

-- ── technical_scans ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "technical_scans" (
  "symbol" TEXT,
  "data" TEXT,
  "timestamp" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol")
);

-- ── technical_signals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "technical_signals" (
  "symbol" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "signals_json" TEXT,
  "signal_score" BIGINT DEFAULT 0,
  "rsi" DOUBLE PRECISION,
  "sma50" DOUBLE PRECISION,
  "sma200" DOUBLE PRECISION,
  "macd" DOUBLE PRECISION,
  "macd_signal" DOUBLE PRECISION,
  "bb_width" DOUBLE PRECISION,
  "volume_ratio" DOUBLE PRECISION,
  "above_sma200" BIGINT DEFAULT 0,
  "cmp" DOUBLE PRECISION,
  "change_pct" DOUBLE PRECISION,
  "ai_insight" TEXT,
  "entry_zone" TEXT,
  "stop_loss" TEXT,
  "targets" TEXT,
  "setup_quality" TEXT,
  "time_horizon" TEXT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  "adx" DOUBLE PRECISION,
  "nifty_regime" TEXT,
  "delivery_pct" DOUBLE PRECISION,
  "fii_3d_net" DOUBLE PRECISION,
  "win_probability" DOUBLE PRECISION,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "news_sentiment_score" DOUBLE PRECISION,
  "pcr_oi" DOUBLE PRECISION DEFAULT 1.0,
  "pcr_vol" DOUBLE PRECISION DEFAULT 1.0,
  "fii_10d_net" DOUBLE PRECISION DEFAULT 0,
  "dii_3d_net" DOUBLE PRECISION DEFAULT 0,
  "sector_ret_5d" DOUBLE PRECISION DEFAULT 0,
  "sector_ret_21d" DOUBLE PRECISION DEFAULT 0,
  "calibrated_win_probability" DOUBLE PRECISION,
  "iv_rank" DOUBLE PRECISION,
  "iv_skew" DOUBLE PRECISION,
  "rs_rank_21d" DOUBLE PRECISION,
  "rs_rank_63d" DOUBLE PRECISION,
  "insider_buy_pct_90d" DOUBLE PRECISION,
  "opening_range_break" DOUBLE PRECISION,
  "vwap_deviation_pct" DOUBLE PRECISION,
  "first_hour_vol_share" DOUBLE PRECISION,
  "cs_score" DOUBLE PRECISION,
  "avwap_deviation_pct" DOUBLE PRECISION,
  "oi_net_change_pct" DOUBLE PRECISION,
  "eps_beat_last_q" BIGINT,
  "eps_beat_streak_4q" BIGINT,
  "eps_miss_streak_4q" BIGINT,
  "eps_surprise_last_yr" DOUBLE PRECISION,
  "eps_estimate_dispersion" DOUBLE PRECISION,
  "rollover_pct" DOUBLE PRECISION,
  "cost_of_carry_ann" DOUBLE PRECISION,
  "mf_holding_pct" DOUBLE PRECISION,
  "mf_fund_count" BIGINT,
  "mf_chg_vs_prev" DOUBLE PRECISION,
  "sector_global_corr_21d" DOUBLE PRECISION,
  "sector_benchmark" TEXT,
  "block_deal_net_qty" BIGINT,
  "block_deal_value_cr" DOUBLE PRECISION,
  "eps_ttm" DOUBLE PRECISION,
  "eps_growth_yoy" DOUBLE PRECISION,
  "eps_growth_qoq" DOUBLE PRECISION,
  "eps_acceleration" DOUBLE PRECISION,
  "pe_ttm" DOUBLE PRECISION,
  "dvm_durability" BIGINT,
  "dvm_valuation" BIGINT,
  "dvm_momentum" BIGINT,
  "pe_pct_rank_252d" DOUBLE PRECISION,
  "pe_vs_median_1yr" DOUBLE PRECISION,
  "pb_pct_rank_252d" DOUBLE PRECISION,
  "div_yield_ttm" DOUBLE PRECISION,
  "ma_bull_frac" DOUBLE PRECISION,
  "osc_bull_frac" DOUBLE PRECISION,
  "adx_tl" DOUBLE PRECISION,
  "atr_pct_tl" DOUBLE PRECISION,
  "mfi_tl" DOUBLE PRECISION,
  "pivot_dist_pct_tl" DOUBLE PRECISION,
  "delivery_avg_1m_tl" DOUBLE PRECISION,
  "beta_1y_tl" DOUBLE PRECISION,
  "ret_1m_tl" DOUBLE PRECISION,
  "ret_3m_tl" DOUBLE PRECISION,
  "ret_6m_tl" DOUBLE PRECISION,
  "ret_1y_tl" DOUBLE PRECISION,
  "analyst_upside_pct" DOUBLE PRECISION,
  "analyst_count" BIGINT,
  "analyst_buy_pct" DOUBLE PRECISION,
  "roe_annual" DOUBLE PRECISION,
  "roce_annual" DOUBLE PRECISION,
  "ebitda_margin" DOUBLE PRECISION,
  "np_margin" DOUBLE PRECISION,
  "promoter_pct" DOUBLE PRECISION,
  "fii_pct" DOUBLE PRECISION,
  "pledge_pct" DOUBLE PRECISION,
  "rev_growth_yoy_q" DOUBLE PRECISION,
  "np_growth_yoy_q" DOUBLE PRECISION,
  "days_since_dividend" BIGINT,
  "last_dividend_amt" DOUBLE PRECISION,
  "mc_52w_high_dist_pct" DOUBLE PRECISION,
  "mc_52w_low_dist_pct" DOUBLE PRECISION,
  "mc_days_from_52wh" BIGINT,
  "mc_cagr_3y" DOUBLE PRECISION,
  "mc_cagr_5y" DOUBLE PRECISION,
  "mc_ind_pe" DOUBLE PRECISION,
  "mc_pe_vs_ind" DOUBLE PRECISION,
  "mc_consensus_pe" DOUBLE PRECISION,
  "mc_ma50_dist_pct" DOUBLE PRECISION,
  "mc_ma200_dist_pct" DOUBLE PRECISION,
  "mc_del_pct_20d" DOUBLE PRECISION,
  "mc_vol_ratio" DOUBLE PRECISION,
  "mc_circuit_dist_pct" DOUBLE PRECISION,
  "mc_cp_bull_count" BIGINT,
  "mc_cp_bear_count" BIGINT,
  "mc_cp_net_score" BIGINT,
  "mc_cp_avg_target_pct" DOUBLE PRECISION,
  "tl_vs_nifty_1m" DOUBLE PRECISION,
  "tl_vs_nifty_3m" DOUBLE PRECISION,
  "tl_vs_nifty_6m" DOUBLE PRECISION,
  "tl_vs_ind_1m" DOUBLE PRECISION,
  "tl_vs_ind_3m" DOUBLE PRECISION,
  "tl_seasonal_month_5y" DOUBLE PRECISION,
  "tl_dist_3m_high_pct" DOUBLE PRECISION,
  "tl_dist_3m_low_pct" DOUBLE PRECISION,
  "mc_cagr_10y" DOUBLE PRECISION,
  "mc_consensus_pb" DOUBLE PRECISION,
  "mc_ma30_dist_pct" DOUBLE PRECISION,
  "mc_ma150_dist_pct" DOUBLE PRECISION,
  "mc_del_pct_3d" DOUBLE PRECISION,
  "mc_del_pct_5d" DOUBLE PRECISION,
  "mc_del_acceleration" DOUBLE PRECISION,
  "mc_fno_eligible" BIGINT,
  "mc_3d_return" DOUBLE PRECISION,
  "mc_ytd_return" DOUBLE PRECISION,
  "mc_price_cash" DOUBLE PRECISION,
  "mc_consensus_eps" DOUBLE PRECISION,
  "mc_eps_vs_cons" DOUBLE PRECISION,
  "mc_pe_fwd_discount" DOUBLE PRECISION,
  "nt_max_pain_dist_pct" DOUBLE PRECISION,
  "nt_oi_direction" DOUBLE PRECISION,
  "nt_pcr" DOUBLE PRECISION,
  "nt_option_volume_log" DOUBLE PRECISION,
  "days_to_next_results" BIGINT,
  "earnings_category_yoy" BIGINT,
  "earnings_category_qoq" BIGINT,
  "earnings_np_growth_yoy" DOUBLE PRECISION,
  "earnings_np_growth_qoq" DOUBLE PRECISION,
  "earnings_shocker_flag" BIGINT,
  "earnings_shocker_gain" DOUBLE PRECISION,
  "mc_broker_buy_7d" BIGINT,
  "mc_broker_sell_7d" BIGINT,
  "mc_broker_upside" DOUBLE PRECISION,
  "hv_10d" DOUBLE PRECISION,
  "hv_20d" DOUBLE PRECISION,
  "hv_30d" DOUBLE PRECISION,
  "hv_60d" DOUBLE PRECISION,
  "iv_hv_ratio" DOUBLE PRECISION,
  "eps_revision_3m_pct" DOUBLE PRECISION,
  "target_revision_3m_pct" DOUBLE PRECISION,
  "analyst_count_chg" BIGINT,
  "rs_vs_sector_21d" DOUBLE PRECISION,
  "rs_vs_sector_63d" DOUBLE PRECISION,
  "asm_flag" BIGINT DEFAULT 0,
  "gsm_stage" BIGINT DEFAULT 0,
  "crude_corr_90d" DOUBLE PRECISION,
  "gold_corr_90d" DOUBLE PRECISION,
  "dxy_corr_90d" DOUBLE PRECISION,
  "sp500_corr_90d" DOUBLE PRECISION,
  "is_nifty50" BIGINT DEFAULT 0,
  "is_nifty100" BIGINT DEFAULT 0,
  "is_nifty200" BIGINT DEFAULT 0,
  "is_midcap150" BIGINT DEFAULT 0,
  "is_smallcap250" BIGINT DEFAULT 0,
  "nifty_tier" BIGINT DEFAULT 0,
  "pledge_chg_90d" DOUBLE PRECISION,
  "iep_gap_pct" DOUBLE PRECISION,
  "preopen_imbalance" DOUBLE PRECISION,
  "expected_move_pct" DOUBLE PRECISION,
  "stock_gex_proxy" DOUBLE PRECISION,
  "eps_surprise_q1" DOUBLE PRECISION,
  "eps_surprise_q2" DOUBLE PRECISION,
  "eps_beat_streak" BIGINT,
  "eps_miss_after_streak" BIGINT DEFAULT 0,
  "rev_surprise_q1" DOUBLE PRECISION,
  "fcf_yield" DOUBLE PRECISION,
  "interest_coverage" DOUBLE PRECISION,
  "fcf_positive" BIGINT DEFAULT 0,
  "debt_coverage_risk" BIGINT DEFAULT 0,
  "delivery_trend_30d" DOUBLE PRECISION,
  "block_deal_flag" BIGINT DEFAULT 0,
  "block_deal_direction" BIGINT DEFAULT 0,
  "short_interest_proxy" DOUBLE PRECISION,
  "promoter_buy_90d_cr" DOUBLE PRECISION,
  "promoter_sell_90d_cr" DOUBLE PRECISION,
  "promoter_net_90d" DOUBLE PRECISION,
  "insider_buy_flag" BIGINT DEFAULT 0,
  "insider_sell_flag" BIGINT DEFAULT 0,
  "rating_upgrade_180d" BIGINT DEFAULT 0,
  "rating_downgrade_180d" BIGINT DEFAULT 0,
  "days_since_upgrade" BIGINT,
  "mf_sector_flow_pct" DOUBLE PRECISION,
  "receivables_days_ttm" DOUBLE PRECISION,
  "ccc_ttm" DOUBLE PRECISION,
  "ccc_trend" DOUBLE PRECISION,
  "wc_deteriorating" BIGINT DEFAULT 0,
  "wc_improving" BIGINT DEFAULT 0,
  "breakout_probability" DOUBLE PRECISION,
  "mc_bullish_scan_count" BIGINT,
  "mc_scan_52w_high" BIGINT,
  "mc_scan_squeeze_bo" BIGINT,
  "mc_tech_rating" BIGINT,
  "mf_funds_adding" BIGINT,
  "mf_funds_trimming" BIGINT,
  "mf_add_trim_ratio" DOUBLE PRECISION,
  "mf_pct" DOUBLE PRECISION,
  "promoter_chg_qoq" DOUBLE PRECISION,
  "fii_chg_qoq" DOUBLE PRECISION,
  "mf_chg_qoq" DOUBLE PRECISION,
  "pledge_chg_qoq" DOUBLE PRECISION,
  "mf_avg_pct_assets" DOUBLE PRECISION,
  "mf_big_fund_flow" DOUBLE PRECISION,
  "mf_flow_vs_sector" DOUBLE PRECISION,
  "mf_flow_rank" DOUBLE PRECISION,
  "ext_fii_holding_pct" DOUBLE PRECISION,
  "ext_dii_holding_pct" DOUBLE PRECISION,
  "ext_fii_qoq_chg" DOUBLE PRECISION,
  "ext_dii_qoq_chg" DOUBLE PRECISION,
  "ext_t80_tech_score" DOUBLE PRECISION,
  "ext_t80_quality_rank" DOUBLE PRECISION,
  "ext_t80_valuation_rank" DOUBLE PRECISION,
  "ext_t80_financial_pts" DOUBLE PRECISION,
  "ext_mojo_quality_rank" DOUBLE PRECISION,
  "ext_mojo_valuation_rank" DOUBLE PRECISION,
  "ext_mojo_financial_pts" DOUBLE PRECISION,
  "ext_is_overall_score" DOUBLE PRECISION,
  "ext_is_percentile_rank" DOUBLE PRECISION,
  "ext_tt_score" DOUBLE PRECISION,
  "signal_type" TEXT,
  "fcf_yield_approx" DOUBLE PRECISION,
  "next_expiry_iv" DOUBLE PRECISION,
  "iv_term_slope" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "date")
);
CREATE INDEX idx_tsig_date  ON technical_signals(date DESC);
CREATE INDEX idx_tsig_score ON technical_signals(signal_score DESC);
CREATE INDEX idx_tsig_sym   ON technical_signals(symbol);
CREATE INDEX idx_technical_signals_symbol ON technical_signals(symbol);
CREATE INDEX idx_technical_signals_created_at ON technical_signals(created_at DESC);
CREATE INDEX idx_ts_cs_score
    ON technical_signals(cs_score) WHERE cs_score IS NOT NULL;

-- ── tick_data ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "tick_data" (
  "symbol" TEXT NOT NULL,
  "tick_time" TIMESTAMPTZ NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "bid" DOUBLE PRECISION,
  "ask" DOUBLE PRECISION,
  "volume" BIGINT,
  "volume_cum" BIGINT,
  PRIMARY KEY ("symbol", "tick_time")
);
CREATE INDEX idx_tick_symbol ON tick_data(symbol, tick_time DESC);
CREATE INDEX idx_tick_date ON tick_data(tick_time DESC);

-- ── timeframe_scores ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "timeframe_scores" (
  "symbol" TEXT NOT NULL,
  "timeframe" TEXT NOT NULL,
  "run_id" TEXT,
  "score" DOUBLE PRECISION,
  "confidence" DOUBLE PRECISION,
  "domains_json" TEXT,
  "reasons_json" TEXT,
  "suggested_holding_days" BIGINT,
  "stop_loss" DOUBLE PRECISION,
  "targets_json" TEXT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "timeframe", "run_id")
);
CREATE INDEX idx_ts_run_id ON timeframe_scores(run_id);
CREATE INDEX idx_ts_score    ON timeframe_scores(score DESC);

-- ── tl_financial_quality ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "tl_financial_quality" (
  "symbol" TEXT NOT NULL,
  "as_of_date" TEXT NOT NULL,
  "cfo_ttm" DOUBLE PRECISION,
  "capex_ttm" DOUBLE PRECISION,
  "fcf_ttm" DOUBLE PRECISION,
  "ebit_ttm" DOUBLE PRECISION,
  "interest_expense_ttm" DOUBLE PRECISION,
  "market_cap" DOUBLE PRECISION,
  "fcf_yield" DOUBLE PRECISION,
  "interest_coverage" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "as_of_date")
);

-- ── todos ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "todos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT DEFAULT 'PENDING',
  "category" TEXT DEFAULT 'IDEAS',
  "priority" TEXT DEFAULT 'MEDIUM',
  "createdAt" TIMESTAMPTZ DEFAULT now(),
  "updatedAt" TIMESTAMPTZ DEFAULT now()
);

-- ── trendlyne_checklist ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "trendlyne_checklist" (
  "symbol" TEXT,
  "score" DOUBLE PRECISION,
  "total" BIGINT,
  "yes_count" BIGINT,
  "insight" TEXT,
  "checklist_data" TEXT,
  "fetched_at" TIMESTAMPTZ,
  PRIMARY KEY ("symbol")
);

-- ── trendlyne_screener_stocks ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "trendlyne_screener_stocks" (
  "screener_id" TEXT NOT NULL,
  "stock_id" TEXT NOT NULL,
  "symbol" TEXT,
  "first_seen" TEXT,
  "last_seen" TEXT,
  PRIMARY KEY ("screener_id", "stock_id")
);
CREATE INDEX idx_tss_stock_id ON trendlyne_screener_stocks(stock_id);
CREATE INDEX idx_tss_symbol ON trendlyne_screener_stocks(symbol);

-- ── trendlyne_screeners ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "trendlyne_screeners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screener_id" TEXT NOT NULL,
  "screener_name" TEXT NOT NULL,
  "screenpk" TEXT NOT NULL,
  "description" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  "sentiment" TEXT DEFAULT 'neutral',
  "category" TEXT DEFAULT 'technical',
  "timeframe" TEXT DEFAULT 'long_term',
  UNIQUE ("screener_id")
);
CREATE INDEX idx_screener_id ON trendlyne_screeners(screener_id);
CREATE INDEX idx_screenpk ON trendlyne_screeners(screenpk);

-- ── trendlyne_technical_snapshots ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "trendlyne_technical_snapshots" (
  "symbol" TEXT NOT NULL,
  "timeframe" TEXT NOT NULL,
  "data_json" TEXT NOT NULL,
  "last_updated" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol", "timeframe")
);

-- ── unified_recommendations ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "unified_recommendations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "computed_at" TEXT NOT NULL,
  "regime" TEXT NOT NULL,
  "unified_score" DOUBLE PRECISION NOT NULL,
  "conviction_level" TEXT NOT NULL,
  "screener_stock_score" DOUBLE PRECISION,
  "ml_score" DOUBLE PRECISION,
  "confluence_score" DOUBLE PRECISION,
  "technical_score" DOUBLE PRECISION,
  "dl_score" DOUBLE PRECISION,
  "avg_engine_track_record" DOUBLE PRECISION,
  "bullish_screener_count" BIGINT,
  "bearish_screener_count" BIGINT,
  "screener_names_json" TEXT,
  "fundamental_score" DOUBLE PRECISION,
  "entry_zone_low" DOUBLE PRECISION,
  "entry_zone_high" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "target_1" DOUBLE PRECISION,
  "target_2" DOUBLE PRECISION,
  "target_3" DOUBLE PRECISION,
  "risk_reward" DOUBLE PRECISION,
  "timeframe" TEXT,
  "sector" TEXT,
  "trade_reasoning" TEXT,
  "classification" TEXT,
  "position_size_pct" DOUBLE PRECISION,
  UNIQUE ("symbol", "computed_at")
);
CREATE INDEX idx_ur_date_score ON unified_recommendations(computed_at, unified_score DESC);
CREATE INDEX idx_ur_conviction  ON unified_recommendations(computed_at, conviction_level);

-- ── unified_signal_outcomes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "unified_signal_outcomes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unified_signal_id" BIGINT NOT NULL,
  "symbol" TEXT NOT NULL,
  "signal_date" TEXT NOT NULL,
  "signal_source" TEXT NOT NULL,
  "horizon_days" BIGINT NOT NULL,
  "entry_price" DOUBLE PRECISION NOT NULL,
  "entry_time" TIMESTAMPTZ NOT NULL,
  "check_date" TEXT,
  "exit_price" DOUBLE PRECISION,
  "exit_time" TIMESTAMPTZ,
  "return_pct" DOUBLE PRECISION,
  "intraday_max_return_pct" DOUBLE PRECISION,
  "intraday_min_return_pct" DOUBLE PRECISION,
  "outcome" TEXT,
  "exit_reason" TEXT,
  "signal_score" BIGINT,
  "computed_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("unified_signal_id", "horizon_days")
);
CREATE INDEX idx_uso_symbol_date ON unified_signal_outcomes(symbol, signal_date);
CREATE INDEX idx_uso_outcome ON unified_signal_outcomes(outcome);
CREATE INDEX idx_uso_source ON unified_signal_outcomes(signal_source);

-- ── unified_signals ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "unified_signals" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" TEXT NOT NULL,
  "signal_date" TIMESTAMPTZ DEFAULT now(),
  "signal_source" TEXT NOT NULL,
  "signal_type" TEXT NOT NULL,
  "entry_price" DOUBLE PRECISION,
  "target_price" DOUBLE PRECISION,
  "stop_loss" DOUBLE PRECISION,
  "confidence_score" DOUBLE PRECISION,
  "reasoning" TEXT,
  "technical_score" DOUBLE PRECISION,
  "quant_score" DOUBLE PRECISION,
  "ai_reasoning" TEXT,
  "status" TEXT DEFAULT 'ACTIVE',
  "signal_generated_at" TIMESTAMPTZ NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("symbol", "signal_source", "signal_type", "signal_date")
);
CREATE INDEX idx_us_symbol_date ON unified_signals(symbol, signal_date DESC);
CREATE INDEX idx_us_source ON unified_signals(signal_source);
CREATE INDEX idx_us_confidence ON unified_signals(confidence_score DESC);
CREATE INDEX idx_us_status ON unified_signals(status);
CREATE INDEX idx_unified_signals_date ON unified_signals(signal_date DESC);
CREATE UNIQUE INDEX idx_us_unique_key
    ON unified_signals(symbol, signal_source, signal_type, signal_date);

-- ── users ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT,
  "email" TEXT,
  "name" TEXT,
  "photoURL" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT now(),
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);
CREATE INDEX idx_users_created_at ON users(created_at DESC);

-- ── watchlist ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "watchlist" (
  "userId" TEXT NOT NULL,
  "symbol" TEXT NOT NULL,
  "addedAt" TIMESTAMPTZ DEFAULT now(),
  "price" DOUBLE PRECISION,
  "name" TEXT,
  "source" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("userId", "symbol")
);
CREATE INDEX idx_watchlist_created_at ON watchlist(created_at DESC);
CREATE INDEX idx_watchlist_userId ON watchlist("userId");

-- ── working_capital_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "working_capital_history" (
  "symbol" TEXT NOT NULL,
  "quarter" TEXT NOT NULL,
  "receivables_days" DOUBLE PRECISION,
  "inventory_days" DOUBLE PRECISION,
  "payables_days" DOUBLE PRECISION,
  "ccc" DOUBLE PRECISION,
  "revenue_qtr" DOUBLE PRECISION,
  "cogs_qtr" DOUBLE PRECISION,
  PRIMARY KEY ("symbol", "quarter")
);

-- ── xgboost_predictions ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "xgboost_predictions" (
  "symbol" TEXT,
  "prediction_date" TEXT NOT NULL,
  "xgboost_score" DOUBLE PRECISION,
  "signal" TEXT,
  "is_growth" BIGINT,
  "is_value" BIGINT,
  "is_quality" BIGINT,
  "is_breakout" BIGINT,
  "is_pullback" BIGINT,
  "feature_breakdown" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("symbol")
);
CREATE INDEX idx_xgb_score ON xgboost_predictions(xgboost_score DESC);


-- ── Timescale hypertables / compression / retention ──────────────────────
SELECT create_hypertable('confluence_signals', 'computed_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE, migrate_data => TRUE);
ALTER TABLE confluence_signals SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');
SELECT add_compression_policy('confluence_signals', INTERVAL '30 days', if_not_exists => TRUE);
SELECT add_retention_policy('confluence_signals', INTERVAL '90 days', if_not_exists => TRUE);
SELECT create_hypertable('feature_store', 'date', chunk_time_interval => INTERVAL '90 days', if_not_exists => TRUE, migrate_data => TRUE);
ALTER TABLE feature_store SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');
SELECT add_compression_policy('feature_store', INTERVAL '120 days', if_not_exists => TRUE);
SELECT create_hypertable('intraday_ohlcv', 'datetime', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE, migrate_data => TRUE);
ALTER TABLE intraday_ohlcv SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');
SELECT add_compression_policy('intraday_ohlcv', INTERVAL '30 days', if_not_exists => TRUE);
SELECT add_retention_policy('intraday_ohlcv', INTERVAL '365 days', if_not_exists => TRUE);
SELECT create_hypertable('macro_asset_prices', 'date', chunk_time_interval => INTERVAL '365 days', if_not_exists => TRUE, migrate_data => TRUE);
SELECT create_hypertable('stock_ohlcv', 'date', chunk_time_interval => INTERVAL '90 days', if_not_exists => TRUE, migrate_data => TRUE);
ALTER TABLE stock_ohlcv SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');
SELECT add_compression_policy('stock_ohlcv', INTERVAL '180 days', if_not_exists => TRUE);
SELECT create_hypertable('tick_data', 'tick_time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE, migrate_data => TRUE);
ALTER TABLE tick_data SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');
SELECT add_compression_policy('tick_data', INTERVAL '7 days', if_not_exists => TRUE);
SELECT add_retention_policy('tick_data', INTERVAL '30 days', if_not_exists => TRUE);
