"""db_compat-backed storage for the URL explorer (catalog + raw history)."""
from __future__ import annotations

import json
from db_compat import execute, query_all, query_one
from sql_translate import use_postgres

# db_compat's translate() rewrites query syntax (placeholders, date functions),
# not DDL type syntax — AUTOINCREMENT has no Postgres equivalent it can substitute,
# so each dialect's id-column type is spelled out explicitly here (same pattern as
# moneycontrol_fetcher.py's ensure_tables_exist).
_ID = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if use_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"

_DDL = [
    f"""CREATE TABLE IF NOT EXISTS url_endpoints (
        id {_ID},
        template TEXT UNIQUE NOT NULL,
        host TEXT, path_skeleton TEXT, param_keys TEXT,
        method TEXT DEFAULT 'GET', n_urls INTEGER DEFAULT 0,
        last_run_at TEXT, last_status TEXT)""",
    f"""CREATE TABLE IF NOT EXISTS url_params (
        id {_ID},
        endpoint_id INTEGER NOT NULL,
        name TEXT, location TEXT, inferred_type TEXT,
        is_variable INTEGER, distinct_count INTEGER, sample_values TEXT,
        UNIQUE(endpoint_id, location, name))""",
    f"""CREATE TABLE IF NOT EXISTS url_fetches (
        id {_ID},
        endpoint_id INTEGER NOT NULL,
        concrete_url TEXT, params_json TEXT,
        fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
        http_status INTEGER, latency_ms INTEGER, ok INTEGER,
        response_bytes INTEGER, raw_json TEXT, error TEXT)""",
    f"""CREATE TABLE IF NOT EXISTS url_fields (
        id {_ID},
        endpoint_id INTEGER NOT NULL, run_at TEXT,
        field_path TEXT, dtype TEXT, fill_rate REAL, cardinality INTEGER,
        num_min REAL, num_max REAL, num_mean REAL,
        universe_overlap_pct REAL, changed_vs_last INTEGER)""",
    f"""CREATE TABLE IF NOT EXISTS url_field_correlations (
        id {_ID},
        endpoint_id INTEGER NOT NULL, run_at TEXT,
        field_path TEXT, target TEXT, n INTEGER,
        pearson REAL, spearman REAL, ic REAL)""",
    "CREATE INDEX IF NOT EXISTS ix_url_fetches_ep ON url_fetches(endpoint_id, fetched_at)",
    "CREATE INDEX IF NOT EXISTS ix_url_fields_ep ON url_fields(endpoint_id, run_at)",
]


def ensure_schema() -> None:
    for ddl in _DDL:
        execute(ddl)


def upsert_endpoint(t) -> int:
    execute(
        """INSERT INTO url_endpoints (template, host, path_skeleton, param_keys, method, n_urls)
           VALUES (?, ?, ?, ?, ?, ?)
           ON CONFLICT(template) DO UPDATE SET
             host=excluded.host, path_skeleton=excluded.path_skeleton,
             param_keys=excluded.param_keys, n_urls=excluded.n_urls""",
        (t.template, t.host, t.path_skeleton, json.dumps(t.query_keys), t.method, len(t.urls)),
    )
    row = query_one("SELECT id FROM url_endpoints WHERE template = ?", (t.template,))
    return int(row["id"])


def upsert_params(endpoint_id: int, params) -> None:
    for p in params:
        execute(
            """INSERT INTO url_params (endpoint_id, name, location, inferred_type,
                 is_variable, distinct_count, sample_values)
               VALUES (?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT(endpoint_id, location, name) DO UPDATE SET
                 inferred_type=excluded.inferred_type, is_variable=excluded.is_variable,
                 distinct_count=excluded.distinct_count, sample_values=excluded.sample_values""",
            (endpoint_id, p.name, p.location, p.inferred_type,
             1 if p.is_variable else 0, p.distinct_count, json.dumps(p.sample_values)),
        )


def insert_fetch(endpoint_id, concrete_url, params_json, http_status,
                 latency_ms, ok, response_bytes, raw_json, error) -> int:
    execute(
        """INSERT INTO url_fetches (endpoint_id, concrete_url, params_json, http_status,
             latency_ms, ok, response_bytes, raw_json, error)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (endpoint_id, concrete_url, params_json, http_status, latency_ms,
         1 if ok else 0, response_bytes, raw_json, error),
    )
    row = query_one("SELECT MAX(id) AS id FROM url_fetches WHERE endpoint_id = ?", (endpoint_id,))
    return int(row["id"])


def insert_field(endpoint_id, run_at, p) -> None:
    execute(
        """INSERT INTO url_fields (endpoint_id, run_at, field_path, dtype, fill_rate,
             cardinality, num_min, num_max, num_mean, universe_overlap_pct, changed_vs_last)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (endpoint_id, run_at, p.field_path, p.dtype, p.fill_rate, p.cardinality,
         p.num_min, p.num_max, p.num_mean, p.universe_overlap_pct,
         1 if p.changed_vs_last else 0),
    )


def insert_correlation(endpoint_id, run_at, c) -> None:
    execute(
        """INSERT INTO url_field_correlations (endpoint_id, run_at, field_path, target, n,
             pearson, spearman, ic) VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        (endpoint_id, run_at, c.field_path, c.target, c.n, c.pearson, c.spearman, c.ic),
    )


def last_run_field_paths(endpoint_id: int) -> set[str]:
    rows = query_all(
        """SELECT DISTINCT field_path FROM url_fields
           WHERE endpoint_id = ? AND run_at = (
             SELECT MAX(run_at) FROM url_fields WHERE endpoint_id = ?)""",
        (endpoint_id, endpoint_id),
    )
    return {r["field_path"] for r in rows}
