"""db_compat-backed storage for the URL explorer (catalog + raw history)."""
from __future__ import annotations

import json
from datetime import datetime, timezone

from db_compat import execute, query_all, query_one
from sql_translate import use_postgres

# db_compat's translate() rewrites query syntax (placeholders, date functions),
# not DDL type syntax — AUTOINCREMENT has no Postgres equivalent it can substitute,
# so each dialect's id-column type is spelled out explicitly here (same pattern as
# moneycontrol_fetcher.py's ensure_tables_exist).
_ID = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if use_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"

_DDL = [
    f"""CREATE TABLE IF NOT EXISTS url_endpoints (
        id {_ID},
        template TEXT UNIQUE NOT NULL,
        host TEXT, path_skeleton TEXT, param_keys TEXT,
        method TEXT DEFAULT 'GET', n_urls INTEGER DEFAULT 0,
        last_run_at TEXT, last_status TEXT)""",
    f"""CREATE TABLE IF NOT EXISTS url_params (
        id {_ID},
        endpoint_id INTEGER NOT NULL,
        name TEXT, location TEXT, inferred_type TEXT,
        is_variable INTEGER, distinct_count INTEGER, sample_values TEXT,
        UNIQUE(endpoint_id, location, name))""",
    f"""CREATE TABLE IF NOT EXISTS url_fetches (
        id {_ID},
        endpoint_id INTEGER NOT NULL,
        concrete_url TEXT, params_json TEXT,
        fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
        http_status INTEGER, latency_ms INTEGER, ok INTEGER,
        response_bytes INTEGER, raw_json TEXT, error TEXT)""",
    f"""CREATE TABLE IF NOT EXISTS url_fields (
        id {_ID},
        endpoint_id INTEGER NOT NULL, run_at TEXT,
        field_path TEXT, dtype TEXT, fill_rate REAL, cardinality INTEGER,
        num_min REAL, num_max REAL, num_mean REAL,
        universe_overlap_pct REAL, changed_vs_last INTEGER)""",
    f"""CREATE TABLE IF NOT EXISTS url_field_correlations (
        id {_ID},
        endpoint_id INTEGER NOT NULL, run_at TEXT,
        field_path TEXT, target TEXT, n INTEGER,
        pearson REAL, spearman REAL, ic REAL)""",
    "CREATE INDEX IF NOT EXISTS ix_url_fetches_ep ON url_fetches(endpoint_id, fetched_at)",
    "CREATE INDEX IF NOT EXISTS ix_url_fields_ep ON url_fields(endpoint_id, run_at)",
    # Consolidation metadata (2026-09-13, url_explorer.ingest): discovery-corpus enrichment
    # lives on the shared catalog row so "which other endpoints cover this feature target"
    # is one query instead of a repo-wide grep. IF NOT EXISTS keeps ensure_schema idempotent
    # over catalogs created before this pass (the live one has 251 rows).
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS provider TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS category TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS description TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS feature_targets_json TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS sources_json TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS refs_json TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS updated_at TEXT",
    "ALTER TABLE url_endpoints ADD COLUMN IF NOT EXISTS verified_json TEXT",
    # Per-screener instance database (2026-09-13, url_explorer.screeners): the layer
    # between endpoint families and concrete captures — one row per (provider, scan_id)
    # with its captured payload and taxonomy. ue_* columns are urls-explorer's own
    # measured results, external evidence like verified_json.
    """CREATE TABLE IF NOT EXISTS screener_instances (
        provider TEXT NOT NULL,
        scan_id TEXT NOT NULL,
        name TEXT,
        category TEXT,
        sentiment TEXT,
        timeframe TEXT,
        endpoint TEXT,
        query_condition TEXT,
        description TEXT,
        ue_status TEXT,
        ue_stocks_count INTEGER,
        updated_at TEXT,
        PRIMARY KEY (provider, scan_id))""",
]


def ensure_schema() -> None:
    for ddl in _DDL:
        execute(ddl)


def upsert_endpoint(t) -> int:
    execute(
        """INSERT INTO url_endpoints (template, host, path_skeleton, param_keys, method, n_urls)
           VALUES (?, ?, ?, ?, ?, ?)
           ON CONFLICT(template) DO UPDATE SET
             host=excluded.host, path_skeleton=excluded.path_skeleton,
             param_keys=excluded.param_keys, n_urls=excluded.n_urls""",
        (t.template, t.host, t.path_skeleton, json.dumps(t.query_keys), t.method, len(t.urls)),
    )
    row = query_one("SELECT id FROM url_endpoints WHERE template = ?", (t.template,))
    return int(row["id"])


def upsert_params(endpoint_id: int, params) -> None:
    for p in params:
        execute(
            """INSERT INTO url_params (endpoint_id, name, location, inferred_type,
                 is_variable, distinct_count, sample_values)
               VALUES (?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT(endpoint_id, location, name) DO UPDATE SET
                 inferred_type=excluded.inferred_type, is_variable=excluded.is_variable,
                 distinct_count=excluded.distinct_count, sample_values=excluded.sample_values""",
            (endpoint_id, p.name, p.location, p.inferred_type,
             1 if p.is_variable else 0, p.distinct_count, json.dumps(p.sample_values)),
        )


def update_endpoint_meta(endpoint_id: int, *, provider, category, description,
                         feature_targets, sources, refs, verified=None) -> None:
    execute(
        """UPDATE url_endpoints SET provider = ?, category = ?, description = ?,
             feature_targets_json = ?, sources_json = ?, refs_json = ?, verified_json = ?,
             updated_at = ?
           WHERE id = ?""",
        (provider, category, description,
         json.dumps(feature_targets), json.dumps(sources), json.dumps(refs),
         json.dumps(verified) if verified is not None else None,
         datetime.now(timezone.utc).isoformat(), endpoint_id),
    )


def upsert_screener_instance(inst: dict) -> None:
    execute(
        """INSERT INTO screener_instances (provider, scan_id, name, category, sentiment,
             timeframe, endpoint, query_condition, description, ue_status,
             ue_stocks_count, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT (provider, scan_id) DO UPDATE SET
             name = excluded.name, category = excluded.category,
             sentiment = excluded.sentiment, timeframe = excluded.timeframe,
             endpoint = excluded.endpoint, query_condition = excluded.query_condition,
             description = excluded.description, ue_status = excluded.ue_status,
             ue_stocks_count = excluded.ue_stocks_count, updated_at = excluded.updated_at""",
        (inst["provider"], inst["scan_id"], inst.get("name"), inst.get("category"),
         inst.get("sentiment"), inst.get("timeframe"), inst.get("endpoint"),
         inst.get("query_condition"), inst.get("description"), inst.get("ue_status"),
         inst.get("ue_stocks_count"), datetime.now(timezone.utc).isoformat()),
    )


def record_health(endpoint_id: int, ok: bool, error: str | None = None) -> None:
    status = "ok" if ok else f"fail: {error or 'unknown'}"[:160]
    execute(
        "UPDATE url_endpoints SET last_run_at = ?, last_status = ? WHERE id = ?",
        (datetime.now(timezone.utc).isoformat(), status, endpoint_id),
    )


def insert_fetch(endpoint_id, concrete_url, params_json, http_status,
                 latency_ms, ok, response_bytes, raw_json, error) -> int:
    execute(
        """INSERT INTO url_fetches (endpoint_id, concrete_url, params_json, http_status,
             latency_ms, ok, response_bytes, raw_json, error)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (endpoint_id, concrete_url, params_json, http_status, latency_ms,
         1 if ok else 0, response_bytes, raw_json, error),
    )
    row = query_one("SELECT MAX(id) AS id FROM url_fetches WHERE endpoint_id = ?", (endpoint_id,))
    return int(row["id"])


def insert_field(endpoint_id, run_at, p) -> None:
    execute(
        """INSERT INTO url_fields (endpoint_id, run_at, field_path, dtype, fill_rate,
             cardinality, num_min, num_max, num_mean, universe_overlap_pct, changed_vs_last)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (endpoint_id, run_at, p.field_path, p.dtype, p.fill_rate, p.cardinality,
         p.num_min, p.num_max, p.num_mean, p.universe_overlap_pct,
         1 if p.changed_vs_last else 0),
    )


def insert_correlation(endpoint_id, run_at, c) -> None:
    execute(
        """INSERT INTO url_field_correlations (endpoint_id, run_at, field_path, target, n,
             pearson, spearman, ic) VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        (endpoint_id, run_at, c.field_path, c.target, c.n, c.pearson, c.spearman, c.ic),
    )


def last_run_field_paths(endpoint_id: int) -> set[str]:
    rows = query_all(
        """SELECT DISTINCT field_path FROM url_fields
           WHERE endpoint_id = ? AND run_at = (
             SELECT MAX(run_at) FROM url_fields WHERE endpoint_id = ?)""",
        (endpoint_id, endpoint_id),
    )
    return {r["field_path"] for r in rows}
