import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import path from "path";
import { parseSchemaFile, diffSchemas, isClean, formatReport, type SchemaMap } from "../checkSchemaDrift";

const FIXTURE_SQL = `
-- GENERATED by scripts/generate_pg_schema.py — do not edit by hand.
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ── widgets ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "widgets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "price" DOUBLE PRECISION,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "note" TEXT DEFAULT 'a, b, (c)' -- a default containing commas and parens, must not confuse the splitter
);
CREATE INDEX idx_widgets_name ON widgets(name);

-- ── screener_master_fixture ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "screener_master_fixture" (
  "scan_id" TEXT,
  "source" TEXT NOT NULL,
  "name" TEXT,
  PRIMARY KEY ("source", "scan_id")
);
`;

function toMap(obj: Record<string, string[]>): SchemaMap {
  return new Map(Object.entries(obj).map(([k, v]) => [k, new Set(v)]));
}

describe("parseSchemaFile", () => {
  it("extracts table names and their real columns, excluding table-level constraints", () => {
    const parsed = parseSchemaFile(FIXTURE_SQL);
    expect([...parsed.keys()].sort()).toEqual(["screener_master_fixture", "widgets"]);
    expect(parsed.get("widgets")).toEqual(new Set(["id", "name", "price", "created_at", "note"]));
  });

  it("does not misread a composite PRIMARY KEY table constraint as a column", () => {
    const parsed = parseSchemaFile(FIXTURE_SQL);
    const cols = parsed.get("screener_master_fixture")!;
    expect(cols).toEqual(new Set(["scan_id", "source", "name"]));
    expect(cols.has("PRIMARY KEY")).toBe(false);
  });

  it("is not confused by parens/commas inside a column DEFAULT value", () => {
    const parsed = parseSchemaFile(FIXTURE_SQL);
    // If the paren/comma-depth tracking were wrong, this table would have picked up spurious
    // extra "columns" from inside the DEFAULT 'a, b, (c)' literal, or dropped the real ones
    // after it.
    expect(parsed.get("widgets")!.size).toBe(5);
  });

  it("returns an empty map for a file with no CREATE TABLE statements", () => {
    expect(parseSchemaFile("-- just a comment\nSELECT 1;").size).toBe(0);
  });

  it("parses the real repo db/schema.postgres.sql without throwing and finds a plausible table count", () => {
    // Smoke test against the actual generated file — proves the parser handles real-world
    // syntax (GENERATED BY DEFAULT AS IDENTITY, TIMESCALEDB extension lines, multi-line
    // multi-column tables), even though this sandbox has no live Postgres to diff against.
    const realFile = readFileSync(path.join(process.cwd(), "db", "schema.postgres.sql"), "utf-8");
    const parsed = parseSchemaFile(realFile);
    expect(parsed.size).toBeGreaterThan(100);
    // A table this session's own migration touched — asserts the composite PK line (a
    // TABLE-level constraint) is correctly excluded from its column set in the real file, not
    // just in a hand-written fixture.
    const screenerMaster = parsed.get("screener_master");
    expect(screenerMaster).toBeDefined();
    expect(screenerMaster!.has("scan_id")).toBe(true);
    expect(screenerMaster!.has("source")).toBe(true);
    expect(screenerMaster!.has("PRIMARY KEY")).toBe(false);
  });
});

describe("diffSchemas", () => {
  it("reports clean when both sides match exactly", () => {
    const a = toMap({ t: ["a", "b"] });
    const b = toMap({ t: ["a", "b"] });
    const report = diffSchemas(a, b);
    expect(isClean(report)).toBe(true);
  });

  it("reports a table only in the file", () => {
    const file = toMap({ t1: ["a"], t2: ["a"] });
    const live = toMap({ t1: ["a"] });
    const report = diffSchemas(file, live);
    expect(report.tablesOnlyInFile).toEqual(["t2"]);
    expect(report.tablesOnlyInLive).toEqual([]);
    expect(isClean(report)).toBe(false);
  });

  it("reports a table only in live — the exact case a pgEnsureColumns()-created table produces", () => {
    const file = toMap({ t1: ["a"] });
    const live = toMap({ t1: ["a"], t2: ["a"] });
    const report = diffSchemas(file, live);
    expect(report.tablesOnlyInLive).toEqual(["t2"]);
  });

  it("reports column-level drift only for tables present on both sides", () => {
    const file = toMap({ t: ["a", "b"] });
    const live = toMap({ t: ["a", "c"] });
    const report = diffSchemas(file, live);
    expect(report.columnsOnlyInFile).toEqual([{ table: "t", column: "b" }]);
    expect(report.columnsOnlyInLive).toEqual([{ table: "t", column: "c" }]);
  });

  it("does not double-report column drift for a table already reported as table-only", () => {
    const file = toMap({ onlyInFile: ["a", "b", "c"] });
    const live = toMap({});
    const report = diffSchemas(file, live);
    expect(report.tablesOnlyInFile).toEqual(["onlyInFile"]);
    expect(report.columnsOnlyInFile).toEqual([]);
  });
});

describe("formatReport", () => {
  it("prints a clean message with no drift sections when nothing differs", () => {
    const report = diffSchemas(toMap({ t: ["a"] }), toMap({ t: ["a"] }));
    expect(formatReport(report)).toMatch(/clean/i);
  });

  it("names every table and column difference so a human can act on it directly", () => {
    const file = toMap({ onlyFile: ["x"], both: ["a", "fileOnlyCol"] });
    const live = toMap({ onlyLive: ["y"], both: ["a", "liveOnlyCol"] });
    const text = formatReport(diffSchemas(file, live));
    expect(text).toContain("onlyFile");
    expect(text).toContain("onlyLive");
    expect(text).toContain("both.fileOnlyCol");
    expect(text).toContain("both.liveOnlyCol");
  });
});
