import { describe, it, expect } from "vitest";
import { buildSchemaFile } from "../generatePgSchemaFromLive";
import { parseSchemaFile } from "../checkSchemaDrift";

function baseData(overrides: Partial<Parameters<typeof buildSchemaFile>[0]> = {}) {
  return {
    extensions: ["timescaledb"],
    tables: ["widgets"],
    columns: [
      {
        table_name: "widgets",
        ordinal: 1,
        column_name: "id",
        data_type: "bigint",
        not_null: true,
        identity_flag: "d",
        default_expr: null,
      },
      {
        table_name: "widgets",
        ordinal: 2,
        column_name: "name",
        data_type: "text",
        not_null: true,
        identity_flag: "",
        default_expr: null,
      },
      {
        table_name: "widgets",
        ordinal: 3,
        column_name: "price",
        data_type: "double precision",
        not_null: false,
        identity_flag: "",
        default_expr: "0",
      },
    ],
    pks: [{ table_name: "widgets", column_name: "id", pos: 1 }],
    uniques: [],
    indexes: [],
    ...overrides,
  };
}

describe("buildSchemaFile", () => {
  it("emits an inline PRIMARY KEY for a single-column PK identity column", () => {
    const sql = buildSchemaFile(baseData());
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "widgets" (');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    // Identity columns must not also carry a redundant explicit NOT NULL.
    expect(sql).not.toMatch(/"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL/);
  });

  it("emits a table-level PRIMARY KEY line for a composite PK, not an inline one", () => {
    const data = baseData({
      tables: ["screener_master"],
      columns: [
        { table_name: "screener_master", ordinal: 1, column_name: "scan_id", data_type: "text", not_null: true, identity_flag: "", default_expr: null },
        { table_name: "screener_master", ordinal: 2, column_name: "source", data_type: "text", not_null: true, identity_flag: "", default_expr: null },
        { table_name: "screener_master", ordinal: 3, column_name: "name", data_type: "text", not_null: false, identity_flag: "", default_expr: null },
      ],
      pks: [
        { table_name: "screener_master", column_name: "source", pos: 1 },
        { table_name: "screener_master", column_name: "scan_id", pos: 2 },
      ],
    });
    const sql = buildSchemaFile(data);
    expect(sql).toContain('  PRIMARY KEY ("source", "scan_id")');
    // No column line should carry an inline PRIMARY KEY when the key is composite.
    expect(sql).not.toMatch(/"scan_id" TEXT NOT NULL PRIMARY KEY/);
    expect(sql).not.toMatch(/"source" TEXT NOT NULL PRIMARY KEY/);
  });

  it("emits a UNIQUE line for a non-PK unique constraint", () => {
    const data = baseData({
      uniques: [
        { table_name: "widgets", constraint_name: "widgets_name_key", column_name: "name", pos: 1 },
      ],
    });
    const sql = buildSchemaFile(data);
    expect(sql).toContain('  UNIQUE ("name")');
  });

  // 2026-08-19: a legacy `SERIAL`-style column (identity_flag === '', default_expr a bare
  // nextval(...)) used to be emitted as a plain DEFAULT with no backing CREATE SEQUENCE
  // anywhere in the file -- harmless on a real Postgres where the sequence already exists
  // from whenever the column was originally declared SERIAL, but fatal on a truly fresh
  // database (CI's throwaway test schema), where nothing has ever created it:
  // psycopg2.errors.UndefinedTable / relation "..._id_seq" does not exist. Broke CI on
  // mf_portfolio_holdings/portfolio_holdings the first time a schema:regen run happened to
  // pick this pattern up.
  it("treats a legacy SERIAL nextval() default as an identity column, not a dangling sequence reference", () => {
    const data = baseData({
      tables: ["mf_portfolio_holdings"],
      columns: [
        {
          table_name: "mf_portfolio_holdings", ordinal: 1, column_name: "id",
          data_type: "integer", not_null: true, identity_flag: "",
          default_expr: "nextval('mf_portfolio_holdings_id_seq'::regclass)",
        },
        { table_name: "mf_portfolio_holdings", ordinal: 2, column_name: "userId", data_type: "text", not_null: true, identity_flag: "", default_expr: null },
      ],
      pks: [{ table_name: "mf_portfolio_holdings", column_name: "id", pos: 1 }],
    });
    const sql = buildSchemaFile(data);
    expect(sql).toContain('"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).not.toContain("nextval(");
    expect(sql).not.toContain("_id_seq");
  });

  it("still emits an ordinary DEFAULT verbatim for a non-identity, non-nextval expression", () => {
    const sql = buildSchemaFile(baseData());
    expect(sql).toContain('"price" DOUBLE PRECISION DEFAULT 0');
  });

  it("includes every live-installed extension, not a hardcoded single one", () => {
    const sql = buildSchemaFile(baseData({ extensions: ["pg_trgm", "timescaledb"] }));
    expect(sql).toContain("CREATE EXTENSION IF NOT EXISTS pg_trgm;");
    expect(sql).toContain("CREATE EXTENSION IF NOT EXISTS timescaledb;");
  });

  it("appends the Timescale hypertable footer only for a known hypertable table", () => {
    const sql = buildSchemaFile(baseData({ tables: ["stock_ohlcv"], pks: [], columns: [
      { table_name: "stock_ohlcv", ordinal: 1, column_name: "symbol", data_type: "text", not_null: true, identity_flag: "", default_expr: null },
      { table_name: "stock_ohlcv", ordinal: 2, column_name: "date", data_type: "date", not_null: true, identity_flag: "", default_expr: null },
    ] }));
    expect(sql).toContain("SELECT create_hypertable('stock_ohlcv', 'date'");
    expect(sql).toContain("add_compression_policy('stock_ohlcv', INTERVAL '180 days'");
  });

  it("does not append a hypertable footer for a table not in the known hypertable set", () => {
    const sql = buildSchemaFile(baseData());
    expect(sql).not.toContain("create_hypertable('widgets'");
  });

  it("silently skips a table with zero readable columns rather than emitting an empty CREATE TABLE", () => {
    const sql = buildSchemaFile(baseData({ tables: ["widgets", "ghost_table"], columns: baseData().columns }));
    expect(sql).not.toContain('"ghost_table"');
  });

  it("round-trips through checkSchemaDrift's own parser with the exact column set intact", () => {
    // The real acceptance test for this generator: whatever it emits must be exactly what
    // scripts/checkSchemaDrift.ts can parse back out, or the two tools silently disagree with
    // each other about what "the schema" is.
    const sql = buildSchemaFile(baseData());
    const parsed = parseSchemaFile(sql);
    expect(parsed.get("widgets")).toEqual(new Set(["id", "name", "price"]));
  });

  it("round-trips a composite-PK table without the PRIMARY KEY line being misread as a column", () => {
    const data = baseData({
      tables: ["screener_master"],
      columns: [
        { table_name: "screener_master", ordinal: 1, column_name: "scan_id", data_type: "text", not_null: true, identity_flag: "", default_expr: null },
        { table_name: "screener_master", ordinal: 2, column_name: "source", data_type: "text", not_null: true, identity_flag: "", default_expr: null },
      ],
      pks: [
        { table_name: "screener_master", column_name: "source", pos: 1 },
        { table_name: "screener_master", column_name: "scan_id", pos: 2 },
      ],
    });
    const parsed = parseSchemaFile(buildSchemaFile(data));
    expect(parsed.get("screener_master")).toEqual(new Set(["scan_id", "source"]));
  });
});
