#!/usr/bin/env tsx
/**
 * Diffs the live Postgres schema against the checked-in db/schema.postgres.sql snapshot.
 *
 * Why this exists (2026-08-05 audit): db/schema.postgres.sql is *generated* — by
 * scripts/generate_pg_schema.py, from the local database.sqlite file, which is itself derived
 * from db.ts's CREATE TABLE statements — not hand-maintained independently. But nothing
 * regenerates or re-applies it automatically, and live production Postgres also receives ad-hoc
 * runtime column adds via pgEnsureColumns() that never touch database.sqlite/db.ts at all (the
 * project's own documented pattern). So three pictures of "the schema" can independently drift:
 * db.ts, the generated snapshot file, and what's actually live. This script only compares the
 * second and third — the ones a human can otherwise only catch by connecting to prod and
 * eyeballing information_schema, which is exactly what's already gone wrong before (e.g. the
 * 2026-07-24..27 node-pg-migrate-never-installed incident: a migration existed in git and was
 * believed live for 3 days before anyone checked).
 *
 * Usage:
 *   npx tsx scripts/checkSchemaDrift.ts
 *
 * Exit codes:
 *   0 — no drift (or nothing comparable found)
 *   1 — drift found (tables/columns present in one side but not the other)
 *   2 — could not connect to Postgres to compare (not a drift finding — e.g. no live DB
 *       reachable in this environment; treat as "unable to verify", not "clean")
 */
import { readFileSync } from "fs";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

export type SchemaMap = Map<string, Set<string>>;

export interface DriftReport {
  tablesOnlyInFile: string[];
  tablesOnlyInLive: string[];
  columnsOnlyInFile: Array<{ table: string; column: string }>;
  columnsOnlyInLive: Array<{ table: string; column: string }>;
}

const TABLE_LEVEL_CONSTRAINT_KEYWORDS = [
  "PRIMARY KEY",
  "UNIQUE",
  "CHECK",
  "CONSTRAINT",
  "FOREIGN KEY",
];

/**
 * Parses every `CREATE TABLE IF NOT EXISTS "name" ( ... );` block out of a Postgres DDL file
 * and returns table name -> set of real column names (table-level constraints like a trailing
 * `PRIMARY KEY ("a", "b")` line are recognized and excluded, not misread as columns).
 *
 * Deliberately hand-rolled rather than pulling in a full SQL parser dependency — the DDL this
 * repo generates (db/schema.postgres.sql) has one consistent shape (see generate_pg_schema.py),
 * so a depth-aware paren scanner is enough and avoids a new dependency for a single internal
 * tool. Column defaults/types can themselves contain parens (e.g. `DOUBLE PRECISION`,
 * `GENERATED BY DEFAULT AS IDENTITY`, `DEFAULT now()`) — a naive non-greedy regex would stop at
 * the first inner `)`, so this tracks paren depth explicitly instead.
 */
export function parseSchemaFile(sql: string): SchemaMap {
  const withoutComments = sql
    .split("\n")
    .map((line) => {
      const idx = line.indexOf("--");
      return idx === -1 ? line : line.slice(0, idx);
    })
    .join("\n");

  const result: SchemaMap = new Map();
  const tableRe = /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+"([^"]+)"\s*\(/gi;
  let match: RegExpExecArray | null;

  while ((match = tableRe.exec(withoutComments))) {
    const tableName = match[1];
    const bodyStart = match.index + match[0].length;
    const body = extractParenBody(withoutComments, bodyStart);
    if (body === null) continue; // malformed/unterminated block — skip rather than guess

    const columns = new Set<string>();
    for (const part of splitTopLevel(body)) {
      const trimmed = part.trim();
      if (!trimmed) continue;
      const upper = trimmed.toUpperCase();
      if (TABLE_LEVEL_CONSTRAINT_KEYWORDS.some((kw) => upper.startsWith(kw))) continue;
      const colMatch = trimmed.match(/^"([^"]+)"/);
      if (colMatch) columns.add(colMatch[1]);
    }
    result.set(tableName, columns);
  }

  return result;
}

/** Given the index just past an opening `(`, returns the substring up to its matching `)`. */
function extractParenBody(text: string, openIdx: number): string | null {
  let depth = 1;
  let i = openIdx;
  const start = openIdx;
  for (; i < text.length && depth > 0; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")") depth--;
  }
  if (depth !== 0) return null;
  return text.slice(start, i - 1);
}

/** Splits a parenthesized body on top-level commas only (ignores commas nested in sub-parens). */
function splitTopLevel(body: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  for (const ch of body) {
    if (ch === "(") depth++;
    if (ch === ")") depth--;
    if (ch === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  if (current.trim()) parts.push(current);
  return parts;
}

export function diffSchemas(fileSchema: SchemaMap, liveSchema: SchemaMap): DriftReport {
  const fileTables = new Set(fileSchema.keys());
  const liveTables = new Set(liveSchema.keys());

  const tablesOnlyInFile = [...fileTables].filter((t) => !liveTables.has(t)).sort();
  const tablesOnlyInLive = [...liveTables].filter((t) => !fileTables.has(t)).sort();

  const columnsOnlyInFile: Array<{ table: string; column: string }> = [];
  const columnsOnlyInLive: Array<{ table: string; column: string }> = [];

  for (const table of fileTables) {
    if (!liveTables.has(table)) continue; // already reported as a whole-table diff
    const fileCols = fileSchema.get(table)!;
    const liveCols = liveSchema.get(table)!;
    for (const col of fileCols) if (!liveCols.has(col)) columnsOnlyInFile.push({ table, column: col });
    for (const col of liveCols) if (!fileCols.has(col)) columnsOnlyInLive.push({ table, column: col });
  }

  columnsOnlyInFile.sort((a, b) => a.table.localeCompare(b.table) || a.column.localeCompare(b.column));
  columnsOnlyInLive.sort((a, b) => a.table.localeCompare(b.table) || a.column.localeCompare(b.column));

  return { tablesOnlyInFile, tablesOnlyInLive, columnsOnlyInFile, columnsOnlyInLive };
}

export function isClean(report: DriftReport): boolean {
  return (
    report.tablesOnlyInFile.length === 0 &&
    report.tablesOnlyInLive.length === 0 &&
    report.columnsOnlyInFile.length === 0 &&
    report.columnsOnlyInLive.length === 0
  );
}

export function formatReport(report: DriftReport): string {
  if (isClean(report)) return "Schema clean — db/schema.postgres.sql matches live Postgres.";
  const lines: string[] = ["Schema drift detected:"];
  if (report.tablesOnlyInFile.length) {
    lines.push(`\nTables in db/schema.postgres.sql but NOT live (stale snapshot, or table was dropped live without updating the file):`);
    for (const t of report.tablesOnlyInFile) lines.push(`  - ${t}`);
  }
  if (report.tablesOnlyInLive.length) {
    lines.push(`\nTables live but NOT in db/schema.postgres.sql (likely created via a migration or ad-hoc DDL never reflected back — the exact class of drift this script exists to catch):`);
    for (const t of report.tablesOnlyInLive) lines.push(`  - ${t}`);
  }
  if (report.columnsOnlyInFile.length) {
    lines.push(`\nColumns in the file but not live:`);
    for (const c of report.columnsOnlyInFile) lines.push(`  - ${c.table}.${c.column}`);
  }
  if (report.columnsOnlyInLive.length) {
    lines.push(`\nColumns live but not in the file (likely a pgEnsureColumns()/migration addition never regenerated into the snapshot):`);
    for (const c of report.columnsOnlyInLive) lines.push(`  - ${c.table}.${c.column}`);
  }
  return lines.join("\n");
}

async function fetchLiveSchema(): Promise<SchemaMap> {
  const { getPool } = await import("../src/server/pgClient");
  const pool = getPool();
  const { rows } = await pool.query<{ table_name: string; column_name: string }>(
    `SELECT table_name, column_name
     FROM information_schema.columns
     WHERE table_schema = 'public'
     ORDER BY table_name, column_name`
  );
  const map: SchemaMap = new Map();
  for (const row of rows) {
    if (!map.has(row.table_name)) map.set(row.table_name, new Set());
    map.get(row.table_name)!.add(row.column_name);
  }
  return map;
}

async function main() {
  const schemaPath = path.join(process.cwd(), "db", "schema.postgres.sql");
  const fileSchema = parseSchemaFile(readFileSync(schemaPath, "utf-8"));
  console.log(`Parsed ${fileSchema.size} tables from ${schemaPath}`);

  let liveSchema: SchemaMap;
  try {
    liveSchema = await fetchLiveSchema();
  } catch (err: any) {
    console.error(`Could not reach Postgres to compare: ${err?.message ?? err}`);
    console.error("(This is 'unable to verify', not a clean bill of health — run this where POSTGRES_URL is reachable, e.g. a cron job on the deployment host.)");
    process.exit(2);
  }
  console.log(`Fetched ${liveSchema.size} tables from live Postgres`);

  const report = diffSchemas(fileSchema, liveSchema);
  console.log("\n" + formatReport(report));
  process.exit(isClean(report) ? 0 : 1);
}

const isMainModule =
  typeof process.argv[1] === "string" &&
  pathToFileURL(process.argv[1]).href === import.meta.url;
if (isMainModule) {
  main().catch((err) => {
    console.error("checkSchemaDrift failed:", err);
    process.exit(2);
  });
}
