"""
SQLite -> PostgreSQL/TimescaleDB schema generator
==================================================
Reads the LIVE SQLite schema (database.sqlite) and emits db/schema.postgres.sql:
  - CREATE TABLE for every table (type-mapped), preserving PK / NOT NULL / defaults
  - CREATE INDEX for every non-autoindex index
  - Timescale hypertable + columnar compression + retention for the big append-only
    time-series tables

This is generated (not hand-maintained) so it stays in sync with the canonical SQLite
schema as Phase 1/2 migrations evolve. Re-run after any schema change:

    python scripts/generate_pg_schema.py

CHECK and FOREIGN KEY constraints are intentionally omitted from the generated DDL:
the application enforces them, and they complicate a bulk COPY-based data load. They
can be re-added post-migration if desired.

Run output is reviewed, then applied once Docker/Timescale is up:
    docker compose up -d timescaledb
    psql "$POSTGRES_URL" -f db/schema.postgres.sql
"""

from pathlib import Path
import sqlite3, re

ROOT = Path(__file__).parent.parent
DB_PATH = ROOT / "database.sqlite"
OUT_PATH = ROOT / "db" / "schema.postgres.sql"

# Tables to skip entirely (SQLite internals / migration bookkeeping recreated by app).
SKIP = {"sqlite_sequence", "sqlite_stat1", "sqlite_stat4"}

# Timescale hypertables: table -> (time_column, chunk_interval, compress_after, retain_after|None)
HYPERTABLES = {
    "stock_ohlcv":        ("date",        "90 days",  "180 days", None),
    "feature_store":      ("date",        "90 days",  "120 days", None),
    "confluence_signals": ("computed_at", "7 days",   "30 days",  "90 days"),
    # Phase-4 time-series scaffolding (empty today, ready as hypertables):
    "intraday_ohlcv":     ("datetime",    "7 days",   "30 days",  "365 days"),
    "tick_data":          ("tick_time",   "1 day",    "7 days",   "30 days"),
    "macro_asset_prices": ("date",        "365 days", None,       None),
}


def map_type(decl: str, is_pk_autoinc: bool) -> str:
    """Map a SQLite declared type to a Postgres type."""
    if is_pk_autoinc:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    t = (decl or "").upper().strip()
    if "INT" in t:
        return "BIGINT"
    if any(k in t for k in ("CHAR", "CLOB", "TEXT")):
        return "TEXT"
    if any(k in t for k in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "DATE" in t or "TIME" in t:
        return "TIMESTAMPTZ"
    if "BOOL" in t:
        return "INTEGER"   # codebase stores 0/1
    if t == "":
        return "TEXT"
    return "TEXT"


def map_default(dflt: str, pgtype: str) -> str | None:
    if dflt is None:
        return None
    d = dflt.strip()
    up = d.upper()
    if "CURRENT_TIMESTAMP" in up or "STRFTIME" in up or "DATETIME('NOW'" in up.replace(" ", ""):
        return "now()"
    return d  # numeric / quoted-string / literal defaults pass through unchanged


def table_ddl(conn: sqlite3.Connection, table: str) -> str:
    create_sql = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()[0] or ""
    autoinc = "AUTOINCREMENT" in create_sql.upper()

    cols = conn.execute(f"PRAGMA table_info('{table}')").fetchall()  # cid,name,type,notnull,dflt,pk
    pk_cols = [c[1] for c in sorted([c for c in cols if c[5] > 0], key=lambda c: c[5])]
    single_int_pk = len(pk_cols) == 1 and autoinc

    lines = []
    for _, name, decl, notnull, dflt, pk in cols:
        is_ai = single_int_pk and pk == 1 and "INT" in (decl or "").upper()
        pgtype = map_type(decl, is_ai)
        parts = [f'  "{name}" {pgtype}']
        if notnull and not is_ai:
            parts.append("NOT NULL")
        dv = map_default(dflt, pgtype)
        if dv is not None:
            parts.append(f"DEFAULT {dv}")
        lines.append(" ".join(parts))

    if pk_cols:
        if single_int_pk:
            # IDENTITY column carries PRIMARY KEY inline
            lines = [l + " PRIMARY KEY" if l.strip().startswith(f'"{pk_cols[0]}"') else l for l in lines]
        else:
            quoted = ", ".join(f'"{c}"' for c in pk_cols)
            lines.append(f"  PRIMARY KEY ({quoted})")

    return f'CREATE TABLE IF NOT EXISTS "{table}" (\n' + ",\n".join(lines) + "\n);"


def index_ddls(conn: sqlite3.Connection, table: str) -> list[str]:
    out = []
    idxs = conn.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='index' AND tbl_name=? AND sql IS NOT NULL",
        (table,),
    ).fetchall()
    for name, sql in idxs:
        if name.startswith("sqlite_autoindex"):
            continue
        # SQLite and Postgres CREATE INDEX syntax overlap for these simple cases;
        # just normalise identifier quoting (SQLite backticks/none -> Postgres double quotes optional).
        out.append(sql.rstrip(";") + ";")
    return out


def hypertable_ddls(table: str) -> list[str]:
    if table not in HYPERTABLES:
        return []
    tcol, chunk, compress_after, retain_after = HYPERTABLES[table]
    out = [
        f"SELECT create_hypertable('{table}', '{tcol}', chunk_time_interval => INTERVAL '{chunk}', "
        f"if_not_exists => TRUE, migrate_data => TRUE);"
    ]
    if compress_after:
        out.append(
            f"ALTER TABLE {table} SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');"
        )
        out.append(
            f"SELECT add_compression_policy('{table}', INTERVAL '{compress_after}', if_not_exists => TRUE);"
        )
    if retain_after:
        out.append(f"SELECT add_retention_policy('{table}', INTERVAL '{retain_after}', if_not_exists => TRUE);")
    return out


def main():
    conn = sqlite3.connect(DB_PATH)
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall() if r[0] not in SKIP]

    blocks = [
        "-- GENERATED by scripts/generate_pg_schema.py — do not edit by hand.",
        "-- Apply with:  psql \"$POSTGRES_URL\" -f db/schema.postgres.sql",
        "CREATE EXTENSION IF NOT EXISTS timescaledb;",
        "",
    ]
    hyper_section = ["", "-- ── Timescale hypertables / compression / retention ──────────────────────"]

    for t in tables:
        blocks.append(f"-- ── {t} ─────────────────────────────────────────────")
        blocks.append(table_ddl(conn, t))
        blocks.extend(index_ddls(conn, t))
        blocks.append("")
        hyper_section.extend(hypertable_ddls(t))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(blocks + hyper_section) + "\n", encoding="utf-8")
    conn.close()
    print(f"[schema] wrote {OUT_PATH}  ({len(tables)} tables, "
          f"{sum(1 for t in tables if t in HYPERTABLES)} hypertables)")


if __name__ == "__main__":
    main()
