const j=(n,l,s,f,c,d,ds,u)=>({name:n,label:l,scheduleIST:s,frequency:f,category:c,dataFetched:d,dataSource:ds,urls:u});
const b=[];
b.push(j('stock-refresh','Stock Price Refresh','16:00 IST','Mon-Fri','Intraday','Daily OHLCV sync','Yahoo Finance','query1.finance.yahoo.com/v8/finance/chart/{SYMBOL}.NS'));
b.push(j('intraday-fetcher','Intraday OHLCV','08:30-15:30 IST (15min)','Mon-Fri','Intraday','15-min bars','MoneyControl','priceapi.moneycontrol.com/techCharts/history'));
b.push(j('market-regime-refresh','Market Regime','09:15-15:30 IST (30min)','Mon-Fri','Intraday','Regime detection','Internal','stock_ohlcv'));
b.push(j('intraday-ranker','Intraday Ranker','09:15-15:30 IST (30min)','Mon-Fri','Intraday','Ranking scores','Internal','stock_scores'));
b.push(j('live-screener-collect','Live Screener','09:15-15:30 IST (15min)','Mon-Fri','Intraday','Screener membership','Trendlyne','kayal.trendlyne.com/...'));
b.push(j('et-marketstats-sync','ET Marketstats','18:00 IST','Mon-Fri','Screener Sync','ET screeners','ET Marketstats','etapi.indiatimes.com/et-screener/v2/technical-data'));
b.push(j('mc-screener-sync','MC Screener','18:20 IST','Mon-Fri','Screener Sync','ProScanner membership','MoneyControl','api.moneycontrol.com/mcapi/v1/proscanner/scanner-detail'));
b.push(j('etnow-screener-sync','ETNow Screener','18:40 IST','Mon-Fri','Screener Sync','Screener membership','ETNow','screener.indiatimes.com/screener/v2/screenerByScreenerIdForWeb'));
b.push(j('trendlyne-screener-sync','Trendlyne Screener','18:40 IST','Mon-Fri','Screener Sync','Screener membership','Trendlyne','kayal.trendlyne.com/...'));
b.push(j('quant-eod-sync','Quant EOD','19:30 IST','Mon-Fri','Quant Sync','NT scores + TL snapshots','NiftyTrader','webapi.niftytrader.in/webapi/Analysis/...'));
b.push(j('research-premarket','Pre-Market Research','08:30 IST','Mon-Fri','Research','Pre-market report','Internal','DB data'));
b.push(j('outcome-resolver','Outcome Resolver','09:30 IST','Mon-Fri','Research','Trade P&L resolution','Python','outcome_resolver.py'));
b.push(j('research-postclose','Post-Close Research','16:15 IST','Mon-Fri','Research','Post-close report','Internal','DB data'));
b.push(j('chatbot-reingest','Chatbot Reingest','01:30 IST','Daily','ML/AI','Embeddings re-ingestion','Ollama','news_articles, stock_fundamentals'));
b.push(j('agent-data-scientist','Agent: Data Scientist','07:00 IST','Mon-Fri','Agent','Data quality report','Python','agents/data_scientist_agent.py'));
b.push(j('agent-strategist','Agent: Strategist','08:50 IST','Mon-Fri','Agent','Strategy picks','Python','agents/strategist_agent.py'));
b.push(j('agent-auditor','Agent: Auditor','16:30 IST','Mon-Fri','Agent','Trade audit report','Python','agents/auditor_agent.py'));
b.push(j('agent-optimizer','Agent: Optimizer','17:30 IST','Mon-Fri','Agent','ML weight optimization','Python','agents/optimizer_agent.py'));
b.push(j('stock-scoring','Stock Scoring','18:30 IST','Mon-Fri','Scoring','Composite score recalc','Internal','recalculateScores()'));
b.push(j('quant-scoring','Quant Scoring','20:50 IST','Mon-Fri','Scoring','Quantitative scoring','Internal','quantScoringService'));
b.push(j('confluence-compute','Confluence Compute','22:30-07:59 IST (30min)','Daily','Confluence','Signal computation','Python','confluence_compute.py'));
b.push(j('confluence-outcomes','Confluence Outcomes','21:10 IST','Mon-Fri','Confluence','Outcome tracking + ML','Python','confluence_outcome_tracker.py'));
b.push(j('unified-ranker','Unified Ranker','22:30 IST','Mon-Fri','Ranking','Multi-factor ranking','Python','unified_ranker.py'));
b.push(j('recommendations-digest','Recommendations','22:40 IST','Mon-Fri','Digest','Telegram recommendations','Internal','stock_recommendations'));
b.push(j('job-digest','Job Digest (Night)','22:50 IST','Daily','Digest','Telegram job health','Internal','job_heartbeat'));
b.push(j('job-digest-morning','Job Digest (Morning)','08:15 IST','Daily','Digest','Morning job health','Internal','job_heartbeat'));
b.push(j('data-quality-daily','Data Quality Report','23:00 IST','Daily','Data Quality','25-check report','Internal','dataQualityChecks.ts'));
module.exports=b;
