const j=(n,l,s,f,c,d,ds,u)=>({name:n,label:l,scheduleIST:s,frequency:f,category:c,dataFetched:d,dataSource:ds,urls:u});
const b=[];
b.push(j('dl-macro-fetch','DL: Macro Fetch','18:30 IST','Mon-Fri','Deep Learning','Global macro data','MC APIs','global_macro_fetcher.py'));
b.push(j('dl-feature-refresh','DL: Feature Refresh','19:30 IST','Mon-Fri','Deep Learning','Feature store refresh','Python','feature_store.py'));
b.push(j('dl-inference','DL: Inference','21:30 IST','Mon-Fri','Deep Learning','DL predictions','Python','dl_engine_infer.py'));
b.push(j('dl-regime-update','DL: Regime Update','16:45 IST','Mon-Fri','Deep Learning','Regime detection','Python','regime_detector.py'));
b.push(j('screener-performance','Screener Performance','02:30 IST','Mon-Fri','Sync','Performance tracking','Python','screener_performance.py'));
b.push(j('company-profiles-sync','Company Profiles','21:00 IST','Mon-Fri','Sync','Profile sync + AI','Trendlyne+Ollama','trendlyne_overview_fetcher.py'));
b.push(j('nse-sync','NSE Sync','07:30 IST (Sun)','Weekly','Sync','Bhavcopy + sectors','NSE India','archives.nseindia.com/sec_bhavdata_full.csv'));
b.push(j('corporate-actions-ingest','Corporate Actions','19:30 IST (Sat)','Weekly','Sync','Splits, bonuses','Python','ohlcv_quality.py'));
b.push(j('index-membership','Index Membership','21:05 IST','Mon-Fri','Sync','Index membership','Python','index_membership_fetcher.py'));
b.push(j('analyst-estimates-sync','Analyst Estimates','19:45 IST','Mon-Fri','Sync','Estimates snapshot','Python','analyst_estimates_snapshot.py'));
b.push(j('trendlyne-daily-fetch','Trendlyne Daily','09:15-15:30 IST (15min)','Mon-Fri','Trendlyne','Adv technical analysis','Trendlyne','trendlyne.com/equity/api/stock/adv-technical-analysis/{tlid}/24/'));
b.push(j('trendlyne-checklist-cycle','TL Checklist','24/7','Continuous','Trendlyne','Checklist checks','Trendlyne','trendlyne.com/fundamentals/checklist/{tlid}/'));
b.push(j('trendlyne-catchup','TL Catchup','Every 20 min','Continuous','Trendlyne','4 fetchers rotating','Trendlyne','trendlyne.com/equity/api/stock/...'));
b.push(j('ohlcv-backfill','OHLCV Backfill','07:30 IST (Sun)','Weekly','Trendlyne','Gap-fill from bhavcopy','NSE India','nse_bhavcopy_fetcher.py'));
b.push(j('fundamentals-sync','Fundamentals Sync','08:30 IST (Sat)','Weekly','ML Weekly','Deep fundamentals','ET Markets','etmarketsapis.indiatimes.com/ET_Stats/mobile'));
b.push(j('ml-daily-ops','ML Daily Ops','19:30 IST','Mon-Fri','ML Weekly','Ensemble, score, drift','Python','ml_ensemble.py'));
b.push(j('ml-weekly-retrain','ML Weekly Retrain','10:30 IST (Sat)','Weekly','ML Weekly','Ensemble retrain','Python','ml_ensemble.py --train'));
b.push(j('dl-retrain-weekly','DL Weekly Retrain','11:30 IST (Sat)','Weekly','Deep Learning','DL retrain','Python','dl_trainer.py'));
b.push(j('trendlyne-midweek','TL Midweek','20:00 IST (Tue)','Weekly','Trendlyne','Adv-tech + price','Trendlyne','trendlyne_adv_tech_fetcher.py'));
b.push(j('trendlyne-ratios-monthly','TL Ratios','06:00 IST (Sat)','Weekly','Trendlyne','Financial ratios','ET Markets','financial_ratios_fetcher.py'));
b.push(j('tickertape-scorecard','Tickertape','18:30 IST (Sat)','Weekly','Sync','Scorecard','Tickertape','tickertape_scorecard_fetcher.py'));
const p=[];
p.push(j('gf-screener-daily','GF: Screener Daily','22:30 IST (Mon-Fri)','Mon-Fri','Greenfield','Screener data','TypeScript','greenfield/packages/ingestion/...'));
p.push(j('gf-divergence-daily','GF: Divergence','22:15 IST (Mon-Fri)','Mon-Fri','Greenfield','Divergence analysis','TypeScript','greenfield/packages/ingestion/...'));
p.push(j('gf-kayal-weekly','GF: Kayal Weekly','07:30 IST (Sat)','Weekly','Greenfield','Screener membership','TypeScript','greenfield/packages/ingestion/...'));
p.push(j('gf-fundamentals-weekly','GF: Fundamentals','09:30 IST (Sat)','Weekly','Greenfield','Fundamentals transfer','TypeScript','greenfield/packages/ingestion/...'));
p.push(j('gf-analyst-estimates-weekly','GF: Analyst Est.','11:30 IST (Sat)','Weekly','Greenfield','Analyst estimates','TypeScript','greenfield/packages/ingestion/...'));
p.push(j('gf-insider-activity-weekly','GF: Insider Activity','12:00 IST (Sat)','Weekly','Greenfield','Insider activity','TypeScript','greenfield/packages/ingestion/...'));
p.push(j('pg-backup-nightly','PostgreSQL Backup','23:30 IST','Daily','Backup','pg_dump backup','pg_dump','scripts/backup_pg.py'));
module.exports={b,p};
